<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="2.1 Histograms, boxplots, and density curves | Intermediate Statistics with R" />
<meta property="og:type" content="book" />



<meta name="github-repo" content="gpeterson406/Greenwood_Book" />

<meta name="author" content="Mark C Greenwood" />


<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="2.1 Histograms, boxplots, and density curves | Intermediate Statistics with R">

<title>2.1 Histograms, boxplots, and density curves | Intermediate Statistics with R</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<link rel="stylesheet" href="toc.css" type="text/css" />

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#cover">Cover</a></li>
<li><a href="acknowledgments.html#acknowledgments">Acknowledgments</a></li>
<li class="has-sub"><a href="1-chapter1.html#chapter1"><span class="toc-section-number">1</span> Preface</a><ul>
<li><a href="1-1-section1-1.html#section1-1"><span class="toc-section-number">1.1</span> Overview of methods</a></li>
<li><a href="1-2-section1-2.html#section1-2"><span class="toc-section-number">1.2</span> Getting started in R</a></li>
<li><a href="1-3-section1-3.html#section1-3"><span class="toc-section-number">1.3</span> Basic summary statistics, histograms, and boxplots using R</a></li>
<li><a href="1-4-section1-4.html#section1-4"><span class="toc-section-number">1.4</span> Chapter summary</a></li>
<li><a href="1-5-section1-5.html#section1-5"><span class="toc-section-number">1.5</span> Summary of important R code</a></li>
<li><a href="1-6-section1-6.html#section1-6"><span class="toc-section-number">1.6</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="2-chapter2.html#chapter2"><span class="toc-section-number">2</span> (R)e-Introduction to statistics</a><ul>
<li><a href="2-1-section2-1.html#section2-1"><span class="toc-section-number">2.1</span> Histograms, boxplots, and density curves</a></li>
<li><a href="2-2-section2-2.html#section2-2"><span class="toc-section-number">2.2</span> Pirate-plots</a></li>
<li><a href="2-3-section2-3.html#section2-3"><span class="toc-section-number">2.3</span> Models, hypotheses, and permutations for the two sample mean situation</a></li>
<li><a href="2-4-section2-4.html#section2-4"><span class="toc-section-number">2.4</span> Permutation testing for the two sample mean situation</a></li>
<li><a href="2-5-section2-5.html#section2-5"><span class="toc-section-number">2.5</span> Hypothesis testing (general)</a></li>
<li><a href="2-6-section2-6.html#section2-6"><span class="toc-section-number">2.6</span> Connecting randomization (nonparametric) and parametric tests</a></li>
<li><a href="2-7-section2-7.html#section2-7"><span class="toc-section-number">2.7</span> Second example of permutation tests</a></li>
<li><a href="2-8-section2-8.html#section2-8"><span class="toc-section-number">2.8</span> Reproducibility Crisis: Moving beyond p &lt; 0.05, publication bias, and multiple testing issues</a></li>
<li><a href="2-9-section2-9.html#section2-9"><span class="toc-section-number">2.9</span> Confidence intervals and bootstrapping</a></li>
<li><a href="2-10-section2-10.html#section2-10"><span class="toc-section-number">2.10</span> Bootstrap confidence intervals for difference in GPAs</a></li>
<li><a href="2-11-section2-11.html#section2-11"><span class="toc-section-number">2.11</span> Chapter summary</a></li>
<li><a href="2-12-section2-12.html#section2-12"><span class="toc-section-number">2.12</span> Summary of important R code</a></li>
<li><a href="2-13-section2-13.html#section2-13"><span class="toc-section-number">2.13</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="3-chapter3.html#chapter3"><span class="toc-section-number">3</span> One-Way ANOVA</a><ul>
<li><a href="3-1-section3-1.html#section3-1"><span class="toc-section-number">3.1</span> Situation</a></li>
<li><a href="3-2-section3-2.html#section3-2"><span class="toc-section-number">3.2</span> Linear model for One-Way ANOVA (cell-means and reference-coding)</a></li>
<li><a href="3-3-section3-3.html#section3-3"><span class="toc-section-number">3.3</span> One-Way ANOVA Sums of Squares, Mean Squares, and F-test</a></li>
<li><a href="3-4-section3-4.html#section3-4"><span class="toc-section-number">3.4</span> ANOVA model diagnostics including QQ-plots</a></li>
<li><a href="3-5-section3-5.html#section3-5"><span class="toc-section-number">3.5</span> Guinea pig tooth growth One-Way ANOVA example</a></li>
<li><a href="3-6-section3-6.html#section3-6"><span class="toc-section-number">3.6</span> Multiple (pair-wise) comparisons using Tukey’s HSD and the compact letter display</a></li>
<li><a href="3-7-section3-7.html#section3-7"><span class="toc-section-number">3.7</span> Pair-wise comparisons for the Overtake data</a></li>
<li><a href="3-8-section3-8.html#section3-8"><span class="toc-section-number">3.8</span> Chapter summary</a></li>
<li><a href="3-9-section3-9.html#section3-9"><span class="toc-section-number">3.9</span> Summary of important R code</a></li>
<li><a href="3-10-section3-10.html#section3-10"><span class="toc-section-number">3.10</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="4-chapter4.html#chapter4"><span class="toc-section-number">4</span> Two-Way ANOVA</a><ul>
<li><a href="4-1-section4-1.html#section4-1"><span class="toc-section-number">4.1</span> Situation</a></li>
<li><a href="4-2-section4-2.html#section4-2"><span class="toc-section-number">4.2</span> Designing a two-way experiment and visualizing results</a></li>
<li><a href="4-3-section4-3.html#section4-3"><span class="toc-section-number">4.3</span> Two-Way ANOVA models and hypothesis tests</a></li>
<li><a href="4-4-section4-4.html#section4-4"><span class="toc-section-number">4.4</span> Guinea pig tooth growth analysis with Two-Way ANOVA</a></li>
<li><a href="4-5-section4-5.html#section4-5"><span class="toc-section-number">4.5</span> Observational study example: The Psychology of Debt</a></li>
<li><a href="4-6-section4-6.html#section4-6"><span class="toc-section-number">4.6</span> Pushing Two-Way ANOVA to the limit: Un-replicated designs and Estimability</a></li>
<li><a href="4-7-section4-7.html#section4-7"><span class="toc-section-number">4.7</span> Chapter summary</a></li>
<li><a href="4-8-section4-8.html#section4-8"><span class="toc-section-number">4.8</span> Summary of important R code</a></li>
<li><a href="4-9-section4-9.html#section4-9"><span class="toc-section-number">4.9</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="5-chapter5.html#chapter5"><span class="toc-section-number">5</span> Chi-square tests</a><ul>
<li><a href="5-1-section5-1.html#section5-1"><span class="toc-section-number">5.1</span> Situation, contingency tables, and tableplots</a></li>
<li><a href="5-2-section5-2.html#section5-2"><span class="toc-section-number">5.2</span> Homogeneity test hypotheses</a></li>
<li><a href="5-3-section5-3.html#section5-3"><span class="toc-section-number">5.3</span> Independence test hypotheses</a></li>
<li><a href="5-4-section5-4.html#section5-4"><span class="toc-section-number">5.4</span> Models for R by C tables</a></li>
<li><a href="5-5-section5-5.html#section5-5"><span class="toc-section-number">5.5</span> Permutation tests for the <span class="math inline">\(X^2\)</span> statistic</a></li>
<li><a href="5-6-section5-6.html#section5-6"><span class="toc-section-number">5.6</span> Chi-square distribution for the <span class="math inline">\(X^2\)</span> statistic</a></li>
<li><a href="5-7-section5-7.html#section5-7"><span class="toc-section-number">5.7</span> Examining residuals for the source of differences</a></li>
<li><a href="5-8-section5-8.html#section5-8"><span class="toc-section-number">5.8</span> General protocol for <span class="math inline">\(X^2\)</span> tests</a></li>
<li><a href="5-9-section5-9.html#section5-9"><span class="toc-section-number">5.9</span> Political party and voting results: Complete analysis</a></li>
<li><a href="5-10-section5-10.html#section5-10"><span class="toc-section-number">5.10</span> Is cheating and lying related in students?</a></li>
<li><a href="5-11-section5-11.html#section5-11"><span class="toc-section-number">5.11</span> Analyzing a stratified random sample of California schools</a></li>
<li><a href="5-12-section5-12.html#section5-12"><span class="toc-section-number">5.12</span> Chapter summary</a></li>
<li><a href="5-13-section5-13.html#section5-13"><span class="toc-section-number">5.13</span> Summary of important R commands</a></li>
<li><a href="5-14-section5-14.html#section5-14"><span class="toc-section-number">5.14</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="6-chapter6.html#chapter6"><span class="toc-section-number">6</span> Correlation and Simple Linear Regression</a><ul>
<li><a href="6-1-section6-1.html#section6-1"><span class="toc-section-number">6.1</span> Relationships between two quantitative variables</a></li>
<li><a href="6-2-section6-2.html#section6-2"><span class="toc-section-number">6.2</span> Estimating the correlation coefficient</a></li>
<li><a href="6-3-section6-3.html#section6-3"><span class="toc-section-number">6.3</span> Relationships between variables by groups</a></li>
<li><a href="6-4-section6-4.html#section6-4"><span class="toc-section-number">6.4</span> Inference for the correlation coefficient</a></li>
<li><a href="6-5-section6-5.html#section6-5"><span class="toc-section-number">6.5</span> Are tree diameters related to tree heights?</a></li>
<li><a href="6-6-section6-6.html#section6-6"><span class="toc-section-number">6.6</span> Describing relationships with a regression model</a></li>
<li><a href="6-7-section6-7.html#section6-7"><span class="toc-section-number">6.7</span> Least Squares Estimation</a></li>
<li><a href="6-8-section6-8.html#section6-8"><span class="toc-section-number">6.8</span> Measuring the strength of regressions: R<sup>2</sup></a></li>
<li><a href="6-9-section6-9.html#section6-9"><span class="toc-section-number">6.9</span> Outliers: leverage and influence</a></li>
<li><a href="6-10-section6-10.html#section6-10"><span class="toc-section-number">6.10</span> Residual diagnostics – setting the stage for inference</a></li>
<li><a href="6-11-section6-11.html#section6-11"><span class="toc-section-number">6.11</span> Old Faithful discharge and waiting times</a></li>
<li><a href="6-12-section6-12.html#section6-12"><span class="toc-section-number">6.12</span> Chapter summary</a></li>
<li><a href="6-13-section6-13.html#section6-13"><span class="toc-section-number">6.13</span> Summary of important R code</a></li>
<li><a href="6-14-section6-14.html#section6-14"><span class="toc-section-number">6.14</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="7-chapter7.html#chapter7"><span class="toc-section-number">7</span> Simple linear regression inference</a><ul>
<li><a href="7-1-section7-1.html#section7-1"><span class="toc-section-number">7.1</span> Model</a></li>
<li><a href="7-2-section7-2.html#section7-2"><span class="toc-section-number">7.2</span> Confidence interval and hypothesis tests for the slope and intercept</a></li>
<li><a href="7-3-section7-3.html#section7-3"><span class="toc-section-number">7.3</span> Bozeman temperature trend</a></li>
<li><a href="7-4-section7-4.html#section7-4"><span class="toc-section-number">7.4</span> Randomization-based inferences for the slope coefficient</a></li>
<li><a href="7-5-section7-5.html#section7-5"><span class="toc-section-number">7.5</span> Transformations part I: Linearizing relationships</a></li>
<li><a href="7-6-section7-6.html#section7-6"><span class="toc-section-number">7.6</span> Transformations part II: Impacts on SLR interpretations: log(y), log(x), &amp; both log(y) &amp; log(x)</a></li>
<li><a href="7-7-section7-7.html#section7-7"><span class="toc-section-number">7.7</span> Confidence interval for the mean and prediction intervals for a new observation</a></li>
<li><a href="7-8-section7-8.html#section7-8"><span class="toc-section-number">7.8</span> Chapter summary</a></li>
<li><a href="7-9-section7-9.html#section7-9"><span class="toc-section-number">7.9</span> Summary of important R code</a></li>
<li><a href="7-10-section7-10.html#section7-10"><span class="toc-section-number">7.10</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="8-chapter8.html#chapter8"><span class="toc-section-number">8</span> Multiple linear regression</a><ul>
<li><a href="8-1-section8-1.html#section8-1"><span class="toc-section-number">8.1</span> Going from SLR to MLR</a></li>
<li><a href="8-2-section8-2.html#section8-2"><span class="toc-section-number">8.2</span> Validity conditions in MLR</a></li>
<li><a href="8-3-section8-3.html#section8-3"><span class="toc-section-number">8.3</span> Interpretation of MLR terms</a></li>
<li><a href="8-4-section8-4.html#section8-4"><span class="toc-section-number">8.4</span> Comparing multiple regression models</a></li>
<li><a href="8-5-section8-5.html#section8-5"><span class="toc-section-number">8.5</span> General recommendations for MLR interpretations and VIFs</a></li>
<li><a href="8-6-section8-6.html#section8-6"><span class="toc-section-number">8.6</span> MLR inference: Parameter inferences using the t-distribution</a></li>
<li><a href="8-7-section8-7.html#section8-7"><span class="toc-section-number">8.7</span> Overall F-test in multiple linear regression</a></li>
<li><a href="8-8-section8-8.html#section8-8"><span class="toc-section-number">8.8</span> Case study: First year college GPA and SATs</a></li>
<li><a href="8-9-section8-9.html#section8-9"><span class="toc-section-number">8.9</span> Different intercepts for different groups: MLR with indicator variables</a></li>
<li><a href="8-10-section8-10.html#section8-10"><span class="toc-section-number">8.10</span> Additive MLR with more than two groups: Headache example</a></li>
<li><a href="8-11-section8-11.html#section8-11"><span class="toc-section-number">8.11</span> Different slopes and different intercepts</a></li>
<li><a href="8-12-section8-12.html#section8-12"><span class="toc-section-number">8.12</span> F-tests for MLR models with quantitative and categorical variables and interactions</a></li>
<li><a href="8-13-section8-13.html#section8-13"><span class="toc-section-number">8.13</span> AICs for model selection</a></li>
<li><a href="8-14-section8-14.html#section8-14"><span class="toc-section-number">8.14</span> Case study: Forced expiratory volume model selection using AICs</a></li>
<li><a href="8-15-section8-15.html#section8-15"><span class="toc-section-number">8.15</span> Chapter summary</a></li>
<li><a href="8-16-section8-16.html#section8-16"><span class="toc-section-number">8.16</span> Summary of important R code</a></li>
<li><a href="8-17-section8-17.html#section8-17"><span class="toc-section-number">8.17</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="9-chapter9.html#chapter9"><span class="toc-section-number">9</span> Case studies</a><ul>
<li><a href="9-1-section9-1.html#section9-1"><span class="toc-section-number">9.1</span> Overview of material covered</a></li>
<li><a href="9-2-section9-2.html#section9-2"><span class="toc-section-number">9.2</span> The impact of simulated chronic nitrogen deposition on the biomass and N2-fixation activity of two boreal feather moss–cyanobacteria associations</a></li>
<li><a href="9-3-section9-3.html#section9-3"><span class="toc-section-number">9.3</span> Ants learn to rely on more informative attributes during decision-making</a></li>
<li><a href="9-4-section9-4.html#section9-4"><span class="toc-section-number">9.4</span> Multi-variate models are essential for understanding vertebrate diversification in deep time</a></li>
<li><a href="9-5-section9-5.html#section9-5"><span class="toc-section-number">9.5</span> What do didgeridoos really do about sleepiness?</a></li>
<li><a href="9-6-section9-6.html#section9-6"><span class="toc-section-number">9.6</span> General summary</a></li>
</ul></li>
<li><a href="references.html#references">References</a></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="section2-1" class="section level2">
<h2><span class="header-section-number">2.1</span> Histograms, boxplots, and density curves</h2>
<p>Part of learning statistics is learning to correctly use the terminology, some of which is used colloquially
differently than it is used in formal statistical settings. The most commonly
“misused” statistical term is <strong><em>data</em></strong>.   In statistical parlance, we want to note the plurality of
data. Specifically, <strong><em>datum</em></strong> is a single measurement, possibly on multiple random
variables, and so it is appropriate to say that “<strong>a datum is…</strong>”.
Once we move to discussing data, we are now referring to more than one
observation, again on one, or possibly more than one, random variable, and
so we need to use “<strong>data are…</strong>” when talking about our observations. We want
to distinguish our use of the term “data” from its more
colloquial<a href="#fn12" class="footnote-ref" id="fnref12"><sup>12</sup></a> usage that often involves treating it as singular.
In a statistical setting
“data” refers to measurements of our cases or units. When we summarize the
results of a study (say providing the mean and SD), that information is not
“data”. We used our data to generate that information. Sometimes we also use
the term “data set” to refer to all our observations and this is a singular
term to refer to the group of observations and this makes it really easy to
make mistakes on the usage of “data”<a href="#fn13" class="footnote-ref" id="fnref13"><sup>13</sup></a>.</p>
<p>It is also really important to note that <strong><em>variables</em></strong> have to vary –
if you measure the level of education of your subjects but all are high school graduates, then you do
not have a “variable”. You may not know if you have real variability in a
“variable” until you explore the results you obtained.</p>
<p>The last, but probably most important, aspect of data is the context
of the measurement. The “who, what, when, and where” of the collection
of the observations is critical to the
sort of conclusions we can make based on the results. The information on the
study design provides information required to assess the scope of inference of
the study.  Generally, remember to think about the research questions the
researchers were trying to answer and whether their study actually would answer
those questions. There are no formulas to help us sort some of these things
out, just critical thinking about the context of the measurements.</p>
<p>To make this concrete, consider the data collected from a study
<span class="citation">(<span class="citeproc-not-found" data-reference-id="Walker2014"><strong>???</strong></span>)</span> to investigate whether clothing worn by a bicyclist might impact the passing distance of cars. One of the author’s wore seven different outfits (outfit for the day was chosen randomly by shuffling seven playing cards) on his regular 26 km commute near London in the United Kingdom. Using a specially instrumented bicycle, they measured how close the vehicles passed to the widest point on the handlebars. The seven outfits (“conditions”) that you can view graphically at <a href="https://www.sciencedirect.com/science/article/pii/S0001457513004636" class="uri">https://www.sciencedirect.com/science/article/pii/S0001457513004636</a> were:</p>
<ul>
<li><p>COMMUTE: Plain cycling jersey and pants, reflective cycle clips, commuting helmet, and bike gloves.</p></li>
<li><p>CASUAL: Rugby shirt with pants tucked into socks, wool hat or baseball cap, plain gloves, and small backpack.</p></li>
<li><p>HIVIZ: Bright yellow reflective cycle commuting jacket, plain pants, reflective cycle clips, commuting helmet, and bike gloves.</p></li>
<li><p>RACER: Colorful, skin-tight, Tour de France cycle jersey with sponsor logos, Lycra bike shorts or tights, race helmet, and bike gloves.</p></li>
<li><p>NOVICE: Yellow reflective vest with “Novice Cyclist, Pass Slowly” and plain pants, reflective cycle clips, commuting helmet, and bike gloves.</p></li>
<li><p>POLICE: Yellow reflective vest with “POLICEwitness.com – Move Over – Camera Cyclist” and plain pants, reflective cycle clips, commuting helmet, and bike gloves.</p></li>
<li><p>POLITE: Yellow reflective vest with blue and white checked banding and the words “POLITE notice, Pass Slowly” looking similar to a police jacket and plain pants, reflective cycle clips, commuting helmet, and bike gloves.</p></li>
</ul>
<p>They collected data (distance to the vehicle in cm for each car “overtake”) on between 8 and 11 rides in each outfit and between 737 and 868 “overtakings” across these rides. The outfit is a categorical <em>predictor</em> or <em>explanatory</em> variable)  that has seven different levels here. The distance is the <em>response</em> variable  and is a quantitative variable here<a href="#fn14" class="footnote-ref" id="fnref14"><sup>14</sup></a>. Note that we do not have the information on which overtake came from which ride in the data provided or the conditions related to individual overtake observations other than the distance to the vehicle (they only included overtakings that had consistent conditions for the road and riding).</p>
<p>The data are posted on my website<a href="#fn15" class="footnote-ref" id="fnref15"><sup>15</sup></a> at <a href="http://www.math.montana.edu/courses/s217/documents/Walker2014_mod.csv" class="uri">http://www.math.montana.edu/courses/s217/documents/Walker2014_mod.csv</a> if you want to download the file to a local directory and then import the data into R using “Import Dataset”. Or you can use the code in the following codechunk to directly read the data set into R using the URL.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" title="1"><span class="kw">suppressMessages</span>(<span class="kw">library</span>(readr))</a>
<a class="sourceLine" id="cb24-2" title="2">dd &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;http://www.math.montana.edu/courses/s217/documents/Walker2014_mod.csv&quot;</span>)</a></code></pre></div>
<p>It is always good to review the data you have read by running the code and printing the tibble  by typing the tibble name (here <code>&gt; dd</code>) at the command prompt in the console, using the <code>View</code> function, (here <code>View(dd)</code>), to open a spreadsheet-like view, or using the <code>head</code> and <code>tail</code> functions have been show the first and last ten observations:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" title="1"><span class="kw">head</span>(dd)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 8
##   Condition Distance Shirt Helmet Pants Gloves ReflectClips Backpack
##   &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;        &lt;chr&gt;   
## 1 casual         132 Rugby hat    plain plain  no           yes     
## 2 casual         137 Rugby hat    plain plain  no           yes     
## 3 casual         174 Rugby hat    plain plain  no           yes     
## 4 casual          82 Rugby hat    plain plain  no           yes     
## 5 casual         106 Rugby hat    plain plain  no           yes     
## 6 casual          48 Rugby hat    plain plain  no           yes</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" title="1"><span class="kw">tail</span>(dd)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 8
##   Condition Distance Shirt      Helmet Pants Gloves ReflectClips Backpack
##   &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;        &lt;chr&gt;   
## 1 racer          122 TourJersey race   lycra bike   yes          no      
## 2 racer          204 TourJersey race   lycra bike   yes          no      
## 3 racer          116 TourJersey race   lycra bike   yes          no      
## 4 racer          132 TourJersey race   lycra bike   yes          no      
## 5 racer          224 TourJersey race   lycra bike   yes          no      
## 6 racer           72 TourJersey race   lycra bike   yes          no</code></pre>
<p>Another option is to directly access specific rows and/or columns of the tibble, especially for larger data sets. In objects containing data, we can select certain rows and columns using the <strong><em>brackets</em></strong>, <code>[..., ...]</code>, to specify the row (first element) and column (second element). For example, we can extract the datum in the fourth row and second column using <code>dd[4,2]</code>:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" title="1">dd[<span class="dv">4</span>,<span class="dv">2</span>]</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   Distance
##      &lt;dbl&gt;
## 1       82</code></pre>
<p>This provides the distance (in cm) of a pass at 82 cm. To get all of either the rows or columns, a space is used instead of specifying a particular number. For example, the information in all the columns on the fourth observation can be obtained using <code>dd[4, ]</code>:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" title="1">dd[<span class="dv">4</span>,]</a></code></pre></div>
<pre><code>## # A tibble: 1 x 8
##   Condition Distance Shirt Helmet Pants Gloves ReflectClips Backpack
##   &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;        &lt;chr&gt;   
## 1 casual          82 Rugby hat    plain plain  no           yes</code></pre>
<p>So this was an observation from the <code>casual</code> condition that had a passing distance of 82 cm. The other columns describe some other specific aspects of the condition. To get a more complete sense of the data set, we can extract a suite of observations from each condition using their row numbers concatenated, <code>c()</code>, together, extracting all columns for two observations from each of the conditions based on their rows.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" title="1">dd[<span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">780</span>, <span class="dv">781</span>, <span class="dv">1637</span>, <span class="dv">1638</span>, <span class="dv">2374</span>, <span class="dv">2375</span>, <span class="dv">3181</span>, <span class="dv">3182</span>, <span class="dv">3971</span>, <span class="dv">3972</span>, <span class="dv">4839</span>, <span class="dv">4840</span>),]</a></code></pre></div>
<pre><code>## # A tibble: 14 x 8
##    Condition Distance Shirt      Helmet  Pants Gloves ReflectClips Backpack
##    &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;        &lt;chr&gt;   
##  1 casual         132 Rugby      hat     plain plain  no           yes     
##  2 casual         137 Rugby      hat     plain plain  no           yes     
##  3 commute         70 PlainJers~ commut~ plain bike   yes          no      
##  4 commute        151 PlainJers~ commut~ plain bike   yes          no      
##  5 hiviz           94 Jacket     commut~ plain bike   yes          no      
##  6 hiviz          145 Jacket     commut~ plain bike   yes          no      
##  7 novice          12 Vest_Novi~ commut~ plain bike   yes          no      
##  8 novice         122 Vest_Novi~ commut~ plain bike   yes          no      
##  9 police         113 Vest_Poli~ commut~ plain bike   yes          no      
## 10 police         174 Vest_Poli~ commut~ plain bike   yes          no      
## 11 polite         156 Vest_Poli~ commut~ plain bike   yes          no      
## 12 polite          14 Vest_Poli~ commut~ plain bike   yes          no      
## 13 racer          104 TourJersey race    lycra bike   yes          no      
## 14 racer          141 TourJersey race    lycra bike   yes          no</code></pre>
<p>Now we can see the <code>Condition</code> variable seems to have seven different levels, the <code>Distance</code> variable contains the overtake distance, and then a suite of columns that describe aspects of each outfit, such as the type of shirt or whether reflective cycling clips were used or not. We will only use the “Distance” and “Condition” variables to start with.</p>
<p>When working with data, we should always start with
summarizing the sample size. We will use <strong><em>n</em></strong>  for the
number of subjects in the sample and denote the population size (if
available) with <strong><em>N</em></strong>.  Here, the sample size is <strong><em>n=5690</em></strong>. In
this situation, we do not have a random sample from a population 
(these were all of the overtakes that met the criteria during the rides) so we cannot make inferences from our sample to a larger group (other rides or for other situations like different places, times, or riders).
But we can assess whether there is a  <strong><em>causal effect</em></strong><a href="#fn16" class="footnote-ref" id="fnref16"><sup>16</sup></a>: if sufficient evidence is found to conclude that there is some difference in
the responses across the conditions, we can attribute those differences to
the treatments applied, since the overtake events should be same otherwise due to the
outfit being randomly assigned to the rides. The story of the data set –
that it was collected on a particular route for a particular rider in the UK – becomes pretty important in thinking about
the ramifications of any results. Are drivers in Montana or South Dakota different from drivers near London? Are the road and traffic conditions likely to be different? If so,
then we should not assume that the detected differences, if detected, would
also exist in some other location for a different rider. The lack of a random sample  here from all the overtakes in the area (or more generally all that happen around the world) makes it impossible to assume that this set of overtakes might be like others. So there are definite limitations to the inferences in the following
results. But it is still interesting to see if the outfits worn caused a difference
in the mean overtake distances, even though the inferences are limited to the conditions in this individual’s commute. If this had been an observational study (suppose that the
researcher could select their outfit), then we would have to avoid
any of the “causal” language that we can consider here because the outfits
were not randomly assigned to the rides. Without random assignment,  the
explanatory variable of outfit choice could be <strong><em>confounded</em></strong> 
with another characteristic of rides that might be related to the passing distances, such as wearing a particular outfit because of an expectation of heavy traffic or poor light conditions. Confounding is not the only reason to avoid causal
statements with non-random assignment but the inability to separate the effect
of other variables (measured or unmeasured) from the differences we are
observing means that our inferences in these situations need to be carefully
stated to avoid implying causal effects.</p>
<p>In order to get some summary statistics, we will rely on the R package called
<code>mosaic</code> <span class="citation">(Pruim, Kaplan, and Horton <a href="#ref-R-mosaic" role="doc-biblioref">2019</a>)</span> as introduced previously. First (but only once),
you need to install the package, which can
be done either using the Packages tab in the lower right panel of RStudio or
using the <code>install.packages</code> function with quotes around the package name:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" title="1"><span class="op">&gt;</span><span class="st"> </span><span class="kw">install.packages</span>(<span class="st">&quot;mosaic&quot;</span>)</a></code></pre></div>
<p>If you open a .Rmd file that contains code that incorporates packages and they are not installed, the bar at the top of the markdown document will prompt you to install those missing packages. This is the easiest way to get packages you might need installed. After making sure that any required packages are installed, use the <code>library</code>
function around the package name (no quotes now!) to load the package, something that
you need to do any time you want to use features of a package.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" title="1"><span class="kw">library</span>(mosaic)</a></code></pre></div>
<p>When you are loading a package, R might mention a need to install other packages. If the output says that it needs a package that is
unavailable, then follow the same process noted above to install that package
and then repeat trying to load the package you wanted. These are called package “dependencies” and are due to one package developer relying on functions that already exist in another package.</p>
<p>With tibbles, you have to declare categorical variables as “factors” to have R correctly handle the variables using the <code>factor</code> function. This can be a bit time repetitive but provides some utility for data wrangling in more complex situations to read in the data and then declare their type. For quantitative variables, this is not required and they are stored as numeric variables. The following code declares the categorical variables in the data set as factors and saves them back into the variables of the same names:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" title="1">dd<span class="op">$</span>Condition &lt;-<span class="st"> </span><span class="kw">factor</span>(dd<span class="op">$</span>Condition)</a>
<a class="sourceLine" id="cb37-2" title="2">dd<span class="op">$</span>Shirt &lt;-<span class="st"> </span><span class="kw">factor</span>(dd<span class="op">$</span>Shirt) </a>
<a class="sourceLine" id="cb37-3" title="3">dd<span class="op">$</span>Helmet &lt;-<span class="st"> </span><span class="kw">factor</span>(dd<span class="op">$</span>Helmet)</a>
<a class="sourceLine" id="cb37-4" title="4">dd<span class="op">$</span>Pants &lt;-<span class="st"> </span><span class="kw">factor</span>(dd<span class="op">$</span>Pants)</a>
<a class="sourceLine" id="cb37-5" title="5">dd<span class="op">$</span>Gloves &lt;-<span class="st"> </span><span class="kw">factor</span>(dd<span class="op">$</span>Gloves)</a>
<a class="sourceLine" id="cb37-6" title="6">dd<span class="op">$</span>ReflectClips &lt;-<span class="st"> </span><span class="kw">factor</span>(dd<span class="op">$</span>ReflectClips)</a>
<a class="sourceLine" id="cb37-7" title="7">dd<span class="op">$</span>Backpack &lt;-<span class="st"> </span><span class="kw">factor</span>(dd<span class="op">$</span>Backpack) </a></code></pre></div>
<p>With many variables in a data set, it is often useful to get some
quick information about all of them; the <code>summary</code> function provides
useful information whether the variables are categorical or
quantitative and notes if any values were missing. </p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" title="1"><span class="kw">summary</span>(dd)</a></code></pre></div>
<pre><code>##    Condition      Distance             Shirt          Helmet    
##  casual :779   Min.   :  2.0   Jacket     :737   commuter:4059  
##  commute:857   1st Qu.: 99.0   PlainJersey:857   hat     : 779  
##  hiviz  :737   Median :117.0   Rugby      :779   race    : 852  
##  novice :807   Mean   :117.1   TourJersey :852                  
##  police :790   3rd Qu.:134.0   Vest_Novice:807                  
##  polite :868   Max.   :274.0   Vest_Police:790                  
##  racer  :852                   Vest_Polite:868                  
##    Pants        Gloves     ReflectClips Backpack  
##  lycra: 852   bike :4911   no : 779     no :4911  
##  plain:4838   plain: 779   yes:4911     yes: 779  
##                                                   
##                                                   
##                                                   
##                                                   
## </code></pre>
<p>The output is organized by variable,
providing summary information based on the type of
variable, either counts by category for categorical variables or the 5-number summary plus the mean for the quantitative
variable <code>Distance</code>. If present, you would also get a count of missing values that are
called “NAs” in R.  For the first variable, called <code>Condition</code> and that we might more explicitly name <em>Outfit</em>, we find counts of the
number of overtakes for each outfit: <span class="math inline">\(779\)</span> out of <span class="math inline">\(5,690\)</span> were when wearing the casual outfit, <span class="math inline">\(857\)</span> for “commute”, and the other observations from the other five outfits, with the most observations when wearing the “polite” vest.
We can also see that overtake distances (variable
<code>Distance</code>) ranged from 2 cm to 274 cm with a median of 117 cm.</p>
<p>To accompany the numerical summaries, histograms and boxplots can
provide some initial information on the shape of the distribution of
the responses for the different <em>Outfits</em>. Figure <a href="2-1-section2-1.html#fig:Figure2-1">2.1</a>
contains the histogram
and boxplot of <em>Distance</em>, ignoring any information on which outfit was being worn. The calls to the two plotting functions are
enhanced slightly to add better labels using <code>xlab</code>, <code>ylab</code>, and <code>main</code>.</p>

<div class="figure"><span id="fig:Figure2-1"></span>
<img src="02-reintroductionToStatistics_files/figure-html/Figure2-1-1.png" alt="Histogram and boxplot of passing distances in cm." width="576" />
<p class="caption">
Figure 2.1: Histogram and boxplot of passing distances in cm.
</p>
</div>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" title="1"><span class="kw">hist</span>(dd<span class="op">$</span>Distance, <span class="dt">xlab=</span><span class="st">&quot;Distance (cm)&quot;</span>, <span class="dt">labels=</span>T, <span class="dt">main=</span><span class="st">&quot;Histogram of Distances&quot;</span>)</a>
<a class="sourceLine" id="cb40-2" title="2"><span class="kw">boxplot</span>(dd<span class="op">$</span>Distance, <span class="dt">ylab=</span><span class="st">&quot;Distance (cm)&quot;</span>, <span class="dt">main=</span><span class="st">&quot;Boxplot of Distances&quot;</span>)</a></code></pre></div>
<p>The distribution appears to be relatively symmetric with many observations in both tails flagged as potential
outliers. Despite being flagged as potential outliers, they seem to be part of a common distribution. In real data sets, outliers are commonly encountered and the
first step is to verify that they were not errors in recording (if so, fixing or removing them is easily justified). If they cannot be easily dismissed or fixed, the next step
is to study their impact on the statistical analyses performed, potentially
considering reporting results with and without the influential observation(s)
in the results (if there are just handful). If the analysis is unaffected by the “unusual” observations,
then it matters little whether they are dropped or not. If they do affect the
results, then reporting both versions of results allows the reader to judge the
impacts for themselves. It is important to remember that sometimes the outliers
are the most interesting part of the data set.  For example, those observations that were the closest would be of great interest, whether they are outliers or not.</p>
<p>Often when statisticians think of distributions of data, we think
of the smooth underlying
shape that led to the data set that is being displayed in the histogram.
Instead of binning up observations and making bars in the histogram, we can
estimate what is called a <strong><em>density curve</em></strong> as a smooth curve
that represents the observed distribution of the responses. Density curves can
sometimes help us see features of the data sets more clearly. </p>
<p>To understand the density curve, it is useful to initially see
the histogram and density curve together. The height of the density curve is scaled
so that the total area under the curve<a href="#fn17" class="footnote-ref" id="fnref17"><sup>17</sup></a> is 1. To make a comparable histogram, the
y-axis needs to be scaled so that the histogram is also on the “density”
scale which makes the bar heights adjust so that the proportion of the
total data set in each bar is represented by the area in each bar
(remember that area is height times width). So the height depends on the
width of the bars and the total area across all the bars has to be 1. In the
<code>hist</code> function, the <code>freq=F</code> option does this required re-scaling to get
density-scaled histogram bars. The
density curve is added to the histogram using the R code of
<code>lines(density())</code>, producing the result in Figure <a href="2-1-section2-1.html#fig:Figure2-2">2.2</a> with
added modifications of options for <code>lwd</code> (line width) and <code>col</code> (color)
to make the plot more visually appealing. You can see how the density curve
somewhat matches the histogram bars but deals with the bumps up and down
and edges a little differently. We can pick out the relatively symmetric distribution using
either display and will rarely make both together.</p>

<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" title="1"><span class="kw">hist</span>(dd<span class="op">$</span>Distance, <span class="dt">freq=</span>F, <span class="dt">xlab=</span><span class="st">&quot;Distance (cm)&quot;</span>, <span class="dt">labels=</span>T, <span class="dt">main=</span><span class="st">&quot;Histogram of Distances&quot;</span>)</a>
<a class="sourceLine" id="cb41-2" title="2"><span class="kw">lines</span>(<span class="kw">density</span>(dd<span class="op">$</span>Distance), <span class="dt">lwd=</span><span class="dv">3</span>,<span class="dt">col=</span><span class="st">&quot;purple&quot;</span>)</a></code></pre></div>
<div class="figure"><span id="fig:Figure2-2"></span>
<img src="02-reintroductionToStatistics_files/figure-html/Figure2-2-1.png" alt="Histogram and density curve of Distance responses." width="480" />
<p class="caption">
Figure 2.2: Histogram and density curve of Distance responses.
</p>
</div>
<p>Histograms can be sensitive to the choice of the number of bars and
even the cut-offs used to define the bins for a given number of bars.
Small changes in the definition of cut-offs for the bins can have
noticeable impacts on the shapes observed but
this does not impact density curves. We are not going to tinker with the
default choices for bars in histogram, as they are reasonably selected in R, but we
can add information on the original observations being included in each bar to
better understand the choices that <code>hist</code> is making. In the previous
display, we can add what is called a <strong><em>rug</em></strong> to the plot, where a tick
mark is made on the x-axis for each observation.  Because the responses appear to be rounded to the nearest cm, there is some discreteness in the responses and we need to use a graphical
technique called <strong><em>jittering</em></strong> to add a little noise<a href="#fn18" class="footnote-ref" id="fnref18"><sup>18</sup></a> to each observation so all the
observations at each distance value do not
plot as a single line.  In Figure <a href="2-1-section2-1.html#fig:Figure2-3">2.3</a>, the added tick marks
on the x-axis show the approximate locations of the original observations.
We can (barely) see how there are 2 observations at 2 cm (the noise
added generates a wider line than for an individual observation so it is possible to see that it is more than one observation there). A limitation of the
histogram arises at the center of the distribution where the bar that goes from 100 to 120 cm suggests that the mode (peak) is in this range (but it is unclear where) but the density curve suggests that the peak is closer to 120 than 100. The
density curve also shows some small bumps in the tails of the distributions tied to individual observations that are not really displayed in the histogram. Density curves are, however,
not perfect and this one shows a tiny bit of area for distances less than 0 cm which is
not possible here. When we make density curves below, we will cut off the curves at the most extreme values to avoid this issue.</p>

<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" title="1"><span class="kw">hist</span>(dd<span class="op">$</span>Distance, <span class="dt">freq=</span>F, <span class="dt">xlab=</span><span class="st">&quot;Distance (cm)&quot;</span>, <span class="dt">labels=</span>T, <span class="dt">main=</span><span class="st">&quot;Histogram of Distances with density curve and rug&quot;</span>, <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="fl">0.017</span>))</a>
<a class="sourceLine" id="cb42-2" title="2"><span class="kw">lines</span>(<span class="kw">density</span>(dd<span class="op">$</span>Distance), <span class="dt">lwd=</span><span class="dv">3</span>,<span class="dt">col=</span><span class="st">&quot;purple&quot;</span>)</a>
<a class="sourceLine" id="cb42-3" title="3"><span class="kw">set.seed</span>(<span class="dv">900</span>)</a>
<a class="sourceLine" id="cb42-4" title="4"><span class="kw">rug</span>(<span class="kw">jitter</span>(dd<span class="op">$</span>Distance), <span class="dt">col=</span><span class="st">&quot;red&quot;</span>, <span class="dt">lwd=</span><span class="dv">1</span>)</a></code></pre></div>
<div class="figure"><span id="fig:Figure2-3"></span>
<img src="02-reintroductionToStatistics_files/figure-html/Figure2-3-1.png" alt="Histogram with density curve and rug plot of the jittered distance responses." width="480" />
<p class="caption">
Figure 2.3: Histogram with density curve and rug plot of the jittered distance responses.
</p>
</div>
<p>The graphical tools we’ve just discussed are going to help us move to comparing the
distribution of responses across more than one group. We will have two displays
that will help us make these comparisons. The simplest is
the <strong><em>side-by-side boxplot</em></strong>, where a boxplot is displayed for each group
of interest using the same y-axis scaling.  In R, we can use its <strong><em>formula</em></strong>
notation to see if the response (<code>Distance</code>) differs based on the group
(<code>Condition</code>) by using something like <code>Y~X</code> or, here, <code>Distance~Condition</code>.
We also need to tell R where to find the variables – use the last option in the command, <code>data=DATASETNAME</code> , to inform R of the tibble to look in
to find the variables. In this example, <code>data=dd</code>. We will use
the formula and <code>data=...</code> options in almost every function we use
from here forward. Figure <a href="2-1-section2-1.html#fig:Figure2-4">2.4</a> contains the side-by-side
boxplots showing similar distributions for all the groups, with a slightly higher median in the “police” group and some outliers identified in all groups.</p>

<div class="figure"><span id="fig:Figure2-4"></span>
<img src="02-reintroductionToStatistics_files/figure-html/Figure2-4-1.png" alt="Side-by-side boxplot of distances based on outfits." width="480" />
<p class="caption">
Figure 2.4: Side-by-side boxplot of distances based on outfits.
</p>
</div>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" title="1"><span class="kw">boxplot</span>(Distance <span class="op">~</span><span class="st"> </span>Condition, <span class="dt">data=</span>dd)</a></code></pre></div>
<p>The “~” (which is read as the <em>tilde</em> symbol<a href="#fn19" class="footnote-ref" id="fnref19"><sup>19</sup></a>, which you can find in the
upper left corner of your keyboard) notation will be used in two ways this
semester.  The formula use in R employed previously declares that the
response variable here is <em>Distance</em> and the explanatory variable is <em>Condition</em>.
The other use for “~” is as shorthand for “is distributed as” and is used in
the context of <span class="math inline">\(Y \sim N(0,1)\)</span>, which translates (in statistics) to defining the
random variable <em>Y</em> as following a Normal distribution<a href="#fn20" class="footnote-ref" id="fnref20"><sup>20</sup></a>

with mean 0
and standard deviation of 1. In the current situation, we could ask whether
the <code>Distance</code> variable seems like it may follow a normal distribution in each group, in
other words, is <span class="math inline">\(\text{Years}\sim N(\mu,\sigma^2)\)</span>? Since the responses are relatively symmetric, it is not clear that we have a violation of the assumption of the normality assumption for the <em>Distance</em> variable for any of the seven groups (more later on how we can assess this and the issues that occur when we have a violation of this assumption). Remember that
<span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span> are parameters where
<span class="math inline">\(\mu\)</span> (“mu”) is our standard symbol for the <strong><em>population mean</em></strong>
and that <span class="math inline">\(\sigma\)</span> (“sigma”) is the symbol of the
<strong><em>population standard deviation</em></strong>.  </p>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-R-mosaic">
<p>Pruim, Randall, Daniel T. Kaplan, and Nicholas J. Horton. 2019. <em>Mosaic: Project Mosaic Statistics and Mathematics Teaching Utilities</em>. <a href="https://CRAN.R-project.org/package=mosaic">https://CRAN.R-project.org/package=mosaic</a>.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="12">
<li id="fn12"><p>You will more typically hear “data is” but that more often refers to
information, sometimes even statistical summaries of data sets, than to
observations made on subjects collected as part of a study, suggesting the confusion of this
term in the general public. We will explore a data set in Chapter <a href="5-chapter5.html#chapter5"><strong>??</strong></a>
related to perceptions of this issue collected by researchers at
<a href="http://fivethirtyeight.com/" class="uri">http://fivethirtyeight.com/</a>.<a href="2-1-section2-1.html#fnref12" class="footnote-back">↩</a></p></li>
<li id="fn13"><p>Either try to remember “data is a plural word” or replace “data” with “things” in your sentence and consider whether it sounds right.<a href="2-1-section2-1.html#fnref13" class="footnote-back">↩</a></p></li>
<li id="fn14"><p>Of particular interest to the bicycle rider might be the “close” passes and we will revisit this as a categorical response with “close” and “not close” as its two categories later.<a href="2-1-section2-1.html#fnref14" class="footnote-back">↩</a></p></li>
<li id="fn15"><p>Thanks to Ian Walker for allowing us to use these data.<a href="2-1-section2-1.html#fnref15" class="footnote-back">↩</a></p></li>
<li id="fn16"><p>As noted previously, we reserve the term “effect” for situations where random assignment  allows us to consider causality as the reason for the differences in the response variable among levels of the explanatory variable, but this is only the case if we find evidence against the null hypothesis of no difference
in the groups.<a href="2-1-section2-1.html#fnref16" class="footnote-back">↩</a></p></li>
<li id="fn17"><p>If you’ve taken calculus, you will
know that the
curve is being constructed so that the integral from <span class="math inline">\(-\infty\)</span> to
<span class="math inline">\(\infty\)</span> is 1. If you don’t know calculus, think of a rectangle with area
of 1 based on its height and width. These cover the same area but the top of the
region wiggles.<a href="2-1-section2-1.html#fnref17" class="footnote-back">↩</a></p></li>
<li id="fn18"><p>Jittering typically
involves adding random variability to each observation that
is uniformly distributed in a range determined based on the spacing of the
observation. The idea is to jitter just enough to see all the points but not too much. This means that if you re-run the <code>jitter</code> function, the results will change if you do not set the random number seed using <code>set.seed</code> that is discussed more below.
For more details, type <code>help(jitter)</code> in the console in RStudio.<a href="2-1-section2-1.html#fnref18" class="footnote-back">↩</a></p></li>
<li id="fn19"><p>If you want to type this character in Rmarkdown, try “<span class="math inline">\(\sim\)</span>” outside of codechunks.<a href="2-1-section2-1.html#fnref19" class="footnote-back">↩</a></p></li>
<li id="fn20"><p>Remember the
bell-shaped curve you encountered in introductory statistics? If not, you can
see some at <a href="https://en.wikipedia.org/wiki/Normal_distribution" class="uri">https://en.wikipedia.org/wiki/Normal_distribution</a>.<a href="2-1-section2-1.html#fnref20" class="footnote-back">↩</a></p></li>
</ol>
</div>
<p style="text-align: center;">
<a href="2-chapter2.html"><button class="btn btn-default">Previous</button></a>
<a href="2-2-section2-2.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
