<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta property="og:title" content="A Second Semester Statistics Course with R" />
<meta property="og:type" content="book" />



<meta name="github-repo" content="gpeterson406/Greenwood_Book" />

<meta name="author" content="Mark C Greenwood" />


<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="A Second Semester Statistics Course with R">

<title>A Second Semester Statistics Course with R</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<link rel="stylesheet" href="toc.css" type="text/css" />

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#cover">Cover</a></li>
<li><a href="acknowledgments.html#acknowledgments">Acknowledgments</a></li>
<li class="has-sub"><a href="1-chapter1.html#chapter1"><span class="toc-section-number">1</span> Preface</a><ul>
<li><a href="1-1-section1-1.html#section1-1"><span class="toc-section-number">1.1</span> Overview of methods</a></li>
<li><a href="1-2-section1-2.html#section1-2"><span class="toc-section-number">1.2</span> Getting started in R</a></li>
<li><a href="1-3-section1-3.html#section1-3"><span class="toc-section-number">1.3</span> Basic summary statistics, histograms, and boxplots using R</a></li>
<li><a href="1-4-section1-4.html#section1-4"><span class="toc-section-number">1.4</span> Chapter summary</a></li>
<li><a href="1-5-section1-5.html#section1-5"><span class="toc-section-number">1.5</span> Summary of important R code</a></li>
<li><a href="1-6-section1-6.html#section1-6"><span class="toc-section-number">1.6</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="2-chapter2.html#chapter2"><span class="toc-section-number">2</span> (R)e-Introduction to statistics</a><ul>
<li><a href="2-1-section2-1.html#section2-1"><span class="toc-section-number">2.1</span> Histograms, boxplots, and density curves</a></li>
<li><a href="2-2-section2-2.html#section2-2"><span class="toc-section-number">2.2</span> Beanplots</a></li>
<li><a href="2-3-section2-3.html#section2-3"><span class="toc-section-number">2.3</span> Models, hypotheses, and permutations for the two sample mean situation</a></li>
<li><a href="2-4-section2-4.html#section2-4"><span class="toc-section-number">2.4</span> Permutation testing for the two sample mean situation</a></li>
<li><a href="2-5-section2-5.html#section2-5"><span class="toc-section-number">2.5</span> Hypothesis testing (general)</a></li>
<li><a href="2-6-section2-6.html#section2-6"><span class="toc-section-number">2.6</span> Connecting randomization (nonparametric) and parametric tests</a></li>
<li><a href="2-7-section2-7.html#section2-7"><span class="toc-section-number">2.7</span> Second example of permutation tests</a></li>
<li><a href="2-8-section2-8.html#section2-8"><span class="toc-section-number">2.8</span> Confidence intervals and bootstrapping</a></li>
<li><a href="2-9-section2-9.html#section2-9"><span class="toc-section-number">2.9</span> Bootstrap confidence intervals for difference in GPAs</a></li>
<li><a href="2-10-section2-10.html#section2-10"><span class="toc-section-number">2.10</span> Chapter summary</a></li>
<li><a href="2-11-section2-11.html#section2-11"><span class="toc-section-number">2.11</span> Summary of important R code</a></li>
<li><a href="2-12-section2-12.html#section2-12"><span class="toc-section-number">2.12</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="3-chapter3.html#chapter3"><span class="toc-section-number">3</span> One-Way ANOVA</a><ul>
<li><a href="3-1-section3-1.html#section3-1"><span class="toc-section-number">3.1</span> Situation</a></li>
<li><a href="3-2-section3-2.html#section3-2"><span class="toc-section-number">3.2</span> Linear model for One-Way ANOVA (cell-means and reference-coding)</a></li>
<li><a href="3-3-section3-3.html#section3-3"><span class="toc-section-number">3.3</span> One-Way ANOVA Sums of Squares, Mean Squares, and F-test</a></li>
<li><a href="3-4-section3-4.html#section3-4"><span class="toc-section-number">3.4</span> ANOVA model diagnostics including QQ-plots</a></li>
<li><a href="3-5-section3-5.html#section3-5"><span class="toc-section-number">3.5</span> Guinea pig tooth growth One-Way ANOVA example</a></li>
<li><a href="3-6-section3-6.html#section3-6"><span class="toc-section-number">3.6</span> Multiple (pair-wise) comparisons using Tukey’s HSD and the compact letter display</a></li>
<li><a href="3-7-section3-7.html#section3-7"><span class="toc-section-number">3.7</span> Pair-wise comparisons for Prisoner Rating data</a></li>
<li><a href="3-8-section3-8.html#section3-8"><span class="toc-section-number">3.8</span> Chapter summary</a></li>
<li><a href="3-9-section3-9.html#section3-9"><span class="toc-section-number">3.9</span> Summary of important R code</a></li>
<li><a href="3-10-section3-10.html#section3-10"><span class="toc-section-number">3.10</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="4-chapter4.html#chapter4"><span class="toc-section-number">4</span> Two-Way ANOVA</a><ul>
<li><a href="4-1-section4-1.html#section4-1"><span class="toc-section-number">4.1</span> Situation</a></li>
<li><a href="4-2-section4-2.html#section4-2"><span class="toc-section-number">4.2</span> Designing a two-way experiment and visualizing results</a></li>
<li><a href="4-3-section4-3.html#section4-3"><span class="toc-section-number">4.3</span> Two-Way ANOVA models and hypothesis tests</a></li>
<li><a href="4-4-section4-4.html#section4-4"><span class="toc-section-number">4.4</span> Guinea pig tooth growth analysis with Two-Way ANOVA</a></li>
<li><a href="4-5-section4-5.html#section4-5"><span class="toc-section-number">4.5</span> Observational study example: The Psychology of Debt</a></li>
<li><a href="4-6-section4-6.html#section4-6"><span class="toc-section-number">4.6</span> Pushing Two-Way ANOVA to the limit: Un-replicated designs</a></li>
<li><a href="4-7-section4-7.html#section4-7"><span class="toc-section-number">4.7</span> Chapter summary</a></li>
<li><a href="4-8-section4-8.html#section4-8"><span class="toc-section-number">4.8</span> Summary of important R code</a></li>
<li><a href="4-9-section4-9.html#section4-9"><span class="toc-section-number">4.9</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="5-chapter5.html#chapter5"><span class="toc-section-number">5</span> Chi-square tests</a><ul>
<li><a href="5-1-section5-1.html#section5-1"><span class="toc-section-number">5.1</span> Situation, contingency tables, and table plots</a></li>
<li><a href="5-2-section5-2.html#section5-2"><span class="toc-section-number">5.2</span> Homogeneity test hypotheses</a></li>
<li><a href="5-3-section5-3.html#section5-3"><span class="toc-section-number">5.3</span> Independence test hypotheses</a></li>
<li><a href="5-4-section5-4.html#section5-4"><span class="toc-section-number">5.4</span> Models for R by C tables</a></li>
<li><a href="5-5-section5-5.html#section5-5"><span class="toc-section-number">5.5</span> Permutation tests for the <span class="math inline">\(X^2\)</span> statistic</a></li>
<li><a href="5-6-section5-6.html#section5-6"><span class="toc-section-number">5.6</span> Chi-square distribution for the <span class="math inline">\(X^2\)</span> statistic</a></li>
<li><a href="5-7-section5-7.html#section5-7"><span class="toc-section-number">5.7</span> Examining residuals for the source of differences</a></li>
<li><a href="5-8-section5-8.html#section5-8"><span class="toc-section-number">5.8</span> General protocol for <span class="math inline">\(X^2\)</span> tests</a></li>
<li><a href="5-9-section5-9.html#section5-9"><span class="toc-section-number">5.9</span> Political party and voting results: Complete analysis</a></li>
<li><a href="5-10-section5-10.html#section5-10"><span class="toc-section-number">5.10</span> Is cheating and lying related in students?</a></li>
<li><a href="5-11-section5-11.html#section5-11"><span class="toc-section-number">5.11</span> Analyzing a stratified random sample of California schools</a></li>
<li><a href="5-12-section5-12.html#section5-12"><span class="toc-section-number">5.12</span> Chapter summary</a></li>
<li><a href="5-13-section5-13.html#section5-13"><span class="toc-section-number">5.13</span> Summary of important R commands</a></li>
<li><a href="5-14-section5-14.html#section5-14"><span class="toc-section-number">5.14</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="6-chapter6.html#chapter6"><span class="toc-section-number">6</span> Correlation and Simple Linear Regression</a><ul>
<li><a href="6-1-section6-1.html#section6-1"><span class="toc-section-number">6.1</span> Relationships between two quantitative variables</a></li>
<li><a href="6-2-section6-2.html#section6-2"><span class="toc-section-number">6.2</span> Estimating the correlation coefficient</a></li>
<li><a href="6-3-section6-3.html#section6-3"><span class="toc-section-number">6.3</span> Relationships between variables by groups</a></li>
<li><a href="6-4-section6-4.html#section6-4"><span class="toc-section-number">6.4</span> Inference for the correlation coefficient (Optional section)</a></li>
<li><a href="6-5-section6-5.html#section6-5"><span class="toc-section-number">6.5</span> Are tree diameters related to tree heights?</a></li>
<li><a href="6-6-section6-6.html#section6-6"><span class="toc-section-number">6.6</span> Describing relationships with a regression model</a></li>
<li><a href="6-7-section6-7.html#section6-7"><span class="toc-section-number">6.7</span> Least Squares Estimation</a></li>
<li><a href="6-8-section6-8.html#section6-8"><span class="toc-section-number">6.8</span> Measuring the strength of regressions: R<sup>2</sup></a></li>
<li><a href="6-9-section6-9.html#section6-9"><span class="toc-section-number">6.9</span> Outliers: leverage and influence</a></li>
<li><a href="6-10-section6-10.html#section6-10"><span class="toc-section-number">6.10</span> Residual diagnostics – setting the stage for inference</a></li>
<li><a href="6-11-section6-11.html#section6-11"><span class="toc-section-number">6.11</span> Old Faithful discharge and waiting times</a></li>
<li><a href="6-12-section6-12.html#section6-12"><span class="toc-section-number">6.12</span> Chapter summary</a></li>
<li><a href="6-13-section6-13.html#section6-13"><span class="toc-section-number">6.13</span> Summary of important R code</a></li>
<li><a href="6-14-section6-14.html#section6-14"><span class="toc-section-number">6.14</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="7-chapter7.html#chapter7"><span class="toc-section-number">7</span> Simple linear regression inference</a><ul>
<li><a href="7-1-section7-1.html#section7-1"><span class="toc-section-number">7.1</span> Model</a></li>
<li><a href="7-2-section7-2.html#section7-2"><span class="toc-section-number">7.2</span> Confidence interval and hypothesis tests for the slope and intercept</a></li>
<li><a href="7-3-section7-3.html#section7-3"><span class="toc-section-number">7.3</span> Bozeman temperature trend</a></li>
<li><a href="7-4-section7-4.html#section7-4"><span class="toc-section-number">7.4</span> Randomizing inferences for the slope coefficient</a></li>
<li><a href="7-5-section7-5.html#section7-5"><span class="toc-section-number">7.5</span> Transformations part I: Linearizing relationships</a></li>
<li><a href="7-6-section7-6.html#section7-6"><span class="toc-section-number">7.6</span> Transformations part II: Impacts on SLR interpretations: log(y), log(x), &amp; both log(y) &amp; log(x)</a></li>
<li><a href="7-7-section7-7.html#section7-7"><span class="toc-section-number">7.7</span> Confidence interval for the mean and prediction intervals for a new observation</a></li>
<li><a href="7-8-section7-8.html#section7-8"><span class="toc-section-number">7.8</span> Chapter summary</a></li>
<li><a href="7-9-section7-9.html#section7-9"><span class="toc-section-number">7.9</span> Summary of important R code</a></li>
<li><a href="7-10-section7-10.html#section7-10"><span class="toc-section-number">7.10</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="8-chapter8.html#chapter8"><span class="toc-section-number">8</span> Multiple linear regression</a><ul>
<li><a href="8-1-section8-1.html#section8-1"><span class="toc-section-number">8.1</span> Going from SLR to MLR</a></li>
<li><a href="8-2-section8-2.html#section8-2"><span class="toc-section-number">8.2</span> Validity conditions in MLR</a></li>
<li><a href="8-3-section8-3.html#section8-3"><span class="toc-section-number">8.3</span> Interpretation of MLR terms</a></li>
<li><a href="8-4-section8-4.html#section8-4"><span class="toc-section-number">8.4</span> Comparing multiple regression models</a></li>
<li><a href="8-5-section8-5.html#section8-5"><span class="toc-section-number">8.5</span> General recommendations for MLR interpretations and VIFs</a></li>
<li><a href="8-6-section8-6.html#section8-6"><span class="toc-section-number">8.6</span> MLR inference: Parameter inferences using the t-distribution</a></li>
<li><a href="8-7-section8-7.html#section8-7"><span class="toc-section-number">8.7</span> Overall F-test in multiple linear regression</a></li>
<li><a href="8-8-section8-8.html#section8-8"><span class="toc-section-number">8.8</span> Case study: First year college GPA and SATs</a></li>
<li><a href="8-9-section8-9.html#section8-9"><span class="toc-section-number">8.9</span> Different intercepts for different groups: MLR with indicator variables</a></li>
<li><a href="8-10-section8-10.html#section8-10"><span class="toc-section-number">8.10</span> Additive MLR with more than two groups: Headache example</a></li>
<li><a href="8-11-section8-11.html#section8-11"><span class="toc-section-number">8.11</span> Different slopes and different intercepts</a></li>
<li><a href="8-12-section8-12.html#section8-12"><span class="toc-section-number">8.12</span> F-tests for MLR models with quantitative and categorical variables and interactions</a></li>
<li><a href="8-13-section8-13.html#section8-13"><span class="toc-section-number">8.13</span> AICs for model selection</a></li>
<li><a href="8-14-section8-14.html#section8-14"><span class="toc-section-number">8.14</span> Case study: Forced expiratory volume model selection using AICs</a></li>
<li><a href="8-15-section8-15.html#section8-15"><span class="toc-section-number">8.15</span> Chapter summary</a></li>
<li><a href="8-16-section8-16.html#section8-16"><span class="toc-section-number">8.16</span> Summary of important R code</a></li>
<li><a href="8-17-section8-17.html#section8-17"><span class="toc-section-number">8.17</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="9-chapter9.html#chapter9"><span class="toc-section-number">9</span> Case studies</a><ul>
<li><a href="9-1-section9-1.html#section9-1"><span class="toc-section-number">9.1</span> Overview of material covered</a></li>
<li><a href="9-2-section9-2.html#section9-2"><span class="toc-section-number">9.2</span> The impact of simulated chronic nitrogen deposition on the biomass and N2-fixation activity of two boreal feather moss–cyanobacteria associations</a></li>
<li><a href="9-3-section9-3.html#section9-3"><span class="toc-section-number">9.3</span> Ants learn to rely on more informative attributes during decision-making</a></li>
<li><a href="9-4-section9-4.html#section9-4"><span class="toc-section-number">9.4</span> Multi-variate models are essential for understanding vertebrate diversification in deep time</a></li>
<li><a href="9-5-section9-5.html#section9-5"><span class="toc-section-number">9.5</span> General summary</a></li>
</ul></li>
<li><a href="references.html#references">References</a></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="section4-5" class="section level2">
<h2><span class="header-section-number">4.5</span> Observational study example: The Psychology of Debt</h2>
<p>In this section, the analysis of a survey of <span class="math inline">\(N=464\)</span> randomly sampled adults will be analyzed from a survey conducted by <span class="citation">Lea, Webley, and Walker (<a href="#ref-Lea1995">1995</a>)</span> and available in the <code>debt</code> data set from the <code>faraway</code> package <span class="citation">(Faraway <a href="#ref-R-faraway">2016</a>)</span>. The subjects responded to a variety of questions including whether they buy cigarettes (<code>cigbuy</code>: 0 if no, 1 if yes), their housing situation (<code>house</code>: 1 = rent, 2 = mortgage, and 3 = owned outright), their income group (<code>incomegp</code>: 1 = lowest, 5 = highest), and their score on a continuous scale of attitudes about debt (<code>prodebt</code>: 1 = least favorable, 5 = most favorable). The variable <code>prodebt</code> was derived as the average of a series of questions about debt with each question measured on an <strong><em>ordinal</em></strong> 1 to 5 scale, with higher values corresponding to more positive responses about <span class="math inline">\(\underline{\text{going into debt}}\)</span> of various kinds. The ordered scale on surveys that try to elicit your opinions on topics with scales from 1 to 5 or 1 to 7 or even, sometimes, 1 to 10 is called a <strong><em>Likert scale</em></strong> <span class="citation">(Likert <a href="#ref-Likert1932">1932</a>)</span>. It is not a quantitative scale and really should be handled more carefully than taking an average of a set responses. That said, it is extremely common practice in social science research to treat ordinal responses as if they are quantitative and take the average of many of them to create a more continuous response variable like the one we are using here. If you continue your statistics explorations, you will see some better techniques for analyzing responses obtained in this fashion. That said, the scale of the response is relatively easy to understand as an amount of willingness to go into debt on a scale from 1 to 5 with higher values corresponding to more willingness to be in debt.</p>
<p>This data set is typical of survey data where respondents were not required to answer all questions and there are some missing responses. We will clean out any individuals that failed to respond to all questions using the <code>na.omit</code> function, which will return only subjects that responded to every question in the data set. But is this dangerous? Suppose that people did not want to provide their income levels if they were in the lowest or, maybe, highest income groups. Then we would be missing responses systematically and conclusions could be biased because of ignoring these types of subjects. This is another topic for more advanced statistical methods to try to handle but something every researcher should worry about when selected subjects do not respond at all or fail to answer some questions. This ties back into our discussion of who was sampled. We need to think carefully about who was part of the sample but refused to participate and how that might impact our inferences.</p>
<p>Ignoring this potential for bias in the results for the moment, we are first interested in whether buying cigarettes/not and income groups interact in their explanation of the respondent’s mean opinions on being in debt. The interaction plot (Figure <a href="4-5-section4-5.html#fig:Figure4-12">2.57</a>) may suggest an interaction between <code>cigbuy</code> and <code>incomegp</code> from income levels 1 to 3 where the lines cross but it is not as clear as the previous examples. The interaction <span class="math inline">\(F\)</span>-test helps us objectively assess evidence for that interaction. Based on the plot, there do not appear to be differences based on cigarette purchasing but there might be some differences between the income groups. If there is no interaction present, then this suggests that we might be in Scenario 2 or 3 where a single main effect of interest is present.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(faraway)
<span class="kw">data</span>(debt)
<span class="kw">require</span>(tibble)
debt &lt;-<span class="st"> </span><span class="kw">as.tibble</span>(debt)
debt<span class="op">$</span>incomegp &lt;-<span class="st"> </span><span class="kw">factor</span>(debt<span class="op">$</span>incomegp)
debt<span class="op">$</span>cigbuy &lt;-<span class="st"> </span><span class="kw">factor</span>(debt<span class="op">$</span>cigbuy)
debtc &lt;-<span class="st"> </span><span class="kw">na.omit</span>(debt)</code></pre></div>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">intplot</span>(prodebt<span class="op">~</span>cigbuy<span class="op">*</span>incomegp, <span class="dt">data=</span>debtc, <span class="dt">col=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">3</span>), <span class="dt">lwd=</span><span class="dv">2</span>)</code></pre></div>
<div class="figure"><span id="fig:Figure4-12"></span>
<img src="04-twoWayAnova_files/figure-html/Figure4-12-1.png" alt="Interaction plot of prodebt by income group and buy cigarettes (0=no, 1=yes)." width="960" />
<p class="caption">
Figure 2.57: Interaction plot of <code>prodebt</code> by income group and buy cigarettes (0=no, 1=yes).
</p>
</div>
<p>As in other situations, and especially with observational studies where a single large sample is analyzed, it is important to check for balance - whether all the combinations of the two predictor variables are similarly represented. Even more critically, we need to check whether all the combinations of levels of factors are measured. If a combination is not measured, then we lose the ability to estimate the mean for that combination and the ability to test for an interaction. A solution to that problem would be to collapse the categories of one of the variables, changing the definitions of the levels but if you fail to obtain information for all combinations, you can’t work with the interaction model. In this situation, we barely have enough information to proceed (the smallest <span class="math inline">\(n_{jk}\)</span> is 8 for income group 4 that buys cigarettes). We have a very unbalanced design with counts between 8 and 51 in the different combinations.</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tally</span>(cigbuy<span class="op">~</span>incomegp, <span class="dt">data=</span>debtc)</code></pre></div>
<pre><code>##       incomegp
## cigbuy  1  2  3  4  5
##      0 24 40 45 47 51
##      1 23 29 18  8 19</code></pre>
<p>The test for the interaction is always how we start our modeling in Two-Way ANOVA situations. The ANOVA table suggests that there is little evidence of interaction between the income level and buying cigarettes on the opinions of the respondents towards debt (<span class="math inline">\(F(4,294)=1.0003\)</span>, p-value=0.408). This suggests that the initial assessment that the interaction wasn’t too prominent was correct. We should move to the additive model here but first need to check the assumptions to make sure we can trust this initial test.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(car)
debt1 &lt;-<span class="st"> </span><span class="kw">lm</span>(prodebt<span class="op">~</span>incomegp<span class="op">*</span>cigbuy, <span class="dt">data=</span>debtc)
<span class="kw">Anova</span>(debt1)</code></pre></div>
<pre><code>## Anova Table (Type II tests)
## 
## Response: prodebt
##                  Sum Sq  Df F value   Pr(&gt;F)
## incomegp          9.018   4  4.5766 0.001339
## cigbuy            0.703   1  1.4270 0.233222
## incomegp:cigbuy   1.971   4  1.0003 0.407656
## Residuals       144.835 294</code></pre>
<p>The diagnostic plots (Figure <a href="4-5-section4-5.html#fig:Figure4-13">2.58</a>) seem to be pretty well-behaved with no apparent violations of the normality assumption and no clear evidence of a violation of the constant variance assumption. The observations would seem to be independent because there is no indication of structure to the measurements of the survey respondents that might create dependencies. In observational studies, violations of the independence assumption might come from repeated measures of the same person or multiple measurements within the same family/household or samples that are clustered geographically. The random sampling from a population should allow inferences to a larger population except for that issue of removing partially missing responses. We also don’t have much information on the population sampled, so will just leave this vague here but know that there is a population these conclusions apply to since it was random sample. All of this suggests proceeding to fitting and exploring the additive model is reasonable here. No causal inferences are possible because this is an observational study.</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))
<span class="kw">plot</span>(debt1)</code></pre></div>
<div class="figure"><span id="fig:Figure4-13"></span>
<img src="04-twoWayAnova_files/figure-html/Figure4-13-1.png" alt="Diagnostic plot for prodebt by income group and buy cigarettes/not interaction model." width="960" />
<p class="caption">
Figure 2.58: Diagnostic plot for <code>prodebt</code> by income group and buy cigarettes/not interaction model.
</p>
</div>
<ol style="list-style-type: decimal">
<li><p><strong>Hypotheses (Two sets apply when the additive model is the focus!):</strong></p>
<ul>
<li><p><span class="math inline">\(H_0\)</span>: No difference in means for <code>prodebt</code> for income groups in population, given cigarette buying in model</p>
<p><span class="math inline">\(\Leftrightarrow\)</span> All <span class="math inline">\(\tau_j\text{&#39;s} = 0\)</span> in additive model.</p></li>
<li><p><span class="math inline">\(H_A\)</span>: Some difference in means for <code>prodebt</code> for income group in population, given cigarette buying in model</p>
<p><span class="math inline">\(\Leftrightarrow\)</span> Not all <span class="math inline">\(\tau_j\text{&#39;s} = 0\)</span> in additive model.</p></li>
</ul>

<ul>
<li><p><span class="math inline">\(H_0\)</span>: No difference in means for <code>prodebt</code> for cigarette buying/not in population, given income group in model </span></p>
<p><span class="math inline">\(\Leftrightarrow\)</span> All <span class="math inline">\(\gamma_k\text{&#39;s} = 0\)</span> in additive model.</p></li>
<li><p><span class="math inline">\(H_A\)</span>: Some difference in means for <code>prodebt</code> for cigarette buying/not in population, given income group in model</p>
<p><span class="math inline">\(\Leftrightarrow\)</span> Not all <span class="math inline">\(\gamma_k\text{&#39;s} = 0\)</span> in additive model.</p></li>
</ul></li>
<li><p><strong>Validity conditions – discussed above but with new plots for the additive model:</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">debt1r &lt;-<span class="st"> </span><span class="kw">lm</span>(prodebt<span class="op">~</span>incomegp<span class="op">+</span>cigbuy, <span class="dt">data=</span>debtc)
<span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))
<span class="kw">plot</span>(debt1r)</code></pre></div>
<div class="figure"><span id="fig:Figure4-14"></span>
<img src="04-twoWayAnova_files/figure-html/Figure4-14-1.png" alt="Diagnostic plot for ``prodebt`` by income group and buy   cigarettes/not" width="960" />
<p class="caption">
Figure 2.59: Diagnostic plot for <code>prodebt</code> by income group and buy cigarettes/not
</p>
</div>
<ul>
<li><p>Constant Variance:</p>
<ul>
<li>In the Residuals vs Fitted and the Scale-Location plots in Figure <a href="4-5-section4-5.html#fig:Figure4-14">2.59</a>, the differences in variability among groups is minor and nothing suggests a violation. <strong>If you change models, you should always revisit the diagnostic plots to make sure you didn’t create problems that were not present in more complicated models.</strong></li>
</ul></li>
<li><p>Normality of residuals:</p>
<ul>
<li>The QQ-Plot in Figure <a href="4-5-section4-5.html#fig:Figure4-14">2.59</a> does not suggest a problem with this assumption.</li>
</ul></li>
</ul></li>
<li><p><strong>Calculate the test statistic for the two main effect tests.</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">Anova</span>(debt1r)</code></pre></div>
<pre><code>## Anova Table (Type II tests)
## 
## Response: prodebt
##            Sum Sq  Df F value   Pr(&gt;F)
## incomegp    9.018   4  4.5766 0.001335
## cigbuy      0.703   1  1.4270 0.233210
## Residuals 146.806 298</code></pre>
<ul>
<li>The test statistics are <span class="math inline">\(F(4,298)=4.577\)</span> and <span class="math inline">\(F(1,298)=1.427\)</span>.</li>
</ul></li>
<li><p><strong>Find the p-value:</strong></p>
<ul>
<li>The ANOVA <span class="math inline">\(F\)</span>-test p-values are 0.001335 for the income group variable (conditional on cigarette buy) and 0.2232 for the cigarette buy variable (conditional on income group).</li>
</ul></li>
<li><p><strong>Make decisions:</strong></p>
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> of no income group differences (p-value=0.0013) and fail to reject <span class="math inline">\(H_0\)</span> of no cigarette buying differences (p-value=0.2232), each after controlling for the other variable.</li>
</ul></li>
<li><p><strong>Write a conclusion:</strong></p>
<ul>
<li>There was initially no evidence to support retaining the interaction of income group and cigarette buying on pro-debt feelings (<span class="math inline">\(F(4,294)=1.00, \text{p-value} =0.408\)</span>) so the interaction was dropped from the model. There is strong evidence of some difference in the mean pro-debt feelings in the population across the income groups, after adjusting for cigarette buying. There is little to no evidence of a difference in the mean pro-debt feelings in the population based on cigarette buying/not, after adjusting for income group.</li>
</ul></li>
</ol>
<p>So we learned that the additive model was more appropriate for these responses and that the results resemble Scenario 2 or 3 with only one main effect being important. In the additive model, the coefficients can be interpreted as shifts from the baseline after controlling for the other variable in the model. Figure <a href="4-5-section4-5.html#fig:Figure4-15">2.60</a> shows the increasing average comfort with being in debt as the income groups go up. Being a cigarette buyer was related to a lower comfort level with debt. But compare the y-axis scales in the two plots – the differences in the means across income groups are almost 0.5 points on a 5 point scale whereas the difference across <code>cigbuy</code>’s two levels is less than 0.15 units. The error bars for the 95% confidence intervals are of similar width but the differences in means show up clearly in the income group term-plot. This is all indirectly related to the size of the p-values for each term in the additive model but hopefully helps to build some intuition on the reason for differences.</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(<span class="kw">allEffects</span>(debt1r))</code></pre></div>
<div class="figure"><span id="fig:Figure4-15"></span>
<img src="04-twoWayAnova_files/figure-html/Figure4-15-1.png" alt="Term-plots for the prodebt response additive model with left panel for income group and the right panel for buying cigarettes or not (1 for yes)." width="960" />
<p class="caption">
Figure 2.60: Term-plots for the <code>prodebt</code> response additive model with left panel for income group and the right panel for buying cigarettes or not (1 for yes).
</p>
</div>
<p>The estimated coefficients can also be interesting to interpret for the additive model. Here are the model summary coefficients:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(debt1r)<span class="op">$</span>coefficients</code></pre></div>
<pre><code>##                Estimate Std. Error    t value     Pr(&gt;|t|)
## (Intercept)  3.05483517 0.11127284 27.4535561 1.357428e-83
## incomegp2    0.01640636 0.13288796  0.1234601 9.018260e-01
## incomegp3    0.17477182 0.13649309  1.2804444 2.013846e-01
## incomegp4    0.16900515 0.14274836  1.1839376 2.373813e-01
## incomegp5    0.46833117 0.13377661  3.5008449 5.347171e-04
## cigbuy1     -0.10640228 0.08907259 -1.1945569 2.332101e-01</code></pre>
<p>In the model, the baseline group is for non-cigarette buyers (<code>cigbuy=0</code>) and income group 1 with <span class="math inline">\(\hat{\alpha}= 3.055\)</span> points. Regardless of the <code>cigbuy</code> level, the difference between income groups 2 and 1 is estimated to be <span class="math inline">\(\hat{\tau}_2=0.016\)</span>, an increase in the mean score of 0.016 points. Similarly, the difference between income groups 3 and 1 is <span class="math inline">\(\hat{\tau}_3=0.175\)</span> points, regardless of cigarette smoking status. The estimated difference between cigarette buyers and non-buyers was estimated as <span class="math inline">\(\hat{\gamma}_2=-0.106\)</span> points for any income group, remember that this variable had a moderately large p-value in this model. The additive model-based estimates for all six combinations can be found in Table <a href="4-5-section4-5.html#tab:Table4-3">2.8</a>.</p>


<table>
<caption><span id="tab:Table4-3">Table 2.8: </span> Calculations to construct the estimates for all combinations of variables for the <code>prodebt</code> additive model.</caption>
<colgroup>
<col width="14%" />
<col width="13%" />
<col width="17%" />
<col width="17%" />
<col width="17%" />
<col width="17%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"><span class="math inline">\(\color{red}{\text{Cig}}\)</span><br />
<span class="math inline">\(\color{red}{\text{Buy}}\)</span></th>
<th align="left"><span class="math inline">\(\color{blue}{\textbf{Income}}\)</span><br />
<span class="math inline">\(\color{blue}{\textbf{Group 1}}\)</span></th>
<th align="left"><span class="math inline">\(\color{blue}{\textbf{Income}}\)</span><br />
<span class="math inline">\(\color{blue}{\textbf{Group 2}}\)</span></th>
<th align="left"><span class="math inline">\(\color{blue}{\textbf{Income}}\)</span><br />
<span class="math inline">\(\color{blue}{\textbf{Group 3}}\)</span></th>
<th align="left"><span class="math inline">\(\color{blue}{\textbf{Income}}\)</span><br />
<span class="math inline">\(\color{blue}{\textbf{Group 4}}\)</span></th>
<th align="left"><span class="math inline">\(\color{blue}{\textbf{Income}}\)</span><br />
<span class="math inline">\(\color{blue}{\textbf{Group 5}}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(\color{red}{\text{0:No}}\)</span></td>
<td align="left"><span class="math inline">\(\hat{\alpha} ={3.055}\)</span></td>
<td align="left"><span class="math inline">\(\hat{\alpha} + \hat{\tau}_2\)</span><br />
<span class="math inline">\(=3.055 + 0.016\)</span><br />
<span class="math inline">\(= 3.071\)</span></td>
<td align="left"><span class="math inline">\(\hat{\alpha} + \hat{\tau}_3\)</span><br />
<span class="math inline">\(=3.055 + 0.175\)</span><br />
<span class="math inline">\(=3.230\)</span></td>
<td align="left"><span class="math inline">\(\hat{\alpha} + \hat{\tau}_4\)</span><br />
<span class="math inline">\(=3.055 + 0.169\)</span><br />
<span class="math inline">\(=3.224\)</span></td>
<td align="left"><span class="math inline">\(\hat{\alpha} + \hat{\tau}_5\)</span><br />
<span class="math inline">\(=3.055 + 0.468\)</span><br />
<span class="math inline">\(=3.523\)</span><br />
</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(\color{red}{\text{1:}\text{Yes}}\)</span></td>
<td align="left"><span class="math inline">\(\hat{\alpha}+\hat{\gamma}_2\)</span><br />
<span class="math inline">\(=3.055\)</span><br />
<span class="math inline">\(-0.106\)</span><br />
<span class="math inline">\(=2.949\)</span></td>
<td align="left"><span class="math inline">\(\hat{\alpha}+\hat{\tau}_2+\hat{\gamma}_2\)</span><br />
<span class="math inline">\(=3.055+0.016\)</span><br />
<span class="math inline">\(-0.106\)</span><br />
<span class="math inline">\(=2.965\)</span></td>
<td align="left"><span class="math inline">\(\hat{\alpha}+\hat{\tau}_3+\hat{\gamma}_2\)</span><br />
<span class="math inline">\(=3.055+0.175\)</span><br />
<span class="math inline">\(-0.106\)</span><br />
<span class="math inline">\(=3.124\)</span></td>
<td align="left"><span class="math inline">\(\hat{\alpha}+\hat{\tau}_4+\hat{\gamma}_2\)</span><br />
<span class="math inline">\(=3.055+0.169\)</span><br />
<span class="math inline">\(-0.106\)</span><br />
<span class="math inline">\(=3.118\)</span></td>
<td align="left"><span class="math inline">\(\hat{\alpha}+\hat{\tau}_5+\hat{\gamma}_2\)</span><br />
<span class="math inline">\(=3.055+0.468\)</span><br />
<span class="math inline">\(-0.106\)</span><br />
<span class="math inline">\(=3.417\)</span></td>
</tr>
</tbody>
</table>

<p>One final plot of the fitted values from this additive model in Figure <a href="4-5-section4-5.html#fig:Figure4-16">2.61</a> hopefully crystallizes the implications of an additive model and reinforces that this model creates and assumes that the differences across levels of one variable are the same regardless of the level of the other variable and that this creates parallel lines. The difference between <code>cigbuy</code> levels across all income groups is a drop in -0.106 points. The income groups have the same differences regardless of cigarette buying or not, with income group 5 much higher than the other four groups.</p>

<div class="figure"><span id="fig:Figure4-16"></span>
<img src="04-twoWayAnova_files/figure-html/Figure4-16-1.png" alt="Illustration of the results from Table 2.7 showing the combined impacts of the components of the additive model for prodebt. Panel (a) uses income groups on the x-axis and different lines for cigarette buyers (1) or not (0). Panel (b) displays the different income groups as lines with the cigarette buying status on the x-axis." width="576" />
<p class="caption">
Figure 2.61: Illustration of the results from Table <a href="4-3-section4-3.html#tab:Table4-2">2.7</a> showing the combined impacts of the components of the additive model for <code>prodebt</code>. Panel (a) uses income groups on the x-axis and different lines for cigarette buyers (1) or not (0). Panel (b) displays the different income groups as lines with the cigarette buying status on the x-axis.
</p>
</div>
<p><strong>In general, we proceed through the following steps in any 2-WAY ANOVA situation:</strong></p>
<ol style="list-style-type: decimal">
<li><p>Make an interaction plot.</p></li>
<li><p>Fit the interaction model; examine the test for the interaction.</p></li>
<li><p>Check the residual diagnostic plots for the interaction model (especially normality and equal variance).</p>
<ul>
<li>If there is a problem with normality or equal variance, consider a “transformation” of the response as discussed in Chapter <a href="7-chapter7.html#chapter7"><strong>??</strong></a> This can help make the responses have similar variances or responses to be more normal, but sometimes not both.</li>
</ul></li>
<li><p>If the interaction test has a small p-value, that is your main result. Focus on the interaction plot from (1) to fully understand the results, adding Tukey’s HSD results to see which means of the combinations of levels are detected as being different.</p></li>
<li><p>If the interaction is not considered important, then re-fit the model without the interaction (additive model) and re-check the diagnostic plots. If the diagnostics are reasonable to proceed:</p>
<ul>
<li><p>Focus on the results for each explanatory variable, using Type II tests especially if the design is not balanced.</p></li>
<li><p>Report the initial interaction test results and the results for the test for each variable from the model that is re-fit without the interaction.</p></li>
<li><p>Model coefficients are interesting as they are shifts from baseline for each level of each variable, controlling for the other variable – interpret those differences if the number of levels is not too great.</p></li>
</ul></li>
</ol>
<p>Whether you end up favoring an additive or interaction model, all steps of the hypothesis testing protocol should be engaged and a story based on the final results should be compiled, supported by the graphical displays.</p>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-Lea1995">
<p>Lea, Stephen E.G., Paul Webley, and Catherine M. Walker. 1995. “Psychological Factors in Consumer Debt: Money Management, Economic Socialization, and Credit Use.” <em>Journal of Economic Psychology</em> 16 (4): 681–701.</p>
</div>
<div id="ref-R-faraway">
<p>Faraway, Julian. 2016. <em>Faraway: Functions and Datasets for Books by Julian Faraway</em>. <a href="https://CRAN.R-project.org/package=faraway" class="uri">https://CRAN.R-project.org/package=faraway</a>.</p>
</div>
<div id="ref-Likert1932">
<p>Likert, Rensis. 1932. “A Technique for the Measurement of Attitudes.” <em>Archives of Psychology</em> 140: 1–55.</p>
</div>
</div>
<p style="text-align: center;">
<a href="4-4-section4-4.html"><button class="btn btn-default">Previous</button></a>
<a href="4-6-section4-6.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
