<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta property="og:title" content="A Second Semester Statistics Course with R" />
<meta property="og:type" content="book" />



<meta name="github-repo" content="gpeterson406/Greenwood_Book" />

<meta name="author" content="Mark C Greenwood" />


<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="A Second Semester Statistics Course with R">

<title>A Second Semester Statistics Course with R</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="libs/navigation-1.1/tabsets.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<link rel="stylesheet" href="toc.css" type="text/css" />

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
</style>
</head>

<body>

<div class="container-fluid main-container">


<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul>
<li><a href="index.html#cover">Cover</a></li>
<li><a href="acknowledgments.html#acknowledgments">Acknowledgments</a></li>
<li class="has-sub"><a href="1-chapter1.html#chapter1"><span class="toc-section-number">1</span> Preface</a><ul>
<li><a href="1-1-section1-1.html#section1-1"><span class="toc-section-number">1.1</span> Overview of methods</a></li>
<li><a href="1-2-section1-2.html#section1-2"><span class="toc-section-number">1.2</span> Getting started in R</a></li>
<li><a href="1-3-section1-3.html#section1-3"><span class="toc-section-number">1.3</span> Basic summary statistics, histograms, and boxplots using R</a></li>
<li><a href="1-4-section1-4.html#section1-4"><span class="toc-section-number">1.4</span> Chapter summary</a></li>
<li><a href="1-5-section1-5.html#section1-5"><span class="toc-section-number">1.5</span> Summary of important R code</a></li>
<li><a href="1-6-section1-6.html#section1-6"><span class="toc-section-number">1.6</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="2-chapter2.html#chapter2"><span class="toc-section-number">2</span> (R)e-Introduction to statistics</a><ul>
<li><a href="2-1-section2-1.html#section2-1"><span class="toc-section-number">2.1</span> Histograms, boxplots, and density curves</a></li>
<li><a href="2-2-section2-2.html#section2-2"><span class="toc-section-number">2.2</span> Beanplots</a></li>
<li><a href="2-3-section2-3.html#section2-3"><span class="toc-section-number">2.3</span> Models, hypotheses, and permutations for the two sample mean situation</a></li>
<li><a href="2-4-section2-4.html#section2-4"><span class="toc-section-number">2.4</span> Permutation testing for the two sample mean situation</a></li>
<li><a href="2-5-section2-5.html#section2-5"><span class="toc-section-number">2.5</span> Hypothesis testing (general)</a></li>
<li><a href="2-6-section2-6.html#section2-6"><span class="toc-section-number">2.6</span> Connecting randomization (nonparametric) and parametric tests</a></li>
<li><a href="2-7-section2-7.html#section2-7"><span class="toc-section-number">2.7</span> Second example of permutation tests</a></li>
<li><a href="2-8-section2-8.html#section2-8"><span class="toc-section-number">2.8</span> Confidence intervals and bootstrapping</a></li>
<li><a href="2-9-section2-9.html#section2-9"><span class="toc-section-number">2.9</span> Bootstrap confidence intervals for difference in GPAs</a></li>
<li><a href="2-10-section2-10.html#section2-10"><span class="toc-section-number">2.10</span> Chapter summary</a></li>
<li><a href="2-11-section2-11.html#section2-11"><span class="toc-section-number">2.11</span> Summary of important R code</a></li>
<li><a href="2-12-section2-12.html#section2-12"><span class="toc-section-number">2.12</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="3-chapter3.html#chapter3"><span class="toc-section-number">3</span> One-Way ANOVA</a><ul>
<li><a href="3-1-section3-1.html#section3-1"><span class="toc-section-number">3.1</span> Situation</a></li>
<li><a href="3-2-section3-2.html#section3-2"><span class="toc-section-number">3.2</span> Linear model for One-Way ANOVA (cell-means and reference-coding)</a></li>
<li><a href="3-3-section3-3.html#section3-3"><span class="toc-section-number">3.3</span> One-Way ANOVA Sums of Squares, Mean Squares, and F-test</a></li>
<li><a href="3-4-section3-4.html#section3-4"><span class="toc-section-number">3.4</span> ANOVA model diagnostics including QQ-plots</a></li>
<li><a href="3-5-section3-5.html#section3-5"><span class="toc-section-number">3.5</span> Guinea pig tooth growth One-Way ANOVA example</a></li>
<li><a href="3-6-section3-6.html#section3-6"><span class="toc-section-number">3.6</span> Multiple (pair-wise) comparisons using Tukey’s HSD and the compact letter display</a></li>
<li><a href="3-7-section3-7.html#section3-7"><span class="toc-section-number">3.7</span> Pair-wise comparisons for Prisoner Rating data</a></li>
<li><a href="3-8-section3-8.html#section3-8"><span class="toc-section-number">3.8</span> Chapter summary</a></li>
<li><a href="3-9-section3-9.html#section3-9"><span class="toc-section-number">3.9</span> Summary of important R code</a></li>
<li><a href="3-10-section3-10.html#section3-10"><span class="toc-section-number">3.10</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="4-chapter4.html#chapter4"><span class="toc-section-number">4</span> Two-Way ANOVA</a><ul>
<li><a href="4-1-section4-1.html#section4-1"><span class="toc-section-number">4.1</span> Situation</a></li>
<li><a href="4-2-section4-2.html#section4-2"><span class="toc-section-number">4.2</span> Designing a two-way experiment and visualizing results</a></li>
<li><a href="4-3-section4-3.html#section4-3"><span class="toc-section-number">4.3</span> Two-Way ANOVA models and hypothesis tests</a></li>
<li><a href="4-4-section4-4.html#section4-4"><span class="toc-section-number">4.4</span> Guinea pig tooth growth analysis with Two-Way ANOVA</a></li>
<li><a href="4-5-section4-5.html#section4-5"><span class="toc-section-number">4.5</span> Observational study example: The Psychology of Debt</a></li>
<li><a href="4-6-section4-6.html#section4-6"><span class="toc-section-number">4.6</span> Pushing Two-Way ANOVA to the limit: Un-replicated designs</a></li>
<li><a href="4-7-section4-7.html#section4-7"><span class="toc-section-number">4.7</span> Chapter summary</a></li>
<li><a href="4-8-section4-8.html#section4-8"><span class="toc-section-number">4.8</span> Summary of important R code</a></li>
<li><a href="4-9-section4-9.html#section4-9"><span class="toc-section-number">4.9</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="5-chapter5.html#chapter5"><span class="toc-section-number">5</span> Chi-square tests</a><ul>
<li><a href="5-1-section5-1.html#section5-1"><span class="toc-section-number">5.1</span> Situation, contingency tables, and table plots</a></li>
<li><a href="5-2-section5-2.html#section5-2"><span class="toc-section-number">5.2</span> Homogeneity test hypotheses</a></li>
<li><a href="5-3-section5-3.html#section5-3"><span class="toc-section-number">5.3</span> Independence test hypotheses</a></li>
<li><a href="5-4-section5-4.html#section5-4"><span class="toc-section-number">5.4</span> Models for R by C tables</a></li>
<li><a href="5-5-section5-5.html#section5-5"><span class="toc-section-number">5.5</span> Permutation tests for the <span class="math inline">\(X^2\)</span> statistic</a></li>
<li><a href="5-6-section5-6.html#section5-6"><span class="toc-section-number">5.6</span> Chi-square distribution for the <span class="math inline">\(X^2\)</span> statistic</a></li>
<li><a href="5-7-section5-7.html#section5-7"><span class="toc-section-number">5.7</span> Examining residuals for the source of differences</a></li>
<li><a href="5-8-section5-8.html#section5-8"><span class="toc-section-number">5.8</span> General protocol for <span class="math inline">\(X^2\)</span> tests</a></li>
<li><a href="5-9-section5-9.html#section5-9"><span class="toc-section-number">5.9</span> Political party and voting results: Complete analysis</a></li>
<li><a href="5-10-section5-10.html#section5-10"><span class="toc-section-number">5.10</span> Is cheating and lying related in students?</a></li>
<li><a href="5-11-section5-11.html#section5-11"><span class="toc-section-number">5.11</span> Analyzing a stratified random sample of California schools</a></li>
<li><a href="5-12-section5-12.html#section5-12"><span class="toc-section-number">5.12</span> Chapter summary</a></li>
<li><a href="5-13-section5-13.html#section5-13"><span class="toc-section-number">5.13</span> Summary of important R commands</a></li>
<li><a href="5-14-section5-14.html#section5-14"><span class="toc-section-number">5.14</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="6-chapter6.html#chapter6"><span class="toc-section-number">6</span> Correlation and Simple Linear Regression</a><ul>
<li><a href="6-1-section6-1.html#section6-1"><span class="toc-section-number">6.1</span> Relationships between two quantitative variables</a></li>
<li><a href="6-2-section6-2.html#section6-2"><span class="toc-section-number">6.2</span> Estimating the correlation coefficient</a></li>
<li><a href="6-3-section6-3.html#section6-3"><span class="toc-section-number">6.3</span> Relationships between variables by groups</a></li>
<li><a href="6-4-section6-4.html#section6-4"><span class="toc-section-number">6.4</span> Inference for the correlation coefficient (Optional section)</a></li>
<li><a href="6-5-section6-5.html#section6-5"><span class="toc-section-number">6.5</span> Are tree diameters related to tree heights?</a></li>
<li><a href="6-6-section6-6.html#section6-6"><span class="toc-section-number">6.6</span> Describing relationships with a regression model</a></li>
<li><a href="6-7-section6-7.html#section6-7"><span class="toc-section-number">6.7</span> Least Squares Estimation</a></li>
<li><a href="6-8-section6-8.html#section6-8"><span class="toc-section-number">6.8</span> Measuring the strength of regressions: R<sup>2</sup></a></li>
<li><a href="6-9-section6-9.html#section6-9"><span class="toc-section-number">6.9</span> Outliers: leverage and influence</a></li>
<li><a href="6-10-section6-10.html#section6-10"><span class="toc-section-number">6.10</span> Residual diagnostics – setting the stage for inference</a></li>
<li><a href="6-11-section6-11.html#section6-11"><span class="toc-section-number">6.11</span> Old Faithful discharge and waiting times</a></li>
<li><a href="6-12-section6-12.html#section6-12"><span class="toc-section-number">6.12</span> Chapter summary</a></li>
<li><a href="6-13-section6-13.html#section6-13"><span class="toc-section-number">6.13</span> Summary of important R code</a></li>
<li><a href="6-14-section6-14.html#section6-14"><span class="toc-section-number">6.14</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="7-chapter7.html#chapter7"><span class="toc-section-number">7</span> Simple linear regression inference</a><ul>
<li><a href="7-1-section7-1.html#section7-1"><span class="toc-section-number">7.1</span> Model</a></li>
<li><a href="7-2-section7-2.html#section7-2"><span class="toc-section-number">7.2</span> Confidence interval and hypothesis tests for the slope and intercept</a></li>
<li><a href="7-3-section7-3.html#section7-3"><span class="toc-section-number">7.3</span> Bozeman temperature trend</a></li>
<li><a href="7-4-section7-4.html#section7-4"><span class="toc-section-number">7.4</span> Randomizing inferences for the slope coefficient</a></li>
<li><a href="7-5-section7-5.html#section7-5"><span class="toc-section-number">7.5</span> Transformations part I: Linearizing relationships</a></li>
<li><a href="7-6-section7-6.html#section7-6"><span class="toc-section-number">7.6</span> Transformations part II: Impacts on SLR interpretations: log(y), log(x), &amp; both log(y) &amp; log(x)</a></li>
<li><a href="7-7-section7-7.html#section7-7"><span class="toc-section-number">7.7</span> Confidence interval for the mean and prediction intervals for a new observation</a></li>
<li><a href="7-8-section7-8.html#section7-8"><span class="toc-section-number">7.8</span> Chapter summary</a></li>
<li><a href="7-9-section7-9.html#section7-9"><span class="toc-section-number">7.9</span> Summary of important R code</a></li>
<li><a href="7-10-section7-10.html#section7-10"><span class="toc-section-number">7.10</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="8-chapter8.html#chapter8"><span class="toc-section-number">8</span> Multiple linear regression</a><ul>
<li><a href="8-1-section8-1.html#section8-1"><span class="toc-section-number">8.1</span> Going from SLR to MLR</a></li>
<li><a href="8-2-section8-2.html#section8-2"><span class="toc-section-number">8.2</span> Validity conditions in MLR</a></li>
<li><a href="8-3-section8-3.html#section8-3"><span class="toc-section-number">8.3</span> Interpretation of MLR terms</a></li>
<li><a href="8-4-section8-4.html#section8-4"><span class="toc-section-number">8.4</span> Comparing multiple regression models</a></li>
<li><a href="8-5-section8-5.html#section8-5"><span class="toc-section-number">8.5</span> General recommendations for MLR interpretations and VIFs</a></li>
<li><a href="8-6-section8-6.html#section8-6"><span class="toc-section-number">8.6</span> MLR inference: Parameter inferences using the t-distribution</a></li>
<li><a href="8-7-section8-7.html#section8-7"><span class="toc-section-number">8.7</span> Overall F-test in multiple linear regression</a></li>
<li><a href="8-8-section8-8.html#section8-8"><span class="toc-section-number">8.8</span> Case study: First year college GPA and SATs</a></li>
<li><a href="8-9-section8-9.html#section8-9"><span class="toc-section-number">8.9</span> Different intercepts for different groups: MLR with indicator variables</a></li>
<li><a href="8-10-section8-10.html#section8-10"><span class="toc-section-number">8.10</span> Additive MLR with more than two groups: Headache example</a></li>
<li><a href="8-11-section8-11.html#section8-11"><span class="toc-section-number">8.11</span> Different slopes and different intercepts</a></li>
<li><a href="8-12-section8-12.html#section8-12"><span class="toc-section-number">8.12</span> F-tests for MLR models with quantitative and categorical variables and interactions</a></li>
<li><a href="8-13-section8-13.html#section8-13"><span class="toc-section-number">8.13</span> AICs for model selection</a></li>
<li><a href="8-14-section8-14.html#section8-14"><span class="toc-section-number">8.14</span> Case study: Forced expiratory volume model selection using AICs</a></li>
<li><a href="8-15-section8-15.html#section8-15"><span class="toc-section-number">8.15</span> Chapter summary</a></li>
<li><a href="8-16-section8-16.html#section8-16"><span class="toc-section-number">8.16</span> Summary of important R code</a></li>
<li><a href="8-17-section8-17.html#section8-17"><span class="toc-section-number">8.17</span> Practice problems</a></li>
</ul></li>
<li class="has-sub"><a href="9-chapter9.html#chapter9"><span class="toc-section-number">9</span> Case studies</a><ul>
<li><a href="9-1-section9-1.html#section9-1"><span class="toc-section-number">9.1</span> Overview of material covered</a></li>
<li><a href="9-2-section9-2.html#section9-2"><span class="toc-section-number">9.2</span> The impact of simulated chronic nitrogen deposition on the biomass and N2-fixation activity of two boreal feather moss–cyanobacteria associations</a></li>
<li><a href="9-3-section9-3.html#section9-3"><span class="toc-section-number">9.3</span> Ants learn to rely on more informative attributes during decision-making</a></li>
<li><a href="9-4-section9-4.html#section9-4"><span class="toc-section-number">9.4</span> Multi-variate models are essential for understanding vertebrate diversification in deep time</a></li>
<li><a href="9-5-section9-5.html#section9-5"><span class="toc-section-number">9.5</span> General summary</a></li>
</ul></li>
<li><a href="references.html#references">References</a></li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<div id="section7-5" class="section level2">
<h2><span class="header-section-number">7.5</span> Transformations part I: Linearizing relationships</h2>
<p>When the influential point, linearity, constant variance and/or normality assumptions are violated, we cannot trust any of the inferences generated by the regression model. The violations occur on gradients from minor to really major problems. As we have seen from the examples in the last two chapters, it has been hard to find data sets that were free of all issues. Furthermore, it may seem hopeless to be able to make successful inferences in some of these situations with the previous tools. There are three potential solutions to violations of the validity conditions:</p>
<ol style="list-style-type: decimal">
<li><p>Consider removing an offending point or two and see if this improves the results, presenting results both with and without those points to describe their impact<a href="#fn86" class="footnoteRef" id="fnref86"><sup>86</sup></a>,</p></li>
<li><p>Try to transform the response, explanatory, or both variables and see if you can force the data set to meet our SLR assumptions after transformation (the focus of this and the next section), or</p></li>
<li><p>Consider more advanced statistical models that can account for these issues (the focus of subsequent statistics courses).</p></li>
</ol>
<p>Transformations</em></strong> involve applying a function to one or both variables. After applying this transformation, one hopes to have alleviated whatever issues encouraged its consideration. <strong><em>Linear transformation functions</em></strong>, of the form <span class="math inline">\(z_{\text{new}}=a*x+b\)</span>, will never help us to fix assumptions in regression situations; linear transformations change the scaling of the variables but not their shape or the relationship between two variables. For example, in the Bozeman Temperature data example, we subtracted 1901 from the <code>Year</code> variable to have <code>Year2</code> start at 0 and go up to 113. We could also apply a linear transformation to change Temperature from being measured in <span class="math inline">\(^\circ F\)</span> to <span class="math inline">\(^\circ C\)</span> using <span class="math inline">\(^\circ C=[^\circ F - 32] *(5/9)\)</span>. The scatterplots on both the original and transformed scales are provided in Figure <a href="7-5-section7-5.html#fig:Figure7-10">2.124</a>. All the coefficients in the regression model and the labels on the axes change, but the “picture” is still the same. Additionally, all the inferences remain the same – and p-values are unchanged by linear transformations. So linear transformations can be “fun” but really are only useful if they make the coefficients easier to interpret. Here if you like changes in <span class="math inline">\(^\circ C\)</span> for a 1 year increase, the slope coefficient is 0.029 and if you like the original change in <span class="math inline">\(^\circ F\)</span> for a 1 year increase, the slope coefficient is 0.052.</p>

<div class="figure"><span id="fig:Figure7-10"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-10-1.png" alt="Scatterplots of Temperature (\(^\circ F\)) versus Year (left) and Temperature (\(^\circ C\)) vs Years since 1901 (right)." width="960" />
<p class="caption">
Figure 2.124: Scatterplots of <em>Temperature</em> (<span class="math inline">\(^\circ F\)</span>) versus <em>Year</em> (left) and <em>Temperature</em> (<span class="math inline">\(^\circ C\)</span>) vs <em>Years</em> since 1901 (right).
</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">bozemantemps<span class="op">$</span>meanmaxC &lt;-<span class="st"> </span>(bozemantemps<span class="op">$</span>meanmax <span class="op">-</span><span class="st"> </span><span class="dv">32</span>)<span class="op">*</span>(<span class="dv">5</span><span class="op">/</span><span class="dv">9</span>)
temp3 &lt;-<span class="st"> </span><span class="kw">lm</span>(meanmaxC<span class="op">~</span>Year2, <span class="dt">data=</span>bozemantemps)
<span class="kw">summary</span>(temp1)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = meanmax ~ Year, data = bozemantemps)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.3779 -0.9300  0.1078  1.1960  5.8698 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -47.35123    9.32184   -5.08 1.61e-06
## Year          0.05244    0.00476   11.02  &lt; 2e-16
## 
## Residual standard error: 1.624 on 107 degrees of freedom
## Multiple R-squared:  0.5315, Adjusted R-squared:  0.5271 
## F-statistic: 121.4 on 1 and 107 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(temp3)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = meanmaxC ~ Year2, data = bozemantemps)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.8766 -0.5167  0.0599  0.6644  3.2610 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 11.300703   0.174349   64.82   &lt;2e-16
## Year2        0.029135   0.002644   11.02   &lt;2e-16
## 
## Residual standard error: 0.9022 on 107 degrees of freedom
## Multiple R-squared:  0.5315, Adjusted R-squared:  0.5271 
## F-statistic: 121.4 on 1 and 107 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Nonlinear transformation functions</em></strong> are where we apply something more complicated than this shift and scaling, something like <span class="math inline">\(y_{\text{new}}=f(y)\)</span>, where <span class="math inline">\(f(\cdot)\)</span> could be a log or power of the original variable <span class="math inline">\(y\)</span>. When we apply these sorts of transformations, interesting things can happen to our linear models and their problems. Some examples of transformations that are at least occasionally used for transforming the response variable are provided in Table <a href="7-5-section7-5.html#tab:Table7-1">2.13</a>, ranging from taking <span class="math inline">\(y\)</span> to different powers from <span class="math inline">\(y^{-2}\)</span> to <span class="math inline">\(y^2\)</span>. Typical transformations used in statistical modeling exist along a gradient of powers of the response variable, defined as <span class="math inline">\(y^{\lambda}\)</span> with <span class="math inline">\(\boldsymbol{\lambda}\)</span> being the power of the transformation of the response variable and <span class="math inline">\(\lambda = 0\)</span> implying a log-transformation. Except for <span class="math inline">\(\lambda = 1\)</span>, the transformations are all nonlinear functions of <span class="math inline">\(y\)</span>.</p>


<table>
<caption><span id="tab:Table7-1">Table 2.13: </span> Ladder of powers of transformations that are often used in statistical modeling.</caption>
<colgroup>
<col width="13%" />
<col width="34%" />
<col width="52%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"><strong>Power</strong></th>
<th align="left"><strong>Formula</strong></th>
<th align="left"><strong>Usage</strong>      </th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">2</td>
<td align="left"><span class="math inline">\(y^2\)</span></td>
<td align="left">seldom used</td>
</tr>
<tr class="even">
<td align="left">1</td>
<td align="left"><span class="math inline">\(y^1=y\)</span></td>
<td align="left">no change</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(1/2\)</span></td>
<td align="left"><span class="math inline">\(y^{0.5}=\sqrt{y}\)</span></td>
<td align="left">counts and area responses</td>
</tr>
<tr class="even">
<td align="left">0</td>
<td align="left"><span class="math inline">\(\log(y)\)</span> natural log of <span class="math inline">\(y\)</span></td>
<td align="left">counts, normality, curves, non-constant variance</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(-1/2\)</span></td>
<td align="left"><span class="math inline">\(y^{-0.5}=1/\sqrt{y}\)</span></td>
<td align="left">uncommon</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(-1\)</span></td>
<td align="left"><span class="math inline">\(y^{-1}=1/y\)</span></td>
<td align="left">for ratios</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(-2\)</span></td>
<td align="left"><span class="math inline">\(y^{-2}=1/y^2\)</span></td>
<td align="left">seldom used</td>
</tr>
</tbody>
</table>
<p>There are even more transformations possible, for example <span class="math inline">\(y^{0.33}\)</span> is sometimes useful for variables involved in measuring the volume of something. And we can also consider applying any of these transformations to the explanatory variable, and consider using them on both the response and explanatory variables at the same time. The most common application of these ideas is to transform the response variable using the log-transformation, at least as a starting point. In fact, the log-transformation is so commonly used (and misused), that we will just focus on its use. It is so commonplace in some fields that some researchers log-transform their data prior to even plotting their data. In other situations, such as when measuring acidity (pH), noise (decibels), or earthquake size (Richter scale), the measurements are already on logarithmic scales.</p>
<p>Actually, we have already analyzed data that benefited from a <strong><em>log-transformation</em></strong> – the <em>log-area burned</em> vs. <em>summer temperature</em> data for Montana. Figure <a href="7-5-section7-5.html#fig:Figure7-11">2.125</a> compares the relationship between these variables on the original hectares scale and the log-hectares scale.</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))
<span class="kw">plot</span>(hectares<span class="op">~</span>Temperature, <span class="dt">data=</span>mtfires, <span class="dt">main=</span><span class="st">&quot;(a)&quot;</span>,
     <span class="dt">ylab=</span><span class="st">&quot;Hectares&quot;</span>, <span class="dt">pch=</span><span class="dv">16</span>)
<span class="kw">plot</span>(loghectares<span class="op">~</span>Temperature, <span class="dt">data=</span>mtfires, <span class="dt">main=</span><span class="st">&quot;(b)&quot;</span>,
     <span class="dt">ylab=</span><span class="st">&quot;log-Hectares&quot;</span>, <span class="dt">pch=</span><span class="dv">16</span>)</code></pre></div>
<div class="figure"><span id="fig:Figure7-11"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-11-1.png" alt="Scatterplots of Hectares (a) and log-Hectares (b) vs Temperature." width="960" />
<p class="caption">
Figure 2.125: Scatterplots of Hectares (a) and log-Hectares (b) vs Temperature.
</p>
</div>
<p>Figure <a href="7-5-section7-5.html#fig:Figure7-11">2.125</a>(a) displays a relationship that would be hard fit using SLR – it has a curve and the variance is increasing with increasing temperatures. With a log-transformation of <em>Hectares</em>, the relationship appears to be relatively linear and have constant variance (in (b)). We considered regression models for this situation previously. This shows at least one situation where a log-transformation of a response variable can linearize a relationship and reduce non-constant variance.</p>
<p>This transformation does not always work to “fix” curvilinear relationships, in fact in some situations it can make the relationship more nonlinear. For example, reconsider the relationship between tree diameter and tree height, which contained some curvature that we could not account for in an SLR. Figure <a href="7-5-section7-5.html#fig:Figure7-12">2.126</a> shows the original version of the variables and Figure <a href="7-5-section7-5.html#fig:Figure7-13">2.127</a> shows the same information with the response variable (height) log-transformed.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(spuRs) <span class="co"># install.packages(&quot;spuRs&quot;)</span>
<span class="kw">data</span>(ufc)
ufc &lt;-<span class="st"> </span><span class="kw">as.tibble</span>(ufc)
<span class="kw">require</span>(car)
<span class="kw">scatterplot</span>(height.m<span class="op">~</span>dbh.cm, <span class="dt">data=</span>ufc[<span class="op">-</span><span class="dv">168</span>,], <span class="dt">smooth=</span>T, <span class="dt">spread=</span>F,
            <span class="dt">main=</span><span class="st">&quot;Tree height vs tree diameter&quot;</span>)
<span class="kw">scatterplot</span>(<span class="kw">log</span>(height.m)<span class="op">~</span>dbh.cm, <span class="dt">data=</span>ufc[<span class="op">-</span><span class="dv">168</span>,], <span class="dt">smooth=</span>T, <span class="dt">spread=</span>F,
            <span class="dt">main=</span><span class="st">&quot;log-Tree height vs tree diameter&quot;</span>)</code></pre></div>

<div class="figure"><span id="fig:Figure7-12"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-12-1.png" alt="Scatterplot of tree height versus tree diameter." width="576" />
<p class="caption">
Figure 2.126: Scatterplot of tree height versus tree diameter.
</p>
</div>
<p>Figure <a href="7-5-section7-5.html#fig:Figure7-13">2.127</a> with the log-transformed response seems to show a more nonlinear relationship and may even have more issues with non-constant variance. This example shows that log-transforming the response variable cannot fix all problems, even though I’ve seen some researchers assume it can. It is OK to try a transformation but remember to always plot the results to make sure it actually helped and did not make the situation worse.</p>

<div class="figure"><span id="fig:Figure7-13"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-13-1.png" alt="Scatterplot of log(tree height) versus tree diameter." width="576" />
<p class="caption">
Figure 2.127: Scatterplot of log(tree height) versus tree diameter.
</p>
</div>
<p>All is not lost in this situation, we can consider two other potential uses of the log-transformation and see if they can “fix” the relationship up a bit. One option is to apply the transformation to the explanatory variable (<code>y~log(x)</code>), displayed in Figure <a href="7-5-section7-5.html#fig:Figure7-14">2.128</a>. If the distribution of the explanatory variable is right skewed (see the boxplot on the x-axis), then consider log-transforming the explanatory variable. This will often reduce the leverage of those most extreme observations which can be useful. In this situation, it also seems to have been quite successful at linearizing the relationship, leaving some minor non-constant variance, but providing a big improvement from the relationship on the original scale.</p>

<div class="figure"><span id="fig:Figure7-14"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-14-1.png" alt="Scatterplot of tree height versus log(tree diameter)." width="576" />
<p class="caption">
Figure 2.128: Scatterplot of tree height versus log(tree diameter).
</p>
</div>
<p>The other option, especially when everything else fails, is to apply the log-transformation to both the explanatory and response variables (<code>log(y)~log(x)</code>), as displayed in Figure <a href="7-5-section7-5.html#fig:Figure7-15">2.129</a>. For this example, the transformation seems to be better than the first two options (none and only <span class="math inline">\(\log(y)\)</span>), but demonstrates some decreasing variability with larger <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> values. It has also created a new and different curve in the relationship. In the end, we might prefer to fit an SLR model to the tree <em>height</em> vs <em>log(diameter)</em> versions of the variables (Figure <a href="7-5-section7-5.html#fig:Figure7-14">2.128</a>).</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">scatterplot</span>(<span class="kw">log</span>(height.m)<span class="op">~</span><span class="kw">log</span>(dbh.cm), <span class="dt">data=</span>ufc[<span class="op">-</span><span class="dv">168</span>,], <span class="dt">smooth=</span>T,
            <span class="dt">spread=</span>F, <span class="dt">main=</span><span class="st">&quot;log-Tree height vs log-tree diameter&quot;</span>)</code></pre></div>
<div class="figure"><span id="fig:Figure7-15"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-15-1.png" alt="Scatterplot of log(tree height) versus log(tree diameter)." width="576" />
<p class="caption">
Figure 2.129: Scatterplot of log(tree height) versus log(tree diameter).
</p>
</div>
<p>Economists also like to use <span class="math inline">\(\log(y)\sim \log(x)\)</span> transformations. The log-log transformation tends to linearize certain relationships and has specific interpretations in terms of Economics theory. The log-log transformation shows up in many different disciplines as a way of obtaining a linear relationship on the log-log scale, but different fields discuss it differently. The following example shows a situation where transformations of both <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> are required and this double transformation seems to be quite successful in what looks like an initially hopeless situation for our linear modeling approach.</p>
<p>Data were collected in 1988 on the rates of infant mortality (infant deaths per 1,000 live births) and gross domestic product (GDP) per capita (in 1998 US dollars) from <span class="math inline">\(n=207\)</span> countries. These data are available from the <code>car</code> package (<span class="citation">Fox and Weisberg (<a href="#ref-R-car">2017</a>)</span>, <span class="citation">Fox (<a href="#ref-Fox2003">2003</a>)</span>) in a data set called <code>UN</code>. The four panels in Figure <a href="7-5-section7-5.html#fig:Figure7-16">2.130</a> show the original relationship and the impacts of log-transforming one or both variables. The only scatterplot that could potentially be modeled using SLR is the lower right panel (d) that shows the relationship between <em>log(infant mortality)</em> and <em>log(GDP)</em>. In the next section, we will fit models to some of these relationships and use our diagnostic plots to help us assess “success” of the transformations.</p>

<div class="figure"><span id="fig:Figure7-16"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-16-1.png" alt="Scatterplots of Infant Mortality vs GDP under four different combinations of log-transformations." width="960" />
<p class="caption">
Figure 2.130: Scatterplots of Infant Mortality vs GDP under four different combinations of log-transformations.
</p>
</div>
<p>Almost all nonlinear transformations assume that the variables are strictly greater than 0. For example, consider what happens when we apply the <code>log</code> function to 0 or a negative value in R:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">log</span>(<span class="op">-</span><span class="dv">1</span>)</code></pre></div>
<pre><code>## [1] NaN</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">log</span>(<span class="dv">0</span>)</code></pre></div>
<pre><code>## [1] -Inf</code></pre>
<p>So be careful to think about the domain of the transformation function before using transformations. For example, when using the log-transformation make sure that the data values are non-zero and positive or you will get some surprises when you go to fit your regression model to a data set with NaNs (not a number) and/or <span class="math inline">\(-\infty\text{&#39;s}\)</span> in it.</p>
<p>Sometimes the log-transformations will not be entirely successful. If the relationship is <strong><em>monotonic</em></strong> (strictly positive or strictly negative but not both), then possibly another stop on the ladder of transformations in Table <a href="7-5-section7-5.html#tab:Table7-1">2.13</a> might work. If the relationship is not monotonic, then it may be better to consider a more complex regression model that can accommodate the shape in the relationship or to split the data set in two so you can use SLR on each part.</p>
<p>Finally, remember that <code>log</code> in statistics and especially in R means the <strong><em>natural log</em></strong> (<em>ln</em> or log base <em>e</em> as you might see it elsewhere). In these situations, applying <code>log10</code> function (which provides log base 10) to the variables would lead to very similar results, but readers may assume you used <span class="math inline">\(\ln\)</span> if you don’t state that you used <span class="math inline">\(log_{10}\)</span>. The main thing to remember to do is to be clear when communicating the version you are using. As an example, I was working with researchers on a study <span class="citation">(Dieser, Greenwood, and Foreman <a href="#ref-Dieser2010">2010</a>)</span> related to impacts of environmental stresses on bacterial survival. The response variable was log-transformed counts and involved smoothed regression lines fit on this scale. I was using natural logs to fit the models and then shared the fitted values from the models and my collaborators back-transformed the results assuming that I had used <span class="math inline">\(log_{10}\)</span>. We quickly resolved our differences once we discovered them but this serves as a reminder at how important communication is in group projects – we both said we were working with log-transformations and didn’t know that we defaulted to different bases.</p>
<table>
<tbody>
<tr class="odd">
<td align="left">Generally, in statistics, it’s safe to assume</td>
</tr>
<tr class="even">
<td align="left">that everything is log base <em>e</em> unless otherwise specified.</td>
</tr>
</tbody>
</table>

</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-R-car">
<p>Fox, John, and Sanford Weisberg. 2017. <em>Car: Companion to Applied Regression</em>. <a href="https://CRAN.R-project.org/package=car" class="uri">https://CRAN.R-project.org/package=car</a>.</p>
</div>
<div id="ref-Fox2003">
<p>Fox, John. 2003. “Effect Displays in R for Generalised Linear Models.” <em>Journal of Statistical Software</em> 8 (15): 1–27. <a href="http://www.jstatsoft.org/v08/i15/" class="uri">http://www.jstatsoft.org/v08/i15/</a>.</p>
</div>
<div id="ref-Dieser2010">
<p>Dieser, Markus, Mark C. Greenwood, and Christine M. Foreman. 2010. “Carotenoid Pigmentation in Antarctic Heterotrophic Bacteria as a Strategy to Withstand Environmental Stresses.” <em>Arctic, Antarctic, and Alpine Research</em> 42(4): 396–405. doi:<a href="https://doi.org/10.1657/1938-4246-42.4.396">10.1657/1938-4246-42.4.396</a>.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="86">
<li id="fn86"><p>If the removal is of a point that is extreme in x-values, then it is appropriate to note that the results only apply to the restricted range of x-values that were actually analyzed. Our results only ever apply to the range of x-values we had available so this is a relatively minor change.<a href="7-5-section7-5.html#fnref86">↩</a></p></li>
</ol>
</div>
<p style="text-align: center;">
<a href="7-4-section7-4.html"><button class="btn btn-default">Previous</button></a>
<a href="7-6-section7-6.html"><button class="btn btn-default">Next</button></a>
</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

</body>
</html>
