<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>A Second Semester Statistics Course with R</title>
  <meta name="description" content="A Second Semester Statistics Course with R">
  <meta name="generator" content="bookdown 0.4 and GitBook 2.6.7">

  <meta property="og:title" content="A Second Semester Statistics Course with R" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="gpeterson406/Greenwood_Book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="A Second Semester Statistics Course with R" />
  
  
  

<meta name="author" content="Mark C Greenwood">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="chapter6.html">
<link rel="next" href="chapter8.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Cover</a></li>
<li class="chapter" data-level="" data-path="acknowledgments.html"><a href="acknowledgments.html"><i class="fa fa-check"></i>Acknowledgments</a></li>
<li class="chapter" data-level="1" data-path="chapter1.html"><a href="chapter1.html"><i class="fa fa-check"></i><b>1</b> Preface</a><ul>
<li class="chapter" data-level="1.1" data-path="chapter1.html"><a href="chapter1.html#section1-1"><i class="fa fa-check"></i><b>1.1</b> Overview of methods</a></li>
<li class="chapter" data-level="1.2" data-path="chapter1.html"><a href="chapter1.html#section1-2"><i class="fa fa-check"></i><b>1.2</b> Getting started in R</a></li>
<li class="chapter" data-level="1.3" data-path="chapter1.html"><a href="chapter1.html#section1-3"><i class="fa fa-check"></i><b>1.3</b> Basic summary statistics, histograms, and boxplots using R</a></li>
<li class="chapter" data-level="1.4" data-path="chapter1.html"><a href="chapter1.html#section1-4"><i class="fa fa-check"></i><b>1.4</b> Chapter summary</a></li>
<li class="chapter" data-level="1.5" data-path="chapter1.html"><a href="chapter1.html#section1-5"><i class="fa fa-check"></i><b>1.5</b> Summary of important R code</a></li>
<li class="chapter" data-level="1.6" data-path="chapter1.html"><a href="chapter1.html#section1-6"><i class="fa fa-check"></i><b>1.6</b> Practice problems</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chapter2.html"><a href="chapter2.html"><i class="fa fa-check"></i><b>2</b> (R)e-Introduction to statistics</a><ul>
<li class="chapter" data-level="2.1" data-path="chapter2.html"><a href="chapter2.html#section2-1"><i class="fa fa-check"></i><b>2.1</b> Histograms, boxplots, and density curves</a></li>
<li class="chapter" data-level="2.2" data-path="chapter2.html"><a href="chapter2.html#section2-2"><i class="fa fa-check"></i><b>2.2</b> Beanplots</a></li>
<li class="chapter" data-level="2.3" data-path="chapter2.html"><a href="chapter2.html#section2-3"><i class="fa fa-check"></i><b>2.3</b> Models, hypotheses, and permutations for the two sample mean situation</a></li>
<li class="chapter" data-level="2.4" data-path="chapter2.html"><a href="chapter2.html#section2-4"><i class="fa fa-check"></i><b>2.4</b> Permutation testing for the two sample mean situation</a></li>
<li class="chapter" data-level="2.5" data-path="chapter2.html"><a href="chapter2.html#section2-5"><i class="fa fa-check"></i><b>2.5</b> Hypothesis testing (general)</a></li>
<li class="chapter" data-level="2.6" data-path="chapter2.html"><a href="chapter2.html#section2-6"><i class="fa fa-check"></i><b>2.6</b> Connecting randomization (nonparametric) and parametric tests</a></li>
<li class="chapter" data-level="2.7" data-path="chapter2.html"><a href="chapter2.html#section2-7"><i class="fa fa-check"></i><b>2.7</b> Second example of permutation tests</a></li>
<li class="chapter" data-level="2.8" data-path="chapter2.html"><a href="chapter2.html#section2-8"><i class="fa fa-check"></i><b>2.8</b> Confidence intervals and bootstrapping</a></li>
<li class="chapter" data-level="2.9" data-path="chapter2.html"><a href="chapter2.html#section2-9"><i class="fa fa-check"></i><b>2.9</b> Bootstrap confidence intervals for difference in GPAs</a></li>
<li class="chapter" data-level="2.10" data-path="chapter2.html"><a href="chapter2.html#section2-10"><i class="fa fa-check"></i><b>2.10</b> Chapter summary</a></li>
<li class="chapter" data-level="2.11" data-path="chapter2.html"><a href="chapter2.html#section2-11"><i class="fa fa-check"></i><b>2.11</b> Summary of important R code</a></li>
<li class="chapter" data-level="2.12" data-path="chapter2.html"><a href="chapter2.html#section2-12"><i class="fa fa-check"></i><b>2.12</b> Practice problems</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chapter3.html"><a href="chapter3.html"><i class="fa fa-check"></i><b>3</b> One-Way ANOVA</a><ul>
<li class="chapter" data-level="3.1" data-path="chapter3.html"><a href="chapter3.html#section3-1"><i class="fa fa-check"></i><b>3.1</b> Situation</a></li>
<li class="chapter" data-level="3.2" data-path="chapter3.html"><a href="chapter3.html#section3-2"><i class="fa fa-check"></i><b>3.2</b> Linear model for One-Way ANOVA (cell-means and reference-coding)</a></li>
<li class="chapter" data-level="3.3" data-path="chapter3.html"><a href="chapter3.html#section3-3"><i class="fa fa-check"></i><b>3.3</b> One-Way ANOVA Sums of Squares, Mean Squares, and F-test</a></li>
<li class="chapter" data-level="3.4" data-path="chapter3.html"><a href="chapter3.html#section3-4"><i class="fa fa-check"></i><b>3.4</b> ANOVA model diagnostics including QQ-plots</a></li>
<li class="chapter" data-level="3.5" data-path="chapter3.html"><a href="chapter3.html#section3-5"><i class="fa fa-check"></i><b>3.5</b> Guinea pig tooth growth One-Way ANOVA example</a></li>
<li class="chapter" data-level="3.6" data-path="chapter3.html"><a href="chapter3.html#section3-6"><i class="fa fa-check"></i><b>3.6</b> Multiple (pair-wise) comparisons using Tukey’s HSD and the compact letter display</a></li>
<li class="chapter" data-level="3.7" data-path="chapter3.html"><a href="chapter3.html#section3-7"><i class="fa fa-check"></i><b>3.7</b> Pair-wise comparisons for Prisoner Rating data</a></li>
<li class="chapter" data-level="3.8" data-path="chapter3.html"><a href="chapter3.html#section3-8"><i class="fa fa-check"></i><b>3.8</b> Chapter summary</a></li>
<li class="chapter" data-level="3.9" data-path="chapter3.html"><a href="chapter3.html#section3-9"><i class="fa fa-check"></i><b>3.9</b> Summary of important R code</a></li>
<li class="chapter" data-level="3.10" data-path="chapter3.html"><a href="chapter3.html#section3-10"><i class="fa fa-check"></i><b>3.10</b> Practice problems</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chapter4.html"><a href="chapter4.html"><i class="fa fa-check"></i><b>4</b> Two-Way ANOVA</a><ul>
<li class="chapter" data-level="4.1" data-path="chapter4.html"><a href="chapter4.html#section4-1"><i class="fa fa-check"></i><b>4.1</b> Situation</a></li>
<li class="chapter" data-level="4.2" data-path="chapter4.html"><a href="chapter4.html#section4-2"><i class="fa fa-check"></i><b>4.2</b> Designing a two-way experiment and visualizing results</a></li>
<li class="chapter" data-level="4.3" data-path="chapter4.html"><a href="chapter4.html#section4-3"><i class="fa fa-check"></i><b>4.3</b> Two-Way ANOVA models and hypothesis tests</a></li>
<li class="chapter" data-level="4.4" data-path="chapter4.html"><a href="chapter4.html#section4-4"><i class="fa fa-check"></i><b>4.4</b> Guinea pig tooth growth analysis with Two-Way ANOVA</a></li>
<li class="chapter" data-level="4.5" data-path="chapter4.html"><a href="chapter4.html#section4-5"><i class="fa fa-check"></i><b>4.5</b> Observational study example: The Psychology of Debt</a></li>
<li class="chapter" data-level="4.6" data-path="chapter4.html"><a href="chapter4.html#section4-6"><i class="fa fa-check"></i><b>4.6</b> Pushing Two-Way ANOVA to the limit: Un-replicated designs</a></li>
<li class="chapter" data-level="4.7" data-path="chapter4.html"><a href="chapter4.html#section4-7"><i class="fa fa-check"></i><b>4.7</b> Chapter summary</a></li>
<li class="chapter" data-level="4.8" data-path="chapter4.html"><a href="chapter4.html#section4-8"><i class="fa fa-check"></i><b>4.8</b> Summary of important R code</a></li>
<li class="chapter" data-level="4.9" data-path="chapter4.html"><a href="chapter4.html#section4-9"><i class="fa fa-check"></i><b>4.9</b> Practice problems</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chapter5.html"><a href="chapter5.html"><i class="fa fa-check"></i><b>5</b> Chi-square tests</a><ul>
<li class="chapter" data-level="5.1" data-path="chapter5.html"><a href="chapter5.html#section5-1"><i class="fa fa-check"></i><b>5.1</b> Situation, contingency tables, and table plots</a></li>
<li class="chapter" data-level="5.2" data-path="chapter5.html"><a href="chapter5.html#section5-2"><i class="fa fa-check"></i><b>5.2</b> Homogeneity test hypotheses</a></li>
<li class="chapter" data-level="5.3" data-path="chapter5.html"><a href="chapter5.html#section5-3"><i class="fa fa-check"></i><b>5.3</b> Independence test hypotheses</a></li>
<li class="chapter" data-level="5.4" data-path="chapter5.html"><a href="chapter5.html#section5-4"><i class="fa fa-check"></i><b>5.4</b> Models for R by C tables</a></li>
<li class="chapter" data-level="5.5" data-path="chapter5.html"><a href="chapter5.html#section5-5"><i class="fa fa-check"></i><b>5.5</b> Permutation tests for the <span class="math inline">\(X^2\)</span> statistic</a></li>
<li class="chapter" data-level="5.6" data-path="chapter5.html"><a href="chapter5.html#section5-6"><i class="fa fa-check"></i><b>5.6</b> Chi-square distribution for the <span class="math inline">\(X^2\)</span> statistic</a></li>
<li class="chapter" data-level="5.7" data-path="chapter5.html"><a href="chapter5.html#section5-7"><i class="fa fa-check"></i><b>5.7</b> Examining residuals for the source of differences</a></li>
<li class="chapter" data-level="5.8" data-path="chapter5.html"><a href="chapter5.html#section5-8"><i class="fa fa-check"></i><b>5.8</b> General protocol for <span class="math inline">\(X^2\)</span> tests</a></li>
<li class="chapter" data-level="5.9" data-path="chapter5.html"><a href="chapter5.html#section5-9"><i class="fa fa-check"></i><b>5.9</b> Political party and voting results: Complete analysis</a></li>
<li class="chapter" data-level="5.10" data-path="chapter5.html"><a href="chapter5.html#section5-10"><i class="fa fa-check"></i><b>5.10</b> Is cheating and lying related in students?</a></li>
<li class="chapter" data-level="5.11" data-path="chapter5.html"><a href="chapter5.html#section5-11"><i class="fa fa-check"></i><b>5.11</b> Analyzing a stratified random sample of California schools</a></li>
<li class="chapter" data-level="5.12" data-path="chapter5.html"><a href="chapter5.html#section5-12"><i class="fa fa-check"></i><b>5.12</b> Chapter summary</a></li>
<li class="chapter" data-level="5.13" data-path="chapter5.html"><a href="chapter5.html#section5-13"><i class="fa fa-check"></i><b>5.13</b> Summary of important R commands</a></li>
<li class="chapter" data-level="5.14" data-path="chapter5.html"><a href="chapter5.html#section5-14"><i class="fa fa-check"></i><b>5.14</b> Practice problems</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chapter6.html"><a href="chapter6.html"><i class="fa fa-check"></i><b>6</b> Correlation and Simple Linear Regression</a><ul>
<li class="chapter" data-level="6.1" data-path="chapter6.html"><a href="chapter6.html#section6-1"><i class="fa fa-check"></i><b>6.1</b> Relationships between two quantitative variables</a></li>
<li class="chapter" data-level="6.2" data-path="chapter6.html"><a href="chapter6.html#section6-2"><i class="fa fa-check"></i><b>6.2</b> Estimating the correlation coefficient</a></li>
<li class="chapter" data-level="6.3" data-path="chapter6.html"><a href="chapter6.html#section6-3"><i class="fa fa-check"></i><b>6.3</b> Relationships between variables by groups</a></li>
<li class="chapter" data-level="6.4" data-path="chapter6.html"><a href="chapter6.html#section6-4"><i class="fa fa-check"></i><b>6.4</b> Inference for the correlation coefficient (Optional section)</a></li>
<li class="chapter" data-level="6.5" data-path="chapter6.html"><a href="chapter6.html#section6-5"><i class="fa fa-check"></i><b>6.5</b> Are tree diameters related to tree heights?</a></li>
<li class="chapter" data-level="6.6" data-path="chapter6.html"><a href="chapter6.html#section6-6"><i class="fa fa-check"></i><b>6.6</b> Describing relationships with a regression model</a></li>
<li class="chapter" data-level="6.7" data-path="chapter6.html"><a href="chapter6.html#section6-7"><i class="fa fa-check"></i><b>6.7</b> Least Squares Estimation</a></li>
<li class="chapter" data-level="6.8" data-path="chapter6.html"><a href="chapter6.html#section6-8"><i class="fa fa-check"></i><b>6.8</b> Measuring the strength of regressions: R<sup>2</sup></a></li>
<li class="chapter" data-level="6.9" data-path="chapter6.html"><a href="chapter6.html#section6-9"><i class="fa fa-check"></i><b>6.9</b> Outliers: leverage and influence</a></li>
<li class="chapter" data-level="6.10" data-path="chapter6.html"><a href="chapter6.html#section6-10"><i class="fa fa-check"></i><b>6.10</b> Residual diagnostics – setting the stage for inference</a></li>
<li class="chapter" data-level="6.11" data-path="chapter6.html"><a href="chapter6.html#section6-11"><i class="fa fa-check"></i><b>6.11</b> Old Faithful discharge and waiting times</a></li>
<li class="chapter" data-level="6.12" data-path="chapter6.html"><a href="chapter6.html#section6-12"><i class="fa fa-check"></i><b>6.12</b> Chapter summary</a></li>
<li class="chapter" data-level="6.13" data-path="chapter6.html"><a href="chapter6.html#section6-13"><i class="fa fa-check"></i><b>6.13</b> Summary of important R code</a></li>
<li class="chapter" data-level="6.14" data-path="chapter6.html"><a href="chapter6.html#section6-14"><i class="fa fa-check"></i><b>6.14</b> Practice problems</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chapter7.html"><a href="chapter7.html"><i class="fa fa-check"></i><b>7</b> Simple linear regression inference</a><ul>
<li class="chapter" data-level="7.1" data-path="chapter7.html"><a href="chapter7.html#section7-1"><i class="fa fa-check"></i><b>7.1</b> Model</a></li>
<li class="chapter" data-level="7.2" data-path="chapter7.html"><a href="chapter7.html#section7-2"><i class="fa fa-check"></i><b>7.2</b> Confidence interval and hypothesis tests for the slope and intercept</a></li>
<li class="chapter" data-level="7.3" data-path="chapter7.html"><a href="chapter7.html#section7-3"><i class="fa fa-check"></i><b>7.3</b> Bozeman temperature trend</a></li>
<li class="chapter" data-level="7.4" data-path="chapter7.html"><a href="chapter7.html#section7-4"><i class="fa fa-check"></i><b>7.4</b> Randomizing inferences for the slope coefficient</a></li>
<li class="chapter" data-level="7.5" data-path="chapter7.html"><a href="chapter7.html#section7-5"><i class="fa fa-check"></i><b>7.5</b> Transformations part I: Linearizing relationships</a></li>
<li class="chapter" data-level="7.6" data-path="chapter7.html"><a href="chapter7.html#section7-6"><i class="fa fa-check"></i><b>7.6</b> Transformations part II: Impacts on SLR interpretations: log(y), log(x), &amp; both log(y) &amp; log(x)</a></li>
<li class="chapter" data-level="7.7" data-path="chapter7.html"><a href="chapter7.html#section7-7"><i class="fa fa-check"></i><b>7.7</b> Confidence interval for the mean and prediction intervals for a new observation</a></li>
<li class="chapter" data-level="7.8" data-path="chapter7.html"><a href="chapter7.html#section7-8"><i class="fa fa-check"></i><b>7.8</b> Chapter summary</a></li>
<li class="chapter" data-level="7.9" data-path="chapter7.html"><a href="chapter7.html#section7-9"><i class="fa fa-check"></i><b>7.9</b> Summary of important R code</a></li>
<li class="chapter" data-level="7.10" data-path="chapter7.html"><a href="chapter7.html#section7-10"><i class="fa fa-check"></i><b>7.10</b> Practice problems</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chapter8.html"><a href="chapter8.html"><i class="fa fa-check"></i><b>8</b> Multiple linear regression</a><ul>
<li class="chapter" data-level="8.1" data-path="chapter8.html"><a href="chapter8.html#section8-1"><i class="fa fa-check"></i><b>8.1</b> Going from SLR to MLR</a></li>
<li class="chapter" data-level="8.2" data-path="chapter8.html"><a href="chapter8.html#section8-2"><i class="fa fa-check"></i><b>8.2</b> Validity conditions in MLR</a></li>
<li class="chapter" data-level="8.3" data-path="chapter8.html"><a href="chapter8.html#section8-3"><i class="fa fa-check"></i><b>8.3</b> Interpretation of MLR terms</a></li>
<li class="chapter" data-level="8.4" data-path="chapter8.html"><a href="chapter8.html#section8-4"><i class="fa fa-check"></i><b>8.4</b> Comparing multiple regression models</a></li>
<li class="chapter" data-level="8.5" data-path="chapter8.html"><a href="chapter8.html#section8-5"><i class="fa fa-check"></i><b>8.5</b> General recommendations for MLR interpretations and VIFs</a></li>
<li class="chapter" data-level="8.6" data-path="chapter8.html"><a href="chapter8.html#section8-6"><i class="fa fa-check"></i><b>8.6</b> MLR inference: Parameter inferences using the t-distribution</a></li>
<li class="chapter" data-level="8.7" data-path="chapter8.html"><a href="chapter8.html#section8-7"><i class="fa fa-check"></i><b>8.7</b> Overall F-test in multiple linear regression</a></li>
<li class="chapter" data-level="8.8" data-path="chapter8.html"><a href="chapter8.html#section8-8"><i class="fa fa-check"></i><b>8.8</b> Case study: First year college GPA and SATs</a></li>
<li class="chapter" data-level="8.9" data-path="chapter8.html"><a href="chapter8.html#section8-9"><i class="fa fa-check"></i><b>8.9</b> Different intercepts for different groups: MLR with indicator variables</a></li>
<li class="chapter" data-level="8.10" data-path="chapter8.html"><a href="chapter8.html#section8-10"><i class="fa fa-check"></i><b>8.10</b> Additive MLR with more than two groups: Headache example</a></li>
<li class="chapter" data-level="8.11" data-path="chapter8.html"><a href="chapter8.html#section8-11"><i class="fa fa-check"></i><b>8.11</b> Different slopes and different intercepts</a></li>
<li class="chapter" data-level="8.12" data-path="chapter8.html"><a href="chapter8.html#section8-12"><i class="fa fa-check"></i><b>8.12</b> F-tests for MLR models with quantitative and categorical variables and interactions</a></li>
<li class="chapter" data-level="8.13" data-path="chapter8.html"><a href="chapter8.html#section8-13"><i class="fa fa-check"></i><b>8.13</b> AICs for model selection</a></li>
<li class="chapter" data-level="8.14" data-path="chapter8.html"><a href="chapter8.html#section8-14"><i class="fa fa-check"></i><b>8.14</b> Case study: Forced expiratory volume model selection using AICs</a></li>
<li class="chapter" data-level="8.15" data-path="chapter8.html"><a href="chapter8.html#section8-15"><i class="fa fa-check"></i><b>8.15</b> Chapter summary</a></li>
<li class="chapter" data-level="8.16" data-path="chapter8.html"><a href="chapter8.html#section8-16"><i class="fa fa-check"></i><b>8.16</b> Summary of important R code</a></li>
<li class="chapter" data-level="8.17" data-path="chapter8.html"><a href="chapter8.html#section8-17"><i class="fa fa-check"></i><b>8.17</b> Practice problems</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chapter9.html"><a href="chapter9.html"><i class="fa fa-check"></i><b>9</b> Case studies</a><ul>
<li class="chapter" data-level="9.1" data-path="chapter9.html"><a href="chapter9.html#section9-1"><i class="fa fa-check"></i><b>9.1</b> Overview of material covered</a></li>
<li class="chapter" data-level="9.2" data-path="chapter9.html"><a href="chapter9.html#section9-2"><i class="fa fa-check"></i><b>9.2</b> The impact of simulated chronic nitrogen deposition on the biomass and N2-fixation activity of two boreal feather moss–cyanobacteria associations</a></li>
<li class="chapter" data-level="9.3" data-path="chapter9.html"><a href="chapter9.html#section9-3"><i class="fa fa-check"></i><b>9.3</b> Ants learn to rely on more informative attributes during decision-making</a></li>
<li class="chapter" data-level="9.4" data-path="chapter9.html"><a href="chapter9.html#section9-4"><i class="fa fa-check"></i><b>9.4</b> Multi-variate models are essential for understanding vertebrate diversification in deep time</a></li>
<li class="chapter" data-level="9.5" data-path="chapter9.html"><a href="chapter9.html#section9-5"><i class="fa fa-check"></i><b>9.5</b> General summary</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Second Semester Statistics Course with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chapter7" class="section level1">
<h1><span class="header-section-number">Chapter 7</span> Simple linear regression inference</h1>
<div id="section7-1" class="section level2">
<h2><span class="header-section-number">7.1</span> Model</h2>
<p>In Chapter <a href="chapter6.html#chapter6">6</a>, we learned how to estimate and interpret correlations and regression equations with a single predictor variable (<strong><em>simple linear regression</em></strong> or SLR). We carefully explored the variety of things that could go wrong and how to check for problems in regression situations. In this chapter, that work provides the basis for performing statistical inference that mainly focuses on the population slope coefficient based on the sample slope coefficient. As a reminder, the estimated regression model is <span class="math inline">\(\hat{y}_i = b_0 + b_1x_i\)</span>. The population regression equation is <span class="math inline">\(y_i = \beta_0 + \beta_1x_i + \varepsilon_i\)</span> where <span class="math inline">\(\beta_0\)</span> is the <strong><em>population</em></strong> (or true) <strong><em>y-intercept</em></strong> and <span class="math inline">\(\beta_1\)</span> is the <strong><em>population</em></strong> (or true) <strong><em>slope coefficient</em></strong>. These are population parameters (fixed but typically unknown). This model can be re-written to think about different components and their roles. The mean of a random variable is statistically denoted as <span class="math inline">\(E(y_i)\)</span>, the <strong><em>expected value of</em></strong> <span class="math inline">\(\mathbf{y_i}\)</span>, or as <span class="math inline">\(\mu_{y_i}\)</span> and the mean of the response variable in a simple linear model is specified by <span class="math inline">\(E(y_i) = \mu_{y_i} = \beta_0 + \beta_1x_i\)</span>. This uses the true regression line to define the model for the mean of the responses as a function of the value of the explanatory variable<a href="#fn79" class="footnoteRef" id="fnref79"><sup>79</sup></a>.</p>
<p>The other part of any statistical model is specifying a model for the variability around the mean. There are two aspects to the variability to specify here – the shape of the distribution and the spread of the distribution. This is where the normal distribution and our “normality assumption” re-appears. And for normal distributions, we need to define a variance parameter, <span class="math inline">\(\sigma^2\)</span>. Combined, the complete regression model is</p>
<p><span class="math display">\[y_i \sim N(\mu_{y_i},\sigma^2), \text{ with } 
\mu_{y_i} = \beta_0 + \beta_1x_i,\]</span></p>
<p>which can be read as “y follows a normal distribution with mean mu-y and variance sigma-squared” and that “mu-y is equal to beta-0 plus beta-1 times x”. This also implies that the random variability around the true mean, the errors, follow a normal distribution with mean 0 and that same variance, <span class="math inline">\(\varepsilon_i \sim N(0,\sigma^2)\)</span>. The true deviations (<span class="math inline">\(\varepsilon_i\)</span>) are once again estimated by the residuals, <span class="math inline">\(e_i = y_i - \hat{y}_i\)</span> = observed response – predicted response. We can use the residuals to estimate <span class="math inline">\(\sigma\)</span>, which is also called the <strong><em>residual standard error</em></strong>, <span class="math inline">\(\hat{\sigma} = \sqrt{\Sigma e^2_i / (n-2)}\)</span>. We will find this quantity near the end of the regression output as discussed below so the formula is not heavily used here. This provides us with the three parameters that are estimated as part of our SLR model: <span class="math inline">\(\beta_0, \beta_1,\text{ and } \sigma\)</span>.</p>
<p>These definitions also formalize the assumptions implicit in the regression model:</p>
<ol style="list-style-type: decimal">
<li><p>The errors follow a normal distribution (<strong><em>Normality assumption</em></strong>).</p></li>
<li><p>The errors have the same variance (<strong><em>Constant variance assumption</em></strong>).</p></li>
<li><p>The observations are independent (<strong><em>Independence assumption</em></strong>).</p></li>
<li><p>The model for the mean is “correct” (<strong><em>Linearity, No Influential points, Only one group</em></strong>).</p></li>
</ol>
<p>The diagnostics described at the end of Chapter <a href="chapter6.html#chapter6">6</a> provide techniques for checking these assumptions – meeting these assumptions is fundamental to having a regression line that we trust and inferences from it that we also can trust.</p>
<p>To make this clearer, suppose that in the <em>Beers</em> and <em>BAC</em> study that they had randomly assigned 20 students to consume each number of beers. We would expect some variation in the <em>BAC</em> for each group of 20 at each level of <em>Beers</em> but that each group of observations will be centered at the true mean <em>BAC</em> for each number of <em>Beers</em>. The regression model assumes that the <em>BAC</em> values are normally distributed around the mean for each <em>Beer</em> level, <span class="math inline">\(\text{BAC}_i \sim N(\beta_0 + \beta_1\text{ Beers}_i,\sigma^2)\)</span>, with the mean defined by the regression equation. We actually do not need to obtain more than one observation at each <span class="math inline">\(x\)</span> value to make this assumption or assess it, but the plots below show you what this could look like. The sketch in Figure <a href="chapter7.html#fig:Figure7-1">7.1</a> attempts to show the idea of normal distributions that are centered at the true regression line, all with the same shape and variance that is an assumption of the regression model. Figure <a href="chapter7.html#fig:Figure7-2">7.2</a> contains simulated realizations from a normal distribution of 20 subjects at each <em>Beer</em> level around the assumed true regression line with two different residual SEs of 0.02 and 0.06. The original BAC model has a residual SE of 0.02 but had many fewer observations at each <em>Beer</em> value.</p>

<div class="figure"><span id="fig:Figure7-1"></span>
<img src="chapter7_files/image029small.png" alt="Sketch of assumed normal distributions for the responses centered at the regression line."  />
<p class="caption">
Figure 7.1: Sketch of assumed normal distributions for the responses centered at the regression line.
</p>
</div>

<div class="figure"><span id="fig:Figure7-2"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-2-1.png" alt="Simulated data for Beers and BAC assuming two different residual standard errors (0.02 and 0.06)." width="576" />
<p class="caption">
Figure 7.2: Simulated data for Beers and BAC assuming two different residual standard errors (0.02 and 0.06).
</p>
</div>
<p>Along with getting the idea that regression models define normal distributions in the y-direction that are centered at the regression line, you can also get a sense of how variable samples from a normal distribution can appear. Each distribution of 20 subjects at each <span class="math inline">\(x\)</span> value came from a normal distribution but there are some of those distributions that might appear to generate small outliers and have slightly different variances. This can help us to remember to not be too particular when assessing assumptions and allow for some variability in spreads and a few observations from the tails of the distribution to occasionally arise.</p>
<p>In sampling from the population, we expect some amount of variability of each estimator around its true value. This variability leads to the potential variability in estimated regression lines (think of a suite of potential estimated regression lines that would be created by different random samples from the same population). Figure <a href="chapter7.html#fig:Figure7-3">7.3</a> contains the true regression line (bold, red) and realizations of the estimated regression line in simulated data based on results similar to the real data set. This variability due to random sampling is something that needs to be properly accounted for to use the <strong>single</strong> estimated regression line to make inferences about the true line and parameters based on the sample-based estimates. The next sections develop those inferential tools.</p>

<div class="figure"><span id="fig:Figure7-3"></span>
<img src="chapter7_files/image034.png" alt="Variability in realized regression lines based on sampling variation. Light grey lines are simulated realizations assuming the bold (red) line is the true SLR model and variability is similar to the original BAC data set."  />
<p class="caption">
Figure 7.3: Variability in realized regression lines based on sampling variation. Light grey lines are simulated realizations assuming the bold (red) line is the true SLR model and variability is similar to the original BAC data set.
</p>
</div>


</div>
<div id="section7-2" class="section level2">
<h2><span class="header-section-number">7.2</span> Confidence interval and hypothesis tests for the slope and intercept</h2>

<p>Our inference techniques will resemble previous material with an interest in forming confidence intervals and doing hypothesis testing, although the interpretation of confidence intervals for slope coefficients take some extra care. Remember that the general form of any parametric confidence interval is</p>
<p><span class="math display">\[\text{estimate} \mp t^*\text{SE}_{estimate},\]</span></p>
<p>so we need to obtain the appropriate standard error for regression model coefficients and the degrees of freedom to define the <span class="math inline">\(t\)</span>-distribution to look up <span class="math inline">\(t^*\)</span>. We will find the <span class="math inline">\(\text{SE}_{b_0}\)</span> and <span class="math inline">\(\text{SE}_{b_1}\)</span> in the model summary. The degrees of freedom for the <span class="math inline">\(t\)</span>-distribution in simple linear regression are <span class="math inline">\(\mathbf{df=n-2}\)</span>. Putting this together, the confidence interval for the true y-intercept, <span class="math inline">\(\beta_0\)</span>, is <span class="math inline">\(\mathbf{b_0 \mp t^*_{n-2}}\textbf{SE}_{\mathbf{b_0}}\)</span> although this confidence interval is rarely of interest. The confidence interval that is almost always of interest is for the true slope coefficient, <span class="math inline">\(\beta_1\)</span>, that is <span class="math inline">\(\mathbf{b_1 \mp t^*_{n-2}}\textbf{SE}_{\mathbf{b_1}}\)</span>. The slope confidence interval is used to do two things: (1) inference for the amount of change in the mean of <span class="math inline">\(y\)</span> for a unit change in <span class="math inline">\(x\)</span> in the population and (2) to potentially do hypothesis testing by checking whether 0 is in the CI or not. The sketch in Figure <a href="chapter7.html#fig:Figure7-3b">7.4</a> illustrates the roles of the CI for the slope in terms of determining where the population slope coefficient might be – centered at the sample slope coefficient – our best guess for the true slope. This sketch informs an <strong><em>interpretation of the slope coefficient confidence interval</em></strong>:</p>

<div class="figure"><span id="fig:Figure7-3b"></span>
<img src="chapter7_files/image045.png" alt="Graphic illustrating the confidence interval for a slope coefficient for a 1 unit increase in \(x\)."  />
<p class="caption">
Figure 7.4: Graphic illustrating the confidence interval for a slope coefficient for a 1 unit increase in <span class="math inline">\(x\)</span>.
</p>
</div>
<blockquote>
<p>For a 1 <strong>[<em>units of X</em>]</strong> increase in <strong>X</strong>, we are ___ % confident that the <strong>true change in the mean of</strong> <strong><em>Y</em></strong> will be between <strong>LL</strong> and <strong>UL</strong> <strong>[<em>units of Y</em>]</strong>.</p>
</blockquote>
<p>In this interpretation, LL and UL are the calculated lower and upper limits of the confidence interval. This builds on our previous interpretation of the slope coefficient, adding in the information about pinning down the true change (population change) in the mean of the response variable. The interpretation of the y-intercept CI is:</p>
<blockquote>
<p>For an <strong><em>x</em></strong> of 0 <strong>[<em>units of X</em>]</strong>, we are 95% confident that the true mean of <strong><em>Y</em></strong> will be between <strong>LL</strong> and <strong>UL</strong> <strong>[<em>units of Y</em>]</strong>.</p>
</blockquote>
<p>This is really only interesting if the value of <span class="math inline">\(x=0\)</span> is interesting – we’ll see a method for generating CIs for the true mean at potentially more interesting values of <span class="math inline">\(x\)</span> in Section <a href="chapter7.html#section7-7">7.7</a>. To trust the results from these confidence intervals, all the regression validity conditions need to be met (or at least close to met).</p>
<p>The only hypothesis test of interest in this situation is for the slope coefficient. To develop the hypotheses of interest in SLR, note the effect of having <span class="math inline">\(\beta_1=0\)</span> in the mean of the regression equation, <span class="math inline">\(\mu_{y_i} = \beta_0 + \beta_1x_i = \beta_0 + 0x_i = \beta_0\)</span>. This is the “intercept-only” or “mean-only” model that suggests that the mean of <span class="math inline">\(y\)</span> does not vary with different values of <span class="math inline">\(x\)</span> as it is always <span class="math inline">\(\beta_0\)</span>. We saw this model in the ANOVA material as the reduced model when the null hypothesis of no difference in the true means across the groups was true. Here, this is the same as saying that there is no linear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, or that <span class="math inline">\(x\)</span> is of no use in predicting <span class="math inline">\(y\)</span>, or that we make the same prediction for <span class="math inline">\(y\)</span> for every value of <span class="math inline">\(x\)</span>. Thus</p>
<p><span class="math display">\[\boldsymbol{H_0: \beta_1=0}\]</span></p>
<p>is a test for <strong>no linear relationship between</strong> <span class="math inline">\(\mathbf{x}\)</span> <strong>and</strong> <span class="math inline">\(\mathbf{y}\)</span> <strong>in the population</strong>. The alternative of <span class="math inline">\(\boldsymbol{H_A: \beta_1\ne 0}\)</span>, that there is <strong>some</strong> linear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> in the population, is our main test of interest in these situations. It is also possible to test greater than or less than alternatives in certain situations.</p>
<p>Test statistics for regression coefficients are developed, if assumptions are met, using the <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom. The <span class="math inline">\(t\)</span>-test statistic is generally</p>
<p><span class="math display">\[t=\frac{b_i}{\text{SE}_{b_i}}\]</span></p>
<p>with the main interest in the test for <span class="math inline">\(\beta_1\)</span> based on <span class="math inline">\(b_1\)</span> initially. The p-value would be calculated using the two-tailed area from the <span class="math inline">\(t_{n-2}\)</span> distribution calculated using the <code>pt</code> function. The p-value to test these hypotheses is also provided in the model summary as we will see below.</p>
<p>The greater than or less than alternatives can have interesting interpretations in certain situations. For example, the greater than alternative <span class="math inline">\(\left(\boldsymbol{H_A: \beta_1 &gt; 0}\right)\)</span> tests an alternative of a positive linear relationship, with the p-value extracted just from the right tail of the same <span class="math inline">\(t\)</span>-distribution. This could be used when a researcher would only find a result “interesting” if a positive relationship is detected, such as in the study of tree height and tree diameter where a researcher might be justified in deciding to test only for a positive linear relationship. Similarly, the left-tailed alternative is also possible, <span class="math inline">\(\boldsymbol{H_A: \beta_1 &lt; 0}\)</span>. To get one-tailed p-values from two-tailed results (the default), first check that the observed test statistic is in the direction of the alternative (<span class="math inline">\(t&gt;0\)</span> for <span class="math inline">\(H_A:\beta_1&gt;0\)</span> or <span class="math inline">\(t&lt;0\)</span> for <span class="math inline">\(H_A:\beta_1&lt;0\)</span>). <strong>If these conditions are met, then the p-value for the one-sided test from the two-sided version is found by dividing the reported p-value by 2</strong>. If <span class="math inline">\(t&gt;0\)</span> for <span class="math inline">\(H_A:\beta_1&gt;0\)</span> or <span class="math inline">\(t&lt;0\)</span> for <span class="math inline">\(H_A:\beta_1&lt;0\)</span> are not met, then the p-value would be greater than 0.5 and it would be easiest to look it up directly using <code>pt</code> in the direction of the alternative.</p>
<p>We can revisit a couple of examples for a last time with these ideas in hand to complete the analyses.</p>
<blockquote>
<p>For the <em>Beers, BAC</em> data, the 95% confidence for the true slope coefficient, <span class="math inline">\(\beta_1\)</span>, is</p>
</blockquote>
<p><span class="math display">\[\begin{array}{rl}
\boldsymbol{b_1 \mp t^*_{n-2}} \textbf{SE}_{\boldsymbol{b_1}}
&amp; \boldsymbol{= 0.01796 \mp 2.144787 * 0.002402} \\
&amp; \boldsymbol{= 0.01796 \mp 0.00515} \\
&amp; \boldsymbol{\rightarrow (0.0128, 0.0231).}
\end{array}\]</span></p>
<p>You can find the components of this calculation in the model summary and from <code>qt(0.975, df=n-2)</code> which was 2.145 for the <span class="math inline">\(t^*\)</span>-multiplier. Be careful not to use the <span class="math inline">\(t\)</span>-value of 7.48 in the model summary to make confidence intervals – that is the test statistic used below. The related calculations are shown at the bottom of the following code:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">m1 &lt;-<span class="st"> </span><span class="kw">lm</span>(BAC<span class="op">~</span>Beers, <span class="dt">data=</span>BB)
<span class="kw">summary</span>(m1)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = BAC ~ Beers, data = BB)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.027118 -0.017350  0.001773  0.008623  0.041027 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -0.012701   0.012638  -1.005    0.332
## Beers        0.017964   0.002402   7.480 2.97e-06
## 
## Residual standard error: 0.02044 on 14 degrees of freedom
## Multiple R-squared:  0.7998, Adjusted R-squared:  0.7855 
## F-statistic: 55.94 on 1 and 14 DF,  p-value: 2.969e-06</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dt">df=</span><span class="dv">14</span>) <span class="co"># t* multiplier for 95% CI</span></code></pre></div>
<pre><code>## [1] 2.144787</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="fl">0.017964</span> <span class="op">+</span><span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="op">*</span><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dt">df=</span><span class="dv">14</span>)<span class="op">*</span><span class="fl">0.002402</span></code></pre></div>
<pre><code>## [1] 0.01281222 0.02311578</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dt">df=</span><span class="dv">14</span>)<span class="op">*</span><span class="fl">0.002402</span></code></pre></div>
<pre><code>## [1] 0.005151778</code></pre>
<p>We can also get the confidence interval directly from the <code>confint</code> function run on our regression model, saving some calculation effort and providing both the CI for the y-intercept and the slope coefficient.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(m1)</code></pre></div>
<pre><code>##                   2.5 %     97.5 %
## (Intercept) -0.03980535 0.01440414
## Beers        0.01281262 0.02311490</code></pre>
<p>We interpret the 95% CI for the slope coefficient as follows: For a 1 <strong>beer</strong> increase in number of beers consumed, we are 95% confident that the <strong>true</strong> change in the <strong>mean</strong> <em>BAC</em> will be between 0.0128 and 0.0231 g/dL. While the estimated slope is our best guess of the impacts of an extra beer consumed based on our sample, this CI provides information about the likely range of potential impacts on the mean in the population. It also could be used to test the two-sided hypothesis test and would suggest that we should reject the null hypothesis since the confidence interval does not contain 0.</p>
<p>The width of the CI, loosely the precision of the estimated slope, is impacted by the variability of the observations around the estimated regression line, the overall sample size, and the positioning of the x-observations. Basically all those aspects relate to how “clearly” known the regression line is and that determines the estimated precision in the slope. For example, the more variability around the line that is present, the more uncertainty there is about the correct line to use (Least Squares (LS) can still find an estimated line but there are other lines that might be “close” to its optimizing choice). Similarly, more observations help us get a better estimate of the mean – an idea that permeates all statistical methods. Finally, the location of x-values can impact the precision in a slope coefficient. We’ll revisit this in the context of <strong><em>multi-collinearity</em></strong> in the next chapter, and often we have no control of x-values, but just note that different patterns of x-values can lead to different precision of estimated slope coefficients<a href="#fn80" class="footnoteRef" id="fnref80"><sup>80</sup></a>.</p>
<p>For hypothesis testing, we will almost always stick with two-sided tests in regression modeling as it is a more conservative approach and does not require us to have an expectation of a direction for relationships <em>a priori</em>. In this example, the null hypothesis for the slope coefficient is that there is no linear relationship between <em>Beers</em> and <em>BAC</em> in the population. The alternative hypothesis is that there is some linear relationship between <em>Beers</em> and <em>BAC</em> in the population. The test statistic is <span class="math inline">\(t=0.01796/0.002402 =7.48\)</span> which, if model assumptions hold, follows a <span class="math inline">\(t(14)\)</span> distribution under the null hypothesis. The model summary provides the calculation of the test statistic and the two-sided test p-value of <span class="math inline">\(2.97\text{e-6} = 0.00000297\)</span>. So we would just report “p-value &lt; 0.0001”. This suggests that there is very strong evidence of a linear relationship between <em>Beers</em> and <em>BAC</em> in the population. Because of the random assignment, we can also say that drinking beers causes changes in BAC but, because the sample was made up of volunteers, we cannot infer that these results would hold in the general population of OSU students or more generally.</p>
<p>There are also results for the y-intercept in the output. The 95% CI is from -0.0398 to 0.0144, that the true mean <em>BAC</em> for a 0 beer consuming subject is between -0.0398 to 0.01445. This is really not a big surprise but possibly is comforting to know that these results would fail to reject the null hypothesis that the true mean <em>BAC</em> for 0 <em>Beers</em> is 0. Finding no evidence of a difference from 0 makes sense and makes the estimated y-intercept of -0.013 not so problematic. In other situations, the results for the y-intercept may be more illogical but this will often be because the y-intercept is extrapolating far beyond the scope of observations. The y-intercept’s main function in regression models is to be at the right level for the slope to “work” to make a line that describes the responses and thus is usually of lesser interest.</p>
<p>As a second example, we can revisit modeling the <em>Hematocrit</em> of female Australian athletes as a function of <em>body fat %</em>. The sample size is <span class="math inline">\(n=99\)</span> so the <em>df</em> are 97 in the analysis. In Chapter <a href="chapter6.html#chapter6">6</a>, the relationship between <em>Hematocrit</em> and <em>body fat %</em> for females appeared to be a weak negative linear association. The 95% confidence interval for the slope is -0.187 to 0.0155. For a 1% increase in body fat %, we are 95% confident that the change in the true mean Hematocrit is between -0.187 and 0.0155% of blood. This suggests that we would fail to reject the null hypothesis of no linear relationship at the 5% significance level because this CI contains 0 – we can’t reject the null that the true slope is 0. In fact the p-value is 0.0965 which is larger than 0.05 which provides a consistent conclusion with using the 95% confidence interval to perform a hypothesis test. Either way, we would conclude that there is little evidence to conclude that there is some linear relationship between body fat and Hematocrit in the population of female Australian athletes. If your standards were different, say if you think p-values around 0.10 provide moderate evidence, you might have a different opinion about the evidence against the null hypothesis here. For this reason, we sometimes interpret this sort of marginal result as having some or marginal evidence against the null but certainly would never say that this presents strong evidence.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(alr3)
<span class="kw">data</span>(ais)
<span class="kw">require</span>(tibble)
ais &lt;-<span class="st"> </span><span class="kw">as.tibble</span>(ais)
aisR2 &lt;-<span class="st"> </span>ais[<span class="op">-</span><span class="kw">c</span>(<span class="dv">56</span>,<span class="dv">166</span>), <span class="kw">c</span>(<span class="st">&quot;Ht&quot;</span>,<span class="st">&quot;Hc&quot;</span>,<span class="st">&quot;Bfat&quot;</span>,<span class="st">&quot;Sex&quot;</span>)]
m2 &lt;-<span class="st"> </span><span class="kw">lm</span>(Hc<span class="op">~</span>Bfat, <span class="dt">data=</span>aisR2[aisR2<span class="op">$</span>Sex<span class="op">==</span><span class="dv">1</span>,]) <span class="co"># Results for Females </span>
<span class="kw">summary</span>(m2)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Hc ~ Bfat, data = aisR2[aisR2$Sex == 1, ])
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.2399 -2.2132 -0.1061  1.8917  6.6453 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 42.01378    0.93269  45.046   &lt;2e-16
## Bfat        -0.08504    0.05067  -1.678   0.0965
## 
## Residual standard error: 2.598 on 97 degrees of freedom
## Multiple R-squared:  0.02822,    Adjusted R-squared:  0.0182 
## F-statistic: 2.816 on 1 and 97 DF,  p-value: 0.09653</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(m2)</code></pre></div>
<pre><code>##                  2.5 %      97.5 %
## (Intercept) 40.1626516 43.86490713
## Bfat        -0.1856071  0.01553165</code></pre>
<p>One more worked example is provided from the Montana fire data. In this example pay particular attention to how we are handling the units of the response variable, log-hectares, and to the changes to doing inferences with a 99% confidence level CI, and where you can find the needed results in the following output:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mtfires &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;http://www.math.montana.edu/courses/s217/documents/climateR2.csv&quot;</span>)
mtfires<span class="op">$</span>loghectares &lt;-<span class="st"> </span><span class="kw">log</span>(mtfires<span class="op">$</span>hectares)
fire1 &lt;-<span class="st"> </span><span class="kw">lm</span>(loghectares<span class="op">~</span>Temperature, <span class="dt">data=</span>mtfires)
<span class="kw">summary</span>(fire1)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = loghectares ~ Temperature, data = mtfires)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.0822 -0.9549  0.1210  1.0007  2.4728 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -69.7845    12.3132  -5.667 1.26e-05
## Temperature   1.3884     0.2165   6.412 2.35e-06
## 
## Residual standard error: 1.476 on 21 degrees of freedom
## Multiple R-squared:  0.6619, Adjusted R-squared:  0.6458 
## F-statistic: 41.12 on 1 and 21 DF,  p-value: 2.347e-06</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(fire1, <span class="dt">level=</span><span class="fl">0.99</span>)</code></pre></div>
<pre><code>##                    0.5 %     99.5 %
## (Intercept) -104.6477287 -34.921286
## Temperature    0.7753784   2.001499</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qt</span>(<span class="fl">0.995</span>, <span class="dt">df=</span><span class="dv">21</span>)</code></pre></div>
<pre><code>## [1] 2.83136</code></pre>
<ul>
<li><p>Based on the estimated regression model, we can say that if the average temperature is 0, we expect that, on average, the log-area burned would be -69.8 log-hectares.</p></li>
<li><p>From the regression model summary, <span class="math inline">\(b_1=1.39\)</span> with <span class="math inline">\(\text{SE}_{b_1}=0.2165\)</span> and <span class="math inline">\(\mathbf{t=6.41}\)</span></p></li>
<li><p>There were <span class="math inline">\(n=23\)</span> measurements taken, so <span class="math inline">\(\mathbf{df=n-2=23-3=21}\)</span></p></li>
<li><p>Suppose that we want to test for a linear relationship between temperature and log-hectares burned:</p>
<p><span class="math display">\[H_0: \beta_1=0\]</span></p>
<ul>
<li>In words, the true slope coefficient between <em>Temperature</em> and <em>log-area burned</em> is 0 OR there is no linear relationship between <em>Temperature</em> and <em>log-area burned</em> in the population.</li>
</ul>
<p><span class="math display">\[H_A: \beta_1\ne 0\]</span></p>
<ul>
<li>In words, the alternative states that the true slope coefficient between <em>Temperature</em> and <em>log-area burned</em> is not 0 OR there is a linear relationship between <em>Temperature</em> and <em>log-area burned</em> in the population.</li>
</ul></li>
</ul>
<p>Test statistic: <span class="math inline">\(t = 1.39/0.217 = 6.41\)</span></p>
<ul>
<li>Assuming the null hypothesis to be true (no linear relationship), the <span class="math inline">\(t\)</span>-statistic follows a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-2 = 23-2=21\)</span> degrees of freedom (or simply <span class="math inline">\(t_{21}\)</span>).</li>
</ul>
<p>p-value:</p>
<ul>
<li><p>From the model summary, the <strong>p-value is</strong> <span class="math inline">\(\mathbf{2.35*10^{-6}}\)</span></p>
<ul>
<li>Interpretation: There is less than a 0.01% chance that we would observe slope coefficient like we did or something more extreme (greater than 1.39 log(hectares)/<span class="math inline">\(^\circ F\)</span>) if there were in fact no linear relationship between temperature (<span class="math inline">\(^\circ F\)</span>) and log-area burned (log-hectares) in the population.</li>
</ul></li>
</ul>
<p>Decision: The p-value is very small so presents very strong evidence against <span class="math inline">\(H_0\)</span>.</p>
<p>Conclusion: There is very strong evidence against the null hypothesis of no linear relationship, so we would conclude that there is, in fact, a linear relationship between Temperature and log(Hectares) burned. Since we have a time series of results, our inferences pertain to the results we could have observed for these years but not for years we did not observe – so just for the true slope for this sample of years. Because we can’t randomly assign the amount of area burned, we cannot make causal inferences – there are many reasons why both the average temperature and area burned would vary together that would not involve a direct connection between them.</p>
<p><span class="math display">\[\text{99}\% \text{ CI for } \beta_1: \boldsymbol{b_1 \mp
t^*_{n-2}}\textbf{SE}_{\boldsymbol{b_1}} \rightarrow 1.39 \mp 2.831\bullet 0.217
\rightarrow (0.78, 2.00)\]</span></p>
<p>Interpretation of 99% CI for slope coefficient:</p>
<ul>
<li>For a 1 degree F increase in <em>Temperature</em>, we are 99% confident that the change in the true mean log-area burned is between 0.78 and 2.00 log(Hectares).</li>
</ul>
<p>Another way to interpret this is:</p>
<ul>
<li>For a 1 degree F increase in <em>Temperature</em>, we are 99% confident that the mean Area Burned will change by between 0.78 and 2.00 log(Hectares) <strong>in the population</strong>.</li>
</ul>
<p>Also <span class="math inline">\(R^2\)</span> is 66.2%, which tells us that <em>Temperature</em> explains 66.2% of the variation in <em>log(Hectares) burned</em>. Or that the linear regression model built using <em>Temperature</em> explains 66.2% of the variation in yearly <em>log(Hectares) burned</em> so this model explains quite a bit but not all the variation in the responses.</p>
</div>
<div id="section7-3" class="section level2">
<h2><span class="header-section-number">7.3</span> Bozeman temperature trend</h2>
<p>For a new example, consider the yearly average maximum temperatures in Bozeman, MT. For over 100 years, daily measurements have been taken of the minimum and maximum temperatures at hundreds of weather stations across the US. In early years, this involved manual recording of the temperatures and resetting the thermometer to track the extremes for the following day. More recently, these measures have been replaced by digital temperature recording devices that continue to track this sort of information with much less human effort and, possibly, errors. This sort of information is often aggregated to monthly or yearly averages to be able to see “on average” changes from month-to-month or year-to-year as opposed to the day-to-day variation in the temperature - something that we are all too familiar with in our part of the country.<a href="#fn81" class="footnoteRef" id="fnref81"><sup>81</sup></a> Often the local information is aggregated further to provide regional, hemispheric, or even global average temperatures. Climate change research involves attempting to quantify the changes over time in these sorts of records.</p>
<p>These data were extracted from the National Oceanic and Atmospheric Administration’s National Centers for Environmental Information’s database (<a href="http://www.ncdc.noaa.gov/cdo-web/" class="uri">http://www.ncdc.noaa.gov/cdo-web/</a>) and we will focus on the yearly average of the monthly averages of the daily maximum temperature in Bozeman in degrees F from 1901 to 2014. We can call them yearly average maximum temperatures but note that it was a little more complicated than that to arrive at the response variable we are analyzing.</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">bozemantemps &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;http://www.math.montana.edu/courses/s217/documents/BozemanMeanMax.csv&quot;</span>)
<span class="kw">summary</span>(bozemantemps)</code></pre></div>
<pre><code>##     meanmax           Year     
##  Min.   :49.75   Min.   :1901  
##  1st Qu.:53.97   1st Qu.:1930  
##  Median :55.43   Median :1959  
##  Mean   :55.34   Mean   :1958  
##  3rd Qu.:57.02   3rd Qu.:1986  
##  Max.   :60.05   Max.   :2014</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(bozemantemps<span class="op">$</span>Year) <span class="co">#Some years are missing (1905, 1906, 1948, 1950,1995)</span></code></pre></div>
<pre><code>## [1] 109</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(car)
<span class="kw">scatterplot</span>(meanmax<span class="op">~</span>Year, <span class="dt">data=</span>bozemantemps, 
            <span class="dt">ylab=</span><span class="st">&quot;Mean Maximum Temperature (degrees F)&quot;</span>, <span class="dt">spread=</span>F,
            <span class="dt">main=</span><span class="st">&quot;Scatterplot of Bozeman Yearly Average Max Temperatures&quot;</span>)</code></pre></div>
<div class="figure"><span id="fig:Figure7-4"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-4-1.png" alt="Scatterplot of average yearly maximum temperatures in Bozeman from 1900 to 2014 with SLR (thin, green) and smoothing (thick, red) lines." width="960" />
<p class="caption">
Figure 7.5: Scatterplot of average yearly maximum temperatures in Bozeman from 1900 to 2014 with SLR (thin, green) and smoothing (thick, red) lines.
</p>
</div>
<p>The scatterplot in Figure <a href="chapter7.html#fig:Figure7-4">7.5</a> shows the results between 1901 and 2014 based on a sample of <span class="math inline">\(n=109\)</span> years because four years had too many missing months to fairly include in the responses. Missing values occur for many reasons and in this case were likely just machine or human error<a href="#fn82" class="footnoteRef" id="fnref82"><sup>82</sup></a>. These are time series data and in time series analysis we assume that the population of interest for inference is all possible realizations from the underlying process over this time frame even though we only ever get to observe one realization. In terms of climate change research, we would want to (a) assess evidence for a trend over time (hopefully assessing whether any observed trend is clearly different from a result that could have been observed by chance if there really is no change over time in the true process) and (b) quantify the size of the change over time along with the uncertainty in that estimate relative to the underlying true mean change over time. The hypothesis test for the slope answers (a) and the confidence interval for the slope addresses (b). We also should be concerned about problematic (influential) points, changing variance, and potential nonlinearity in the trend over time causing problems for the SLR inferences. The scatterplot suggests that there is a moderate or strong positive linear relationship between <em>temperatures</em> and <em>year</em> with some difference between the smoothing and SLR lines. If the curving is real, it would suggest a slightly curving response over time – the curve is relatively minor relative to the variability in the data set. There also appears to be one potential large outlier in the late 1930s.</p>
<p>We’ll perform all 6+ steps of the hypothesis test for the slope coefficient and add a confidence interval interpretation for this example. First, we need to select our hypotheses (the 2-sided test would be a <strong><em>conservative</em></strong> choice and no one that does climate change research wants to be accused of taking a <strong><em>liberal</em></strong> approach in their analyses<a href="#fn83" class="footnoteRef" id="fnref83"><sup>83</sup></a>) and our test statistic, <span class="math inline">\(t=\frac{b_1}{\text{SE}_{b_1}}\)</span>.</p>
<ol style="list-style-type: decimal">
<li><strong>Hypotheses for the slope coefficient test:</strong></li>
</ol>
<p><span class="math display">\[H_0: \beta_1=0 \text{ vs } H_A: \beta_1 \ne 0\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li><strong>Validity conditions:</strong></li>
</ol>
<ul>
<li><p><strong>Quantitative variables condition</strong></p>
<ul>
<li>Both <code>Year</code> and yearly average <code>Temperature</code> are quantitative variables so are suitable for an SLR analysis.</li>
</ul></li>
<li><p><strong>Independence of observations</strong></p>
<ul>
<li>There may be a lack of independence among years since a warm year might be followed by another warmer than average year. It would take more sophisticated models to account for this and the standard error on the slope coefficient could either get larger or smaller depending on the type of <strong><em>autocorrelation</em></strong> (correlation between neighboring time points or correlation with oneself at some time lag) present. This creates a caveat on these results but this model is often the first one researchers fit in these situations and often is reasonably correct even in the presence of some autocorrelation.</li>
</ul></li>
</ul>
<p>To assess the remaining conditions, we need to fit the regression model and use the diagnostic plots in Figure <a href="chapter7.html#fig:Figure7-5">7.6</a> to aid our assessment:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">temp1 &lt;-<span class="st"> </span><span class="kw">lm</span>(meanmax<span class="op">~</span>Year, <span class="dt">data=</span>bozemantemps)
<span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))
<span class="kw">plot</span>(temp1, <span class="dt">add.smooth=</span>F)</code></pre></div>
<div class="figure"><span id="fig:Figure7-5"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-5-1.png" alt="Diagnostic plots of the Bozeman yearly temperature simple linear  regression model." width="960" />
<p class="caption">
Figure 7.6: Diagnostic plots of the Bozeman yearly temperature simple linear regression model.
</p>
</div>
<ul>
<li><p><strong>Linearity of relationship</strong></p>
<ul>
<li><p>Examine the Residuals vs Fitted plot:</p>
<ul>
<li>There does not appear to be a clear curve remaining in the residuals so that initial curving in the smoothing line is not clearly showing up in the diagnostics and we should be able to proceed without worrying too much about the slight nonlinearity detected in the initial scatterplot.</li>
</ul></li>
</ul></li>
<li><p><strong>Equal (constant) variance</strong></p>
<ul>
<li>Examining the Residuals vs Fitted and the “Scale-Location” plots provide little to no evidence of changing variance. The variability does decrease slightly in the middle fitted values but those changes are really minor and present no real evidence of changing variability.</li>
</ul></li>
<li><p><strong>Normality of residuals</strong></p>
<ul>
<li>Examining the Normal QQ-plot for violations of the normality assumption shows only one real problem in the outlier from the 32<sup>nd</sup> observation in the data set (1934) which was flagged as a large outlier in the original scatterplot. We should be careful about inferences that assume normality and contain this point in the analysis. We might consider running the analysis with it and without that point to see how much it impacts the results just to be sure it isn’t creating evidence of a trend because of a violation of the normality assumption. The next check reassures us that re-running the model without this point would only result in slightly changing the SEs and not the slopes.</li>
</ul></li>
<li><p><strong>No influential points:</strong></p>
<ul>
<li><p>There are no influential points displayed in the Residuals vs Leverage plot since the Cook’s D contours are not displayed.</p>
<ul>
<li>Note: by default this plot contains a smoothing line that is relatively meaningless, so ignore it if is displayed. We suppressed it using the <code>add.smooth=F</code> option in <code>plot(temp1)</code> but if you forget to do that, just ignore the smoothers in the diagnostic plots especially in the Residuals vs Leverage plot.</li>
</ul></li>
<li><p>These results tells us that the outlier was not influential. If you look back at the scatterplot, it was located near the middle of the observed <span class="math inline">\(x\text{&#39;s}\)</span> so its potential leverage is low. You can find its leverage based on the plot to be around 0.12 when there are observations in the data set with leverages over 0.3. The high leverage points occur at the beginning and the end of the record because they are at the edges of the observed <span class="math inline">\(x\text{&#39;s}\)</span> and most of these points follow the overall pattern fairly well.</p></li>
</ul></li>
</ul>
<p>So the main issues are with the assumption of independence of observations and one non-influential outlier that might be compromising our normality assumption a bit.</p>
<ol start="3" style="list-style-type: decimal">
<li><p><strong>Calculate the test statistic:</strong></p>
<p><span class="math inline">\(t=0.05244/0.00476 = 11.02\)</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(temp1)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = meanmax ~ Year, data = bozemantemps)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.3779 -0.9300  0.1078  1.1960  5.8698 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -47.35123    9.32184   -5.08 1.61e-06
## Year          0.05244    0.00476   11.02  &lt; 2e-16
## 
## Residual standard error: 1.624 on 107 degrees of freedom
## Multiple R-squared:  0.5315, Adjusted R-squared:  0.5271 
## F-statistic: 121.4 on 1 and 107 DF,  p-value: &lt; 2.2e-16</code></pre></li>
<li><p>Find the p-value:</p></li>
</ol>
<ul>
<li><p>From the model summary: p-value &lt; 2e-16 or just &lt; 0.0001</p></li>
<li><p>The test statistic is assumed to follow a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-2=109-2=107\)</span> degrees of freedom. The p-value can be calculated as:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">2</span><span class="op">*</span><span class="kw">pt</span>(<span class="fl">11.02</span>, <span class="dt">df=</span><span class="dv">107</span>, <span class="dt">lower.tail=</span>F)</code></pre></div>
<pre><code>## [1] 2.498481e-19</code></pre></li>
<li><p>Which is then reported as &lt; 0.0001, which means that the chances of observing a slope coefficient as extreme or more extreme than 0.052 if the null hypothesis of no linear relationship is true is less than 0.01%.</p></li>
</ul>
<ol start="5" style="list-style-type: decimal">
<li><p><strong>Make a decision:</strong></p>
<p>The p-value is very small so provides very strong evidence against the null hypothesis of no trend over time..</p></li>
<li><p><strong>Write a conclusion:</strong></p>
<p>There is very strong evidence against the null hypothesis of no linear relationship between <em>Year</em> and yearly mean <em>Temperature</em> so we can conclude that there is, in fact, some linear relationship between <em>Year</em> and yearly mean maximum <em>Temperature</em> in Bozeman. We can conclude that this detected trend pertains to the Bozeman area in the years 1901 to 2014 but not outside of this area or time frame. We cannot say that time caused the observed changes since it was not randomly assigned and we cannot attribute the changes to any other factors because we did not consider them. But knowing that there was a trend toward increasing temperatures is an intriguing first step in a more complete analysis of changing climate in the area.</p></li>
</ol>
<p>It is also good to report the percentage of variation that the model explains: <em>Year</em> explains 54.91% of the variation in yearly average maximum <em>Temperature</em>. If this value had been very small, we might discount the previous result. Since it is moderately large, that suggests that just by using a linear trend over time we can account for quite a bit of the variation in yearly average maximum temperatures in Bozeman. Note that the percentage of variation explained would get much worse if we tried to analyze the monthly or original daily maximum temperature data even though we might find about the same estimated change over time.</p>
<p>Interpreting a confidence interval provides more useful information than the hypothesis test here – instead of just assessing evidence against the null hypothesis, we can actually provide our best guess at the true change in the mean of <span class="math inline">\(y\)</span> for a change in <span class="math inline">\(x\)</span>. Here, the 95% CI is (0.043, 0.062). This tells us that for a 1 year increase in <em>Year</em>, we are 95% confident that the change in the true mean of the yearly average maximum <em>Temperatures</em> in Bozeman is between 0.043 and 0.062 degrees F.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(temp1)</code></pre></div>
<pre><code>##                    2.5 %       97.5 %
## (Intercept) -65.83068375 -28.87177785
## Year          0.04300681   0.06187746</code></pre>
<p>Sometimes the scale of the x-variable makes interpretation a little difficult, so we can re-scale it to make it more interpretable. One option is to re-scale the variable and re-fit the regression model and the other (easier) option is to re-scale our interpretation. The idea here is that a 100-year change might be easier and more meaningful scale to interpret than a single year change. If we have a slope in the model of 0.052 (for a 1 year change), we can also say that a 100 year change in the mean is estimated to be 0.052*100 = 0.52<span class="math inline">\(^\circ F\)</span>. Similarly, the 95% CI for the population mean 100-year change would be from 0.43<span class="math inline">\(^\circ F\)</span> to 0.62<span class="math inline">\(^\circ F\)</span>. In 2007, the IPCC (Intergovernmental Panel on Climate Change; <a href="http://www.ipcc.ch/publications_and_data/ar4/wg1/en/tssts-3-1-1.html" class="uri">http://www.ipcc.ch/publications_and_data/ar4/wg1/en/tssts-3-1-1.html</a>) estimated the global temperature change from 1906 to 2005 to be 0.74<span class="math inline">\(^\circ C\)</span> per decade or, scaled up, 7.4<span class="math inline">\(^\circ C\)</span> per century (1.33<span class="math inline">\(^\circ F\)</span>). There are many reasons why our local temperature trend might differ, including that our analysis was of average maximum temperatures and the IPCC was considering the average temperature (which was not measured locally or in most places in a good way until digital instrumentation was installed) and that local trends are likely to vary around the global average change based on localized environmental conditions.</p>
<p>One issue that arises in local studies of climate change is that researchers often consider these sorts of tests at many locations and on many response variables (if I did the maximum temperature, why not also do the same analysis of the minimum temperature time series as well? And if I did the analysis for Bozeman, what about Butte and Helena and…?). Remember our discussion of multiple testing issues in an ANOVA context when we compared lots of groups? This issue can arise when regression modeling is repeated in many similar data sets, say different sites or different response variables or both, in one study. <span class="citation">Moore, Harper, and Greenwood (<a href="#ref-Moore2007">2007</a>)</span> considered the impacts on the assessment of evidence of trends of earlier spring onset timing in the Mountain West when the number of tests across many sites is accounted for. We found that the evidence for time trends decreases substantially but does not disappear. In a related study, <span class="citation">Greenwood, Harper, and Moore (<a href="#ref-Greenwood2011">2011</a>)</span> found evidence for regional trends to earlier spring onset using more sophisticated statistical models. The main point here is to <strong>be careful when using simple statistical methods repeatedly if you are not accounting for the number of tests performed</strong><a href="#fn84" class="footnoteRef" id="fnref84"><sup>84</sup></a>.</p>
<p>Along with the confidence interval, we can also plot the estimated model (Figure <a href="chapter7.html#fig:Figure7-6">7.7</a>) using a term-plot from the <code>effects</code> package (Fox, 2003). This is the same function we used for visualizing results in the ANOVA models and in its basic application you just need <code>plot(allEffects(MODELNAME))</code> although we enhanced our version a little. In regression models, we get to see the regression line along with bounds for 95% confidence intervals for the mean at every value of <span class="math inline">\(x\)</span> that was observed (explained in the next section). Note that there is also a rugplot on the x-axis showing you where values of the explanatory variable were obtained, which is useful to understanding how much information is available for different aspects of the line. Here it provides gaps for missing years of observations as sort of broken teeth in a comb.</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(effects)
<span class="kw">plot</span>(<span class="kw">allEffects</span>(temp1, <span class="dt">xlevels=</span><span class="kw">list</span>(<span class="dt">Year=</span>bozemantemps<span class="op">$</span>Year)),
     <span class="dt">grid=</span>T)</code></pre></div>
<div class="figure"><span id="fig:Figure7-6"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-6-1.png" alt="Term-plot for the Bozeman mean yearly maximum temperature linear regression model with 95% confidence interval bands for the mean in each year." width="576" />
<p class="caption">
Figure 7.7: Term-plot for the Bozeman mean yearly maximum temperature linear regression model with 95% confidence interval bands for the mean in each year.
</p>
</div>
<p>If we extended the plot for the model to <code>Year</code> = 0, we could see the reason that the y-intercept in this model is -47.4<span class="math inline">\(^\circ F\)</span>. This is obviously a large extrapolation for these data and provides a silly result. However, in paleoclimate data that goes back thousands of years using tree rings, ice cores, or sea sediments, the estimated mean in year 0 might be interesting and within the scope of observed values. It all depends on the application.</p>
<p>To make the y-intercept more interesting for our data set, we can re-scale the <span class="math inline">\(x\text{&#39;s}\)</span> before we fit the model to have the first year in the data set (1901) be “0”. This is accomplished by calculating <span class="math inline">\(\text{Year2} = \text{Year}-1901\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">bozemantemps<span class="op">$</span>Year2 &lt;-<span class="st"> </span>bozemantemps<span class="op">$</span>Year <span class="op">-</span><span class="st"> </span><span class="dv">1901</span>
<span class="kw">summary</span>(bozemantemps<span class="op">$</span>Year2)</code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.00   29.00   58.00   57.27   85.00  113.00</code></pre>
<p>The new estimated regression equation is <span class="math inline">\(\widehat{\text{Temp}}_i = 52.34 + 0.052\cdot\text{Year2}_i\)</span>. The slope and its test statistic are the same as in the previous model. The y-intercept has changed dramatically with a 95% CI from 51.72<span class="math inline">\(^\circ F\)</span> to 52.96<span class="math inline">\(^\circ F\)</span> for <code>Year2</code>=0. But we know that <code>Year2</code> has a 0 value for 1901 because of our subtraction. That means that this CI is for the true mean in 1901 and is now at least somewhat interesting. If you revisit Figure <a href="chapter7.html#fig:Figure7-6">7.7</a> you will actually see that the displayed confidence intervals provide upper and lower bounds that match this result for 1901 – the y-intercept CI matches the 95% CI for the true mean.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">temp2 &lt;-<span class="st"> </span><span class="kw">lm</span>(meanmax<span class="op">~</span>Year2, <span class="dt">data=</span>bozemantemps)
<span class="kw">summary</span>(temp2)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = meanmax ~ Year2, data = bozemantemps)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.3779 -0.9300  0.1078  1.1960  5.8698 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 52.34126    0.31383  166.78   &lt;2e-16
## Year2        0.05244    0.00476   11.02   &lt;2e-16
## 
## Residual standard error: 1.624 on 107 degrees of freedom
## Multiple R-squared:  0.5315, Adjusted R-squared:  0.5271 
## F-statistic: 121.4 on 1 and 107 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(temp2)</code></pre></div>
<pre><code>##                   2.5 %      97.5 %
## (Intercept) 51.71913822 52.96339150
## Year2        0.04300681  0.06187746</code></pre>
<p>Ideally, we want to find a regression model that does not violate any assumptions, has a high <span class="math inline">\(\mathbf{R^2}\)</span> value, and a slope coefficient with a small p-value. If any of these are not the case, then we are not completely satisfied with the regression and <strong>should be suspicious of any inference we perform</strong>. We can sometimes resolve some of the systematic issues noted above using <strong><em>transformations</em></strong>, discussed in Sections <a href="chapter7.html#section7-5">7.5</a> and <a href="chapter7.html#section7-6">7.6</a>.</p>
</div>
<div id="section7-4" class="section level2">
<h2><span class="header-section-number">7.4</span> Randomizing inferences for the slope coefficient</h2>
<p>Exploring permutation testing in SLR provides an opportunity to gauge the observed relationship against the sorts of relationships we would expect to see if there was no linear relationship between the variables. If the relationship is linear (not curvilinear) and the null hypothesis of <span class="math inline">\(\beta_1=0\)</span> is true, then any configuration of the responses relative to the predictor variable’s values is as good as any other. Consider the four scatterplots of the Bozeman temperature data versus <code>Year</code> and permuted versions of <code>Year</code> in Figure <a href="chapter7.html#fig:Figure7-7">7.8</a>. First, think about which of the panels you think present the most evidence of a linear relationship between <code>Year</code> and <code>Temperature</code>?</p>

<div class="figure"><span id="fig:Figure7-7"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-7-1.png" alt="Plot of the Temperature responses versus four versions of Year, three of which are permutations of the Year variable relative to the Temperatures." width="768" />
<p class="caption">
Figure 7.8: Plot of the <code>Temperature</code> responses versus four versions of <code>Year</code>, three of which are permutations of the Year variable relative to the Temperatures.
</p>
</div>
<p>Hopefully you can see that panel (c) contains the most clear linear relationship among the choices. The plot in panel (c) is actually the real data set and pretty clearly presents itself as “different” from the other results. When we have small p-values, the real data set will be clearly different from the permuted results because it will be almost impossible to find a permuted data set that can attain as large a slope coefficient as was observed in the real data set<a href="#fn85" class="footnoteRef" id="fnref85"><sup>85</sup></a>. This result ties back into our original interests in this climate change research situation – does our result look like it is different from what could have been observed just by chance if there were no linear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>? It seems unlikely…</p>
<p>Repeating this permutation process and tracking the estimated slope coefficients, as <span class="math inline">\(T^*\)</span>, provides another method to obtain a p-value in SLR applications. This could also be performed on the <span class="math inline">\(t\)</span>-statistic for the slope coefficient and would provide the same p-values but the sampling distribution would have a different x-axis scaling. In this situation, the observed slope of 0.052 is really far from any possible values that can be obtained using permutations as shown in Figure <a href="chapter7.html#fig:Figure7-8">7.9</a>. The p-value would be reported as <span class="math inline">\(&lt;0.0001\)</span> for the two-sided permutation test.</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Tobs &lt;-<span class="st"> </span><span class="kw">lm</span>(meanmax<span class="op">~</span>Year, <span class="dt">data=</span>bozemantemps)<span class="op">$</span>coef[<span class="dv">2</span>]
Tobs</code></pre></div>
<pre><code>##       Year 
## 0.05244213</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))
B &lt;-<span class="st"> </span><span class="dv">1000</span>
Tstar &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="ot">NA</span>, <span class="dt">nrow=</span>B)
<span class="cf">for</span> (b <span class="cf">in</span> (<span class="dv">1</span><span class="op">:</span>B)){
  Tstar[b] &lt;-<span class="st"> </span><span class="kw">lm</span>(meanmax<span class="op">~</span><span class="kw">shuffle</span>(Year), <span class="dt">data=</span>bozemantemps)<span class="op">$</span>coef[<span class="dv">2</span>]
}
<span class="kw">pdata</span>(<span class="kw">abs</span>(Tstar), <span class="kw">abs</span>(Tobs), <span class="dt">lower.tail=</span>F)</code></pre></div>
<pre><code>## Year 
##    0</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">hist</span>(Tstar, <span class="dt">xlim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="op">*</span>Tobs)
<span class="kw">abline</span>(<span class="dt">v=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="op">*</span>Tobs, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>, <span class="dt">lwd=</span><span class="dv">3</span>)
<span class="kw">plot</span>(<span class="kw">density</span>(Tstar), <span class="dt">main=</span><span class="st">&quot;Density curve of Tstar&quot;</span>, <span class="dt">xlim=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="op">*</span>Tobs)
<span class="kw">abline</span>(<span class="dt">v=</span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="op">*</span>Tobs, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>, <span class="dt">lwd=</span><span class="dv">3</span>)</code></pre></div>
<div class="figure"><span id="fig:Figure7-8"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-8-1.png" alt="Permutation distribution of the slope coefficient in the Bozeman temperature linear regression model with bold vertical lines at \(\pm b_1=0.56\) based on the observed estimated slope." width="960" />
<p class="caption">
Figure 7.9: Permutation distribution of the slope coefficient in the Bozeman temperature linear regression model with bold vertical lines at <span class="math inline">\(\pm b_1=0.56\)</span> based on the observed estimated slope.
</p>
</div>
<p>One other interesting aspect of exploring the permuted data sets as in Figure <a href="chapter7.html#fig:Figure7-7">7.8</a> is that the outlier in the late 1930s “disappears” in the permuted data sets because there were many other observations that were that warm, just none that happened around that time of the century in the real data set. This reinforces the evidence for changes over time that seem to be present in these data – old unusual years don’t look unusual in more recent years.</p>
<p>The permutation approach can be useful in situations where the normality assumption is compromised, but there are no influential points. In these situations, we might find more trustworthy p-values using permutations but only if we are working with an initial estimated regression equation that we generally trust. I personally like the permutation approach as a way of explaining what a p-value is actually measuring – the chance of seeing something like what we saw, or more extreme, if the null is true. And the previous scatterplots show what the “by chance” versions of this relationship might look like.</p>
<p>In a similar situation where we want to focus on confidence intervals for slope coefficients but are not completely comfortable with the normality assumption, it is also possible to generate bootstrap confidence intervals by sampling with replacement from the data set. This idea was introduced in Sections <a href="chapter2.html#section2-8">2.8</a> and <a href="chapter2.html#section2-9">2.9</a>. This provides a 95% bootstrap confidence interval from 0.433 to 0.62, which almost exactly matches the parametric <span class="math inline">\(t\)</span>-based confidence interval. The bootstrap distributions are very symmetric (Figure <a href="chapter7.html#fig:Figure7-9">7.10</a>). The interpretation is the same and this result reinforces the other assessments that the parametric approach is not unreasonable except possibly for the independence assumption. These randomization approaches provide no robustness against violations of the independence assumption.</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Tobs &lt;-<span class="st"> </span><span class="kw">lm</span>(meanmax<span class="op">~</span>Year, <span class="dt">data=</span>bozemantemps)<span class="op">$</span>coef[<span class="dv">2</span>]
Tobs</code></pre></div>
<pre><code>##       Year 
## 0.05244213</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))
B &lt;-<span class="st"> </span><span class="dv">1000</span>
Tstar &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="ot">NA</span>, <span class="dt">nrow=</span>B)
<span class="cf">for</span> (b <span class="cf">in</span> (<span class="dv">1</span><span class="op">:</span>B)){
  Tstar[b] &lt;-<span class="st"> </span><span class="kw">lm</span>(meanmax<span class="op">~</span>Year, <span class="dt">data=</span><span class="kw">resample</span>(bozemantemps))<span class="op">$</span>coef[<span class="dv">2</span>]
}
quantiles &lt;-<span class="st"> </span><span class="kw">qdata</span>(Tstar, <span class="kw">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))
quantiles</code></pre></div>
<pre><code>##         quantile     p
## 2.5%  0.04331326 0.025
## 97.5% 0.06195345 0.975</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">hist</span>(Tstar, <span class="dt">labels=</span>T, <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">450</span>))
<span class="kw">abline</span>(<span class="dt">v=</span>Tobs, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>, <span class="dt">lwd=</span><span class="dv">2</span>)
<span class="kw">abline</span>(<span class="dt">v=</span>quantiles<span class="op">$</span>quantile, <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>, <span class="dt">lwd=</span><span class="dv">3</span>)
<span class="kw">plot</span>(<span class="kw">density</span>(Tstar), <span class="dt">main=</span><span class="st">&quot;Density curve of Tstar&quot;</span>)
<span class="kw">abline</span>(<span class="dt">v=</span>Tobs, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>, <span class="dt">lwd=</span><span class="dv">2</span>)
<span class="kw">abline</span>(<span class="dt">v=</span>quantiles<span class="op">$</span>quantile, <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>, <span class="dt">lwd=</span><span class="dv">3</span>)</code></pre></div>
<div class="figure"><span id="fig:Figure7-9"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-9-1.png" alt="Bootstrap distribution of the slope coefficient in the Bozeman temperature linear regression model with bold vertical lines delineating 95% confidence interval and observed slope of 0.52." width="960" />
<p class="caption">
Figure 7.10: Bootstrap distribution of the slope coefficient in the Bozeman temperature linear regression model with bold vertical lines delineating 95% confidence interval and observed slope of 0.52.
</p>
</div>
</div>
<div id="section7-5" class="section level2">
<h2><span class="header-section-number">7.5</span> Transformations part I: Linearizing relationships</h2>
<p>When the influential point, linearity, constant variance and/or normality assumptions are violated, we cannot trust any of the inferences generated by the regression model. The violations occur on gradients from minor to really major problems. As we have seen from the examples in the last two chapters, it has been hard to find data sets that were free of all issues. Furthermore, it may seem hopeless to be able to make successful inferences in some of these situations with the previous tools. There are three potential solutions to violations of the validity conditions:</p>
<ol style="list-style-type: decimal">
<li><p>Consider removing an offending point or two and see if this improves the results, presenting results both with and without those points to describe their impact<a href="#fn86" class="footnoteRef" id="fnref86"><sup>86</sup></a>,</p></li>
<li><p>Try to transform the response, explanatory, or both variables and see if you can force the data set to meet our SLR assumptions after transformation (the focus of this and the next section), or</p></li>
<li><p>Consider more advanced statistical models that can account for these issues (the focus of subsequent statistics courses).</p></li>
</ol>
<p>Transformations</em></strong> involve applying a function to one or both variables. After applying this transformation, one hopes to have alleviated whatever issues encouraged its consideration. <strong><em>Linear transformation functions</em></strong>, of the form <span class="math inline">\(z_{\text{new}}=a*x+b\)</span>, will never help us to fix assumptions in regression situations; linear transformations change the scaling of the variables but not their shape or the relationship between two variables. For example, in the Bozeman Temperature data example, we subtracted 1901 from the <code>Year</code> variable to have <code>Year2</code> start at 0 and go up to 113. We could also apply a linear transformation to change Temperature from being measured in <span class="math inline">\(^\circ F\)</span> to <span class="math inline">\(^\circ C\)</span> using <span class="math inline">\(^\circ C=[^\circ F - 32] *(5/9)\)</span>. The scatterplots on both the original and transformed scales are provided in Figure <a href="chapter7.html#fig:Figure7-10">7.11</a>. All the coefficients in the regression model and the labels on the axes change, but the “picture” is still the same. Additionally, all the inferences remain the same – and p-values are unchanged by linear transformations. So linear transformations can be “fun” but really are only useful if they make the coefficients easier to interpret. Here if you like changes in <span class="math inline">\(^\circ C\)</span> for a 1 year increase, the slope coefficient is 0.029 and if you like the original change in <span class="math inline">\(^\circ F\)</span> for a 1 year increase, the slope coefficient is 0.052.</p>

<div class="figure"><span id="fig:Figure7-10"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-10-1.png" alt="Scatterplots of Temperature (\(^\circ F\)) versus Year (left) and Temperature (\(^\circ C\)) vs Years since 1901 (right)." width="960" />
<p class="caption">
Figure 7.11: Scatterplots of <em>Temperature</em> (<span class="math inline">\(^\circ F\)</span>) versus <em>Year</em> (left) and <em>Temperature</em> (<span class="math inline">\(^\circ C\)</span>) vs <em>Years</em> since 1901 (right).
</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">bozemantemps<span class="op">$</span>meanmaxC &lt;-<span class="st"> </span>(bozemantemps<span class="op">$</span>meanmax <span class="op">-</span><span class="st"> </span><span class="dv">32</span>)<span class="op">*</span>(<span class="dv">5</span><span class="op">/</span><span class="dv">9</span>)
temp3 &lt;-<span class="st"> </span><span class="kw">lm</span>(meanmaxC<span class="op">~</span>Year2, <span class="dt">data=</span>bozemantemps)
<span class="kw">summary</span>(temp1)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = meanmax ~ Year, data = bozemantemps)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.3779 -0.9300  0.1078  1.1960  5.8698 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -47.35123    9.32184   -5.08 1.61e-06
## Year          0.05244    0.00476   11.02  &lt; 2e-16
## 
## Residual standard error: 1.624 on 107 degrees of freedom
## Multiple R-squared:  0.5315, Adjusted R-squared:  0.5271 
## F-statistic: 121.4 on 1 and 107 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(temp3)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = meanmaxC ~ Year2, data = bozemantemps)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.8766 -0.5167  0.0599  0.6644  3.2610 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 11.300703   0.174349   64.82   &lt;2e-16
## Year2        0.029135   0.002644   11.02   &lt;2e-16
## 
## Residual standard error: 0.9022 on 107 degrees of freedom
## Multiple R-squared:  0.5315, Adjusted R-squared:  0.5271 
## F-statistic: 121.4 on 1 and 107 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Nonlinear transformation functions</em></strong> are where we apply something more complicated than this shift and scaling, something like <span class="math inline">\(y_{\text{new}}=f(y)\)</span>, where <span class="math inline">\(f(\cdot)\)</span> could be a log or power of the original variable <span class="math inline">\(y\)</span>. When we apply these sorts of transformations, interesting things can happen to our linear models and their problems. Some examples of transformations that are at least occasionally used for transforming the response variable are provided in Table <a href="chapter7.html#tab:Table7-1">7.1</a>, ranging from taking <span class="math inline">\(y\)</span> to different powers from <span class="math inline">\(y^{-2}\)</span> to <span class="math inline">\(y^2\)</span>. Typical transformations used in statistical modeling exist along a gradient of powers of the response variable, defined as <span class="math inline">\(y^{\lambda}\)</span> with <span class="math inline">\(\boldsymbol{\lambda}\)</span> being the power of the transformation of the response variable and <span class="math inline">\(\lambda = 0\)</span> implying a log-transformation. Except for <span class="math inline">\(\lambda = 1\)</span>, the transformations are all nonlinear functions of <span class="math inline">\(y\)</span>.</p>


<table>
<caption><span id="tab:Table7-1">Table 7.1: </span> Ladder of powers of transformations that are often used in statistical modeling.</caption>
<colgroup>
<col width="13%" />
<col width="32%" />
<col width="53%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"><strong>Power</strong></th>
<th align="left"><strong>Formula</strong></th>
<th align="left"><strong>Usage</strong>      </th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">2</td>
<td align="left"><span class="math inline">\(y^2\)</span></td>
<td align="left">seldom used</td>
</tr>
<tr class="even">
<td align="left">1</td>
<td align="left"><span class="math inline">\(y^1=y\)</span></td>
<td align="left">no change</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(1/2\)</span></td>
<td align="left"><span class="math inline">\(y^{0.5}=\sqrt{y}\)</span></td>
<td align="left">counts and area responses</td>
</tr>
<tr class="even">
<td align="left">0</td>
<td align="left"><span class="math inline">\(\log(y)\)</span> natural log of <span class="math inline">\(y\)</span></td>
<td align="left">counts, normality, curves, non-constant variance</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(-1/2\)</span></td>
<td align="left"><span class="math inline">\(y^{-0.5}=1/\sqrt{y}\)</span></td>
<td align="left">uncommon</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(-1\)</span></td>
<td align="left"><span class="math inline">\(y^{-1}=1/y\)</span></td>
<td align="left">for ratios</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(-2\)</span></td>
<td align="left"><span class="math inline">\(y^{-2}=1/y^2\)</span></td>
<td align="left">seldom used</td>
</tr>
</tbody>
</table>
<p>There are even more transformations possible, for example <span class="math inline">\(y^{0.33}\)</span> is sometimes useful for variables involved in measuring the volume of something. And we can also consider applying any of these transformations to the explanatory variable, and consider using them on both the response and explanatory variables at the same time. The most common application of these ideas is to transform the response variable using the log-transformation, at least as a starting point. In fact, the log-transformation is so commonly used (and misused), that we will just focus on its use. It is so commonplace in some fields that some researchers log-transform their data prior to even plotting their data. In other situations, such as when measuring acidity (pH), noise (decibels), or earthquake size (Richter scale), the measurements are already on logarithmic scales.</p>
<p>Actually, we have already analyzed data that benefited from a <strong><em>log-transformation</em></strong> – the <em>log-area burned</em> vs. <em>summer temperature</em> data for Montana. Figure <a href="chapter7.html#fig:Figure7-11">7.12</a> compares the relationship between these variables on the original hectares scale and the log-hectares scale.</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))
<span class="kw">plot</span>(hectares<span class="op">~</span>Temperature, <span class="dt">data=</span>mtfires, <span class="dt">main=</span><span class="st">&quot;(a)&quot;</span>,
     <span class="dt">ylab=</span><span class="st">&quot;Hectares&quot;</span>, <span class="dt">pch=</span><span class="dv">16</span>)
<span class="kw">plot</span>(loghectares<span class="op">~</span>Temperature, <span class="dt">data=</span>mtfires, <span class="dt">main=</span><span class="st">&quot;(b)&quot;</span>,
     <span class="dt">ylab=</span><span class="st">&quot;log-Hectares&quot;</span>, <span class="dt">pch=</span><span class="dv">16</span>)</code></pre></div>
<div class="figure"><span id="fig:Figure7-11"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-11-1.png" alt="Scatterplots of Hectares (a) and log-Hectares (b) vs Temperature." width="960" />
<p class="caption">
Figure 7.12: Scatterplots of Hectares (a) and log-Hectares (b) vs Temperature.
</p>
</div>
<p>Figure <a href="chapter7.html#fig:Figure7-11">7.12</a>(a) displays a relationship that would be hard fit using SLR – it has a curve and the variance is increasing with increasing temperatures. With a log-transformation of <em>Hectares</em>, the relationship appears to be relatively linear and have constant variance (in (b)). We considered regression models for this situation previously. This shows at least one situation where a log-transformation of a response variable can linearize a relationship and reduce non-constant variance.</p>
<p>This transformation does not always work to “fix” curvilinear relationships, in fact in some situations it can make the relationship more nonlinear. For example, reconsider the relationship between tree diameter and tree height, which contained some curvature that we could not account for in an SLR. Figure <a href="chapter7.html#fig:Figure7-12">7.13</a> shows the original version of the variables and Figure <a href="chapter7.html#fig:Figure7-13">7.14</a> shows the same information with the response variable (height) log-transformed.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(spuRs) <span class="co"># install.packages(&quot;spuRs&quot;)</span>
<span class="kw">data</span>(ufc)
ufc &lt;-<span class="st"> </span><span class="kw">as.tibble</span>(ufc)
<span class="kw">require</span>(car)
<span class="kw">scatterplot</span>(height.m<span class="op">~</span>dbh.cm, <span class="dt">data=</span>ufc[<span class="op">-</span><span class="dv">168</span>,], <span class="dt">smooth=</span>T, <span class="dt">spread=</span>F,
            <span class="dt">main=</span><span class="st">&quot;Tree height vs tree diameter&quot;</span>)
<span class="kw">scatterplot</span>(<span class="kw">log</span>(height.m)<span class="op">~</span>dbh.cm, <span class="dt">data=</span>ufc[<span class="op">-</span><span class="dv">168</span>,], <span class="dt">smooth=</span>T, <span class="dt">spread=</span>F,
            <span class="dt">main=</span><span class="st">&quot;log-Tree height vs tree diameter&quot;</span>)</code></pre></div>

<div class="figure"><span id="fig:Figure7-12"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-12-1.png" alt="Scatterplot of tree height versus tree diameter." width="576" />
<p class="caption">
Figure 7.13: Scatterplot of tree height versus tree diameter.
</p>
</div>
<p>Figure <a href="chapter7.html#fig:Figure7-13">7.14</a> with the log-transformed response seems to show a more nonlinear relationship and may even have more issues with non-constant variance. This example shows that log-transforming the response variable cannot fix all problems, even though I’ve seen some researchers assume it can. It is OK to try a transformation but remember to always plot the results to make sure it actually helped and did not make the situation worse.</p>

<div class="figure"><span id="fig:Figure7-13"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-13-1.png" alt="Scatterplot of log(tree height) versus tree diameter." width="576" />
<p class="caption">
Figure 7.14: Scatterplot of log(tree height) versus tree diameter.
</p>
</div>
<p>All is not lost in this situation, we can consider two other potential uses of the log-transformation and see if they can “fix” the relationship up a bit. One option is to apply the transformation to the explanatory variable (<code>y~log(x)</code>), displayed in Figure <a href="chapter7.html#fig:Figure7-14">7.15</a>. If the distribution of the explanatory variable is right skewed (see the boxplot on the x-axis), then consider log-transforming the explanatory variable. This will often reduce the leverage of those most extreme observations which can be useful. In this situation, it also seems to have been quite successful at linearizing the relationship, leaving some minor non-constant variance, but providing a big improvement from the relationship on the original scale.</p>

<div class="figure"><span id="fig:Figure7-14"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-14-1.png" alt="Scatterplot of tree height versus log(tree diameter)." width="576" />
<p class="caption">
Figure 7.15: Scatterplot of tree height versus log(tree diameter).
</p>
</div>
<p>The other option, especially when everything else fails, is to apply the log-transformation to both the explanatory and response variables (<code>log(y)~log(x)</code>), as displayed in Figure <a href="chapter7.html#fig:Figure7-15">7.16</a>. For this example, the transformation seems to be better than the first two options (none and only <span class="math inline">\(\log(y)\)</span>), but demonstrates some decreasing variability with larger <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> values. It has also created a new and different curve in the relationship. In the end, we might prefer to fit an SLR model to the tree <em>height</em> vs <em>log(diameter)</em> versions of the variables (Figure <a href="chapter7.html#fig:Figure7-14">7.15</a>).</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">scatterplot</span>(<span class="kw">log</span>(height.m)<span class="op">~</span><span class="kw">log</span>(dbh.cm), <span class="dt">data=</span>ufc[<span class="op">-</span><span class="dv">168</span>,], <span class="dt">smooth=</span>T,
            <span class="dt">spread=</span>F, <span class="dt">main=</span><span class="st">&quot;log-Tree height vs log-tree diameter&quot;</span>)</code></pre></div>
<div class="figure"><span id="fig:Figure7-15"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-15-1.png" alt="Scatterplot of log(tree height) versus log(tree diameter)." width="576" />
<p class="caption">
Figure 7.16: Scatterplot of log(tree height) versus log(tree diameter).
</p>
</div>
<p>Economists also like to use <span class="math inline">\(\log(y)\sim \log(x)\)</span> transformations. The log-log transformation tends to linearize certain relationships and has specific interpretations in terms of Economics theory. The log-log transformation shows up in many different disciplines as a way of obtaining a linear relationship on the log-log scale, but different fields discuss it differently. The following example shows a situation where transformations of both <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> are required and this double transformation seems to be quite successful in what looks like an initially hopeless situation for our linear modeling approach.</p>
<p>Data were collected in 1988 on the rates of infant mortality (infant deaths per 1,000 live births) and gross domestic product (GDP) per capita (in 1998 US dollars) from <span class="math inline">\(n=207\)</span> countries. These data are available from the <code>car</code> package (<span class="citation">Fox and Weisberg (<a href="#ref-R-car">2016</a>)</span>, <span class="citation">Fox (<a href="#ref-Fox2003">2003</a>)</span>) in a data set called <code>UN</code>. The four panels in Figure <a href="chapter7.html#fig:Figure7-16">7.17</a> show the original relationship and the impacts of log-transforming one or both variables. The only scatterplot that could potentially be modeled using SLR is the lower right panel (d) that shows the relationship between <em>log(infant mortality)</em> and <em>log(GDP)</em>. In the next section, we will fit models to some of these relationships and use our diagnostic plots to help us assess “success” of the transformations.</p>

<div class="figure"><span id="fig:Figure7-16"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-16-1.png" alt="Scatterplots of Infant Mortality vs GDP under four different combinations of log-transformations." width="960" />
<p class="caption">
Figure 7.17: Scatterplots of Infant Mortality vs GDP under four different combinations of log-transformations.
</p>
</div>
<p>Almost all nonlinear transformations assume that the variables are strictly greater than 0. For example, consider what happens when we apply the <code>log</code> function to 0 or a negative value in R:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">log</span>(<span class="op">-</span><span class="dv">1</span>)</code></pre></div>
<pre><code>## [1] NaN</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">log</span>(<span class="dv">0</span>)</code></pre></div>
<pre><code>## [1] -Inf</code></pre>
<p>So be careful to think about the domain of the transformation function before using transformations. For example, when using the log-transformation make sure that the data values are non-zero and positive or you will get some surprises when you go to fit your regression model to a data set with NaNs (not a number) and/or <span class="math inline">\(-\infty\text{&#39;s}\)</span> in it.</p>
<p>Sometimes the log-transformations will not be entirely successful. If the relationship is <strong><em>monotonic</em></strong> (strictly positive or strictly negative but not both), then possibly another stop on the ladder of transformations in Table <a href="chapter7.html#tab:Table7-1">7.1</a> might work. If the relationship is not monotonic, then it may be better to consider a more complex regression model that can accommodate the shape in the relationship or to split the data set in two so you can use SLR on each part.</p>
<p>Finally, remember that <code>log</code> in statistics and especially in R means the <strong><em>natural log</em></strong> (<em>ln</em> or log base <em>e</em> as you might see it elsewhere). In these situations, applying <code>log10</code> function (which provides log base 10) to the variables would lead to very similar results, but readers may assume you used <span class="math inline">\(\ln\)</span> if you don’t state that you used <span class="math inline">\(log_{10}\)</span>. The main thing to remember to do is to be clear when communicating the version you are using. As an example, I was working with researchers on a study <span class="citation">(Dieser, Greenwood, and Foreman <a href="#ref-Dieser2010">2010</a>)</span> related to impacts of environmental stresses on bacterial survival. The response variable was log-transformed counts and involved smoothed regression lines fit on this scale. I was using natural logs to fit the models and then shared the fitted values from the models and my collaborators back-transformed the results assuming that I had used <span class="math inline">\(log_{10}\)</span>. We quickly resolved our differences once we discovered them but this serves as a reminder at how important communication is in group projects – we both said we were working with log-transformations and didn’t know that we defaulted to different bases.</p>
<table>
<tbody>
<tr class="odd">
<td align="left">Generally, in statistics, it’s safe to assume</td>
</tr>
<tr class="even">
<td align="left">that everything is log base <em>e</em> unless otherwise specified.</td>
</tr>
</tbody>
</table>

</div>
<div id="section7-6" class="section level2">
<h2><span class="header-section-number">7.6</span> Transformations part II: Impacts on SLR interpretations: log(y), log(x), &amp; both log(y) &amp; log(x)</h2>

<p>The previous attempts to linearize relationships imply a desire to be able to fit SLR models. The <em>log</em>-transformations, when successful, provide the potential to apply our SLR model. There are then two options for interpretations: you can either interpret the model on the transformed scale or you can translate the SLR model on the transformed scale back to the original scale of the variables. It ends up that <em>log</em>-transformations have special interpretations on the original scales depending on whether the <em>log</em> was applied to the response variable, the explanatory variable, or both.</p>
<p><strong>Scenario 1: log(y) vs x model:</strong></p>
<div class="figure"><span id="fig:Figure7-17"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-17-1.png" alt="Plot of the estimated SLR (a) and implied model for the median on the original Hectares scale (b) for the area burned vs temperature data." width="960" />
<p class="caption">
Figure 7.18: Plot of the estimated SLR (a) and implied model for the median on the original Hectares scale (b) for the area burned vs temperature data.
</p>
</div>
<p>First consider the <span class="math inline">\(\log(y) \sim x\)</span> situations where the estimated model is of the form <span class="math inline">\(\widehat{\log(y)} = b_0 + b_1x\)</span>. When only the response is <em>log</em>-transformed, some people call this a <strong><em>semi-log model</em></strong>. But many researchers will use this model without any special considerations, as long as it provides a situation where the SLR assumptions are reasonably well-satisfied. To understand the properties and eventually the interpretation of transformed-variables models, we need to try to “reverse” our transformation. If we exponentiate<a href="#fn87" class="footnoteRef" id="fnref87"><sup>87</sup></a> both sides of <span class="math inline">\(\log(y)=b_0 + b_1x\)</span>, we get:</p>
<ul>
<li><p><span class="math inline">\(\exp(\log(y))=\exp(b_0 + b_1x)\)</span>, <em>which is</em></p></li>
<li><p><span class="math inline">\(y=\exp(b_0 + b_1x)\)</span>, <em>which can be re-written as</em></p></li>
<li><p><span class="math inline">\(y=\exp(b_0)\exp(b_1x)\)</span>. <em>This is based on the rules for</em> <code>exp()</code> <em>where</em> <span class="math inline">\(\exp(a+b)=\exp(a)\exp(b)\)</span>.</p></li>
<li><p>Now consider what happens if we increase <span class="math inline">\(x\)</span> by 1 unit, going from <span class="math inline">\(x\)</span> to <span class="math inline">\(x+1\)</span>, providing a new predicted <span class="math inline">\(y\)</span> that we can call <span class="math inline">\(y^*\)</span>: <span class="math inline">\(y^*=\exp(b_0)\exp[b_1(x+1)]\)</span>:</p></li>
<li><p><span class="math inline">\(y^*={\color{red}{\underline{\boldsymbol{\exp(b_0)\exp(b_1x)}}}}\exp(b_1)\)</span>. <em>Now note that the underlined, bold component was the y-value for</em> <span class="math inline">\(x\)</span>.</p></li>
<li><p><span class="math inline">\(y^* = {\color{red}{\boldsymbol{y}}}\exp(b_1)\)</span>. <em>Found by replacing</em> <span class="math inline">\(\color{red}{\mathbf{\exp(b_0)\exp(b_1x)}}\)</span> <em>with</em> <span class="math inline">\(\color{red}{\mathbf{y}}\)</span>, <em>the value for</em> <span class="math inline">\(x\)</span>.</p></li>
</ul>
<p>So the difference in fitted values between <span class="math inline">\(x\)</span> and <span class="math inline">\(x+1\)</span> is to multiply the result for <span class="math inline">\(x\)</span> (that was predicting <span class="math inline">\(\color{red}{\mathbf{y}}\)</span>) by <span class="math inline">\(\exp(b_1)\)</span> to get to the predicted result for <span class="math inline">\(x+1\)</span> (called <span class="math inline">\(y^*\)</span>). We can then use this result to form our <span class="math inline">\(\mathit{\boldsymbol{\log(y)\sim x}}\)</span> <strong><em>slope interpretation</em></strong>: for a 1 unit increase in <span class="math inline">\(x\)</span>, we observe a multiplicative change of <span class="math inline">\(\mathbf{exp(b_1)}\)</span> in the response. When we compute a mean on logged variables that are symmetrically distributed (this should occur if our transformation was successful) and then exponentiate the results, the proper interpretation is that the changes are happening in the <strong>median</strong> of the original responses. This is the only time in the course that we will switch our inferences to medians instead of means, and we don’t do this because we want to, we do it because it is result of modeling on the <span class="math inline">\(\log(y)\)</span> scale if successful.</p>
<p>When we are working with regression equations, slopes can either be positive or negative and our interpretations change based on this result to either result in growth (<span class="math inline">\(b_1&gt;0\)</span>) or decay (<span class="math inline">\(b_1&lt;0\)</span>) in the responses as the explanatory variable is increased. As an example, consider <span class="math inline">\(b_1=0.4\)</span> and <span class="math inline">\(\exp(b_1)=\exp(0.4)=1.492\)</span>. There are a couple of ways to interpret this on the original scale of the response variable <span class="math inline">\(y\)</span>:</p>
<p>For <span class="math inline">\(\mathbf{b_1&gt;0}\)</span>:</p>
<ol style="list-style-type: decimal">
<li><p>For a 1 unit increase in <span class="math inline">\(x\)</span>, the multiplicative change in the median of <span class="math inline">\(y\)</span> is 1.492.</p></li>
<li><p>We can convert this into a <strong>percentage increase</strong> by subtracting 1 from <span class="math inline">\(\exp(0.4)\)</span>, <span class="math inline">\(1.492-1.0=0.492\)</span> and multiplying the result by 100, <span class="math inline">\(0.492*100=49.2\%\)</span>. This is interpreted as: For a 1 unit increase in <span class="math inline">\(x\)</span>, the median of <span class="math inline">\(y\)</span> increases by 49.2%.</p></li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">exp</span>(<span class="fl">0.4</span>)</code></pre></div>
<pre><code>## [1] 1.491825</code></pre>
<p>For <span class="math inline">\(\mathbf{b_1&lt;0}\)</span>, the change on the <em>log</em>-scale is negative and that implies on the original scale that the curve decays to 0. For example, consider <span class="math inline">\(b_1=-0.3\)</span> and <span class="math inline">\(\exp(-0.3)=0.741\)</span>. Again, there are two versions of the interpretation possible:</p>
<ol style="list-style-type: decimal">
<li><p>For a 1 unit increase in <span class="math inline">\(x\)</span>, the multiplicative change in the median of <span class="math inline">\(y\)</span> is 0.741.</p></li>
<li><p>For negative slope coefficients, the percentage decrease is calculated as <span class="math inline">\((1-\exp(b_1))*100\%\)</span>. For <span class="math inline">\(\exp(-0.3)=0.741\)</span>, this is <span class="math inline">\((1-0.741)*100=25.9\%\)</span>. This is interpreted as: For a 1 unit increase in <span class="math inline">\(x\)</span>, the median of <span class="math inline">\(y\)</span> decreases by 25.9%.</p></li>
</ol>
<p>We suspect that you will typically prefer interpretation #1 for both directions but it is important to be able think about the results in terms of <strong><em>% change of the medians</em></strong> to make the scale of change more understandable. Some examples will help us see how these ideas can be used in applications.</p>
<p>For the area burned data set, the estimated regression model is <span class="math inline">\(\log(\widehat{\text{hectares}})=-69.8+1.39\cdot\text{ Temp}\)</span>. On the original scale, this implies that the model is <span class="math inline">\(\widehat{\text{hectares}}=\exp(-69.8)\exp(1.39\text{ Temp})\)</span>. Figure <a href="chapter7.html#fig:Figure7-17">7.18</a> provides the <span class="math inline">\(\log(y)\)</span> scale version of the model and the model transformed to the original scale of measurement. On the log-hectares scale, the interpretation of the slope is: For a 1<span class="math inline">\(^\circ F\)</span> increase in summer temperature, we expect a 1.39 log-hectares/1<span class="math inline">\(^\circ F\)</span> change, on average, in the log-area burned. On the original scale: A 1<span class="math inline">\(^\circ F\)</span> increase in temperature is related to multiplicative change in the median number of hectares burned of <span class="math inline">\(\exp(1.39)=4.01\)</span>. That seems like a big rate of growth but the curve does grow rapidly as shown in panel (b), especially for values over 58<span class="math inline">\(^\circ F\)</span> where the area burned is starting to be really large. You can think of the multiplicative change here in the following way: the median number of hectares burned is 4 times higher at 58<span class="math inline">\(^\circ F\)</span> than at 57<span class="math inline">\(^\circ F\)</span> and the median area burned is 4 times larger at 59<span class="math inline">\(^\circ F\)</span> than at 58<span class="math inline">\(^\circ F\)</span>… This can also be interpreted on a % change scale: A 1<span class="math inline">\(^\circ F\)</span> increase in temperature is related to a <span class="math inline">\((4.01-1)*100 = 301\%\)</span> increase in the median number of hectares burned.</p>

<p><strong>Scenario 2: y vs log(x) model:</strong></p>

<div class="figure"><span id="fig:Figure7-18"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-18-1.png" alt="Plot of the observations and estimated SLR model (mortality~ log(GDP)) (top) and implied model (bottom) for the infant mortality data." width="960" />
<p class="caption">
Figure 7.19: Plot of the observations and estimated SLR model (mortality~ log(GDP)) (top) and implied model (bottom) for the infant mortality data.
</p>
</div>
<p>When only the explanatory variable is log-transformed, it has a different sort of impact on the regression model interpretation. Effectively we move the percentage change onto the x-scale and modify the first part of our slope interpretation when we consider the results on the original scale for <span class="math inline">\(x\)</span>. Once again, we will consider the mathematics underlying the changes in the model and then work on applying it to real situations. When the explanatory variable is logged, the estimated regression model is <span class="math inline">\(\color{red}{\boldsymbol{y=b_0+b_1\log(x)}}\)</span>. This models the relationship between <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span> in terms of multiplicative changes in <span class="math inline">\(x\)</span> having an effect on the average <span class="math inline">\(y\)</span>. To develop an interpretation on the x-scale (not <span class="math inline">\(\log(x)\)</span>), consider the impact of doubling <span class="math inline">\(x\)</span>. This change will take us from the point (<span class="math inline">\(x,\color{red}{\boldsymbol{y=b_0+b_1\log(x)}}\)</span>) to the point <span class="math inline">\((2x,\boldsymbol{y^*=b_0+b_1\log(2x)})\)</span>. Now the impact of doubling <span class="math inline">\(x\)</span> can be simplified using the rules for logs to be:</p>
<ul>
<li><p><span class="math inline">\(\boldsymbol{y^*=b_0+b_1\log(2x)}\)</span>,</p></li>
<li><p><span class="math inline">\(\boldsymbol{y^*}={\color{red}{\underline{\boldsymbol{b_0+b_1\log(x)}}}} + b_1\log(2)\)</span>.   <em>Based on the rules for logs:</em> <span class="math inline">\(log(2x)=log(x)+log(2)\)</span>.</p></li>
<li><p><span class="math inline">\(y^* = {\color{red}{\boldsymbol{y}}}+b_1\log(2)\)</span></p></li>
<li><p>So if we double <span class="math inline">\(x\)</span>, we change the <strong>mean</strong> of <span class="math inline">\(y\)</span> by <span class="math inline">\(b_1\log(2)\)</span>.</p></li>
</ul>
<p>As before, there are couple of ways to interpret these sorts of results,</p>
<ol style="list-style-type: decimal">
<li><p><strong><em>log-scale interpretation of log(x) only model</em></strong>: for a 1 log-unit increase in <span class="math inline">\(x\)</span>, we expect a <span class="math inline">\(b_1\)</span> unit change in the mean of <span class="math inline">\(y\)</span> or</p></li>
<li><p><strong><em>original scale interpretation of log(x) only model</em></strong>: for a doubling of <span class="math inline">\(x\)</span>, we expect a <span class="math inline">\(b_1\log(2)\)</span> change in the mean of <span class="math inline">\(y\)</span>. Note that both interpretations are for the mean of the <span class="math inline">\(y\text{&#39;s}\)</span> since we haven’t changed the <span class="math inline">\(y\sim\)</span> part of the model.</p></li>
</ol>
<p>While it is not a perfect model (no model is), let’s consider the model for <em>infant mortality</em> <span class="math inline">\(\sim\)</span> <em>log(GDP)</em> in order to practice the interpretation using this type of model. This model was estimated to be <span class="math inline">\(\widehat{\text{infantmortality}}=168.648-16.6\cdot\log(\text{GDP})\)</span>. The first (simplest) interpretation of the slope coefficient is: For a 1 log-dollar increase in GDP per capita, we expect infant mortality to change, on average, by -16.6 deaths/1000 births per log-dollar. The second interpretation is on the original GDP scale: For a doubling of GDP, we expect infant mortality to change, on average, by <span class="math inline">\(-16.6\log(2) = -11.51\)</span> deaths/1000 live births. Or, the mean infant mortality is reduced by 11.51 deaths per 1000 live births for each doubling of GDP. Both versions of the model are displayed in Figure <a href="chapter7.html#fig:Figure7-18">7.19</a> – one on the scale the SLR model was fit (panel a) and the other on the original x-scale (panel b) that matches these last interpretations.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ID1 &lt;-<span class="st"> </span><span class="kw">lm</span>(infant.mortality<span class="op">~</span><span class="kw">log</span>(gdp), <span class="dt">data=</span>UN)
<span class="kw">summary</span>(ID1)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = infant.mortality ~ log(gdp), data = UN)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -62.668 -16.798  -0.452  11.064 117.374 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)  168.648      9.084   18.57   &lt;2e-16
## log(gdp)     -16.597      1.180  -14.07   &lt;2e-16
## 
## Residual standard error: 27.09 on 191 degrees of freedom
##   (14 observations deleted due to missingness)
## Multiple R-squared:  0.5089, Adjusted R-squared:  0.5063 
## F-statistic: 197.9 on 1 and 191 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="op">-</span><span class="fl">16.6</span><span class="op">*</span><span class="kw">log</span>(<span class="dv">2</span>)</code></pre></div>
<pre><code>## [1] -11.50624</code></pre>
<p>It appears that our model does not fit too well and that there might be some non-constant variance so we should check the diagnostic plots (available in Figure <a href="chapter7.html#fig:Figure7-19">7.20</a>) before we trust any of those previous interpretations.</p>

<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))
<span class="kw">plot</span>(ID1)</code></pre></div>
<div class="figure"><span id="fig:Figure7-19"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-19-1.png" alt="Diagnostics plots of the infant mortality model with log(GDP)." width="960" />
<p class="caption">
Figure 7.20: Diagnostics plots of the infant mortality model with log(GDP).
</p>
</div>
<p>There appear to be issues with outliers and a long right tail violating the normality assumption. There is curvature and non-constant variance in the results as well. There are no influential points, but we are far from happy with this model and will be revisiting this example with the responses also transformed. Remember that the log-transformation of the response can potentially fix non-constant variance, normality, and curvature issues.</p>
<p><strong>Scenario 3: log(y)~log(x) model</strong></p>

<div class="figure"><span id="fig:Figure7-20"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-20-1.png" alt="Plot of the observations and estimated SLR model log(mortality) \(\sim\) log(GDP) (left) and implied model (right) for the infant mortality data." width="576" />
<p class="caption">
Figure 7.21: Plot of the observations and estimated SLR model log(mortality) <span class="math inline">\(\sim\)</span> log(GDP) (left) and implied model (right) for the infant mortality data.
</p>
</div>
<p>A final model combines log-transformations of both <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, combining the interpretations used in the previous two situations. This model is called the <strong><em>log-log model</em></strong> and in some fields is also called the <strong><em>power law model</em></strong>. The power-law model is usually written as <span class="math inline">\(y = \beta_0x^{\beta_1}+\varepsilon\)</span>, where <span class="math inline">\(y\)</span> is thought to be proportional to <span class="math inline">\(x\)</span> raised to an estimated power of <span class="math inline">\(\beta_1\)</span> (linear if <span class="math inline">\(\beta_1=1\)</span> and quadratic if <span class="math inline">\(\beta_1=2\)</span>). It is one of the models that has been used in Geomorphology to model the shape of glaciated valley elevation profiles (that classic U-shape that comes with glacier-eroded mountain valleys). If you ignore the error term, it is possible to estimate the power-law model using our SLR approach. Consider the log-transformation of both sides of this equation starting with the power-law version:</p>
<ul>
<li><p><span class="math inline">\(\log(y) = \log(\beta_0x^{\beta_1})\)</span>,</p></li>
<li><p><span class="math inline">\(\log(y) = \log(\beta_0) + \log(x^{\beta_1}).\)</span>   <em>Based on the rules for logs:</em> <span class="math inline">\(\log(ab) = \log(a) + \log(b)\)</span>.</p></li>
<li><p><span class="math inline">\(\log(y) = \log(\beta_0) + \beta_1\log(x).\)</span>   <em>Based on the rules for logs:</em> <span class="math inline">\(\log(x^b) = b\log(x)\)</span>.</p></li>
</ul>
<p>So other than <span class="math inline">\(\log(\beta_0)\)</span> in the model, this looks just like our regular SLR model with <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> both log-transformed. The slope coefficient for <span class="math inline">\(\log(x)\)</span> is the power coefficient in the original power law model and determines whether the relationship between the original <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> in <span class="math inline">\(y=\beta_0x^{\beta_1}\)</span> is linear <span class="math inline">\((y=\beta_0x^1)\)</span> or quadratic <span class="math inline">\((y=\beta_0x^2)\)</span> or even quartic <span class="math inline">\((y=\beta_0x^4)\)</span> in some really heavily glacier carved U-shaped valleys. There are some issues with “ignoring the errors” in using SLR to estimate these models <span class="citation">(Greenwood and Humphrey <a href="#ref-Greenwood2002">2002</a>)</span> but it is still a pretty powerful result to be able to estimate the coefficients in <span class="math inline">\((y=\beta_0x^{\beta_1})\)</span> using SLR.</p>
<p>We don’t typically use the previous ideas to interpret the typical log-log regression model, instead we combine our two previous interpretation techniques to generate our interpretation. We need to work out the mathematics of doubling <span class="math inline">\(x\)</span> and the changes in <span class="math inline">\(y\)</span> starting with the <span class="math inline">\(\mathit{\boldsymbol{\log(y)\sim \log(x)}}\)</span> <strong><em>model</em></strong> that we would get out of fitting the SLR with both variables log-transformed:</p>
<ul>
<li><p><span class="math inline">\(\log(y) = b_0 + b_1\log(x)\)</span>,</p></li>
<li><p><span class="math inline">\(y = \exp(b_0 + b_1\log(x))\)</span>.   <em>Exponentiate both sides</em>.</p></li>
<li><p><span class="math inline">\(y = \exp(b_0)\exp(b_1\log(x))=\exp(b_0)x^{b_1}\)</span>.   <em>Rules for exponents and logs, simplifying.</em></p></li>
</ul>
<p>Now we can consider the impacts of doubling <span class="math inline">\(x\)</span> on <span class="math inline">\(y\)</span>, going from <span class="math inline">\((x,{\color{red}{\boldsymbol{y=\exp(b_0)x^{b_1}}}})\)</span> to <span class="math inline">\((2x,y^*)\)</span> with</p>
<ul>
<li><p><span class="math inline">\(y^* = \exp(b_0)(2x)^{b_1}\)</span>,</p></li>
<li><p><span class="math inline">\(y^* = \exp(b_0)2^{b_1}x^{b_1} = 2^{b_1}{\color{red}{\boldsymbol{\exp(b_0)x^{b_1}}}}=2^{b_1}{\color{red}{\boldsymbol{y}}}\)</span></p></li>
</ul>
<p>So doubling <span class="math inline">\(x\)</span> leads to a multiplicative change in the median of <span class="math inline">\(y\)</span> of <span class="math inline">\(2^{b_1}\)</span>.</p>
<p>Let’s apply this idea to the GDP and infant mortality data where a <span class="math inline">\(\log(x) \sim \log(y)\)</span> transformation actually made the resulting relationship look like it might be close to meeting the SLR assumptions. The regression line in Figure <a href="chapter7.html#fig:Figure7-20">7.21</a> actually looks pretty good on both the estimated log-log scale (panel a) and on the original scale (panel b) as it captures the severe nonlinearity in the relationship between the two variables.</p>

<pre><code>## 
## Call:
## lm(formula = log(infant.mortality) ~ log(gdp), data = UN)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.25334 -0.39580 -0.05258  0.35598  2.11187 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)  7.04520    0.19914   35.38   &lt;2e-16
## log(gdp)    -0.49320    0.02586  -19.07   &lt;2e-16
## 
## Residual standard error: 0.5938 on 191 degrees of freedom
##   (14 observations deleted due to missingness)
## Multiple R-squared:  0.6556, Adjusted R-squared:  0.6538 
## F-statistic: 363.7 on 1 and 191 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="figure"><span id="fig:Figure7-21"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-21-1.png" alt="Diagnostic plots for the log-log infant mortality model." width="960" />
<p class="caption">
Figure 7.22: Diagnostic plots for the log-log infant mortality model.
</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ID2 &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="kw">log</span>(infant.mortality)<span class="op">~</span><span class="kw">log</span>(gdp), <span class="dt">data=</span>UN)
<span class="kw">summary</span>(ID2)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log(infant.mortality) ~ log(gdp), data = UN)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.25334 -0.39580 -0.05258  0.35598  2.11187 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)  7.04520    0.19914   35.38   &lt;2e-16
## log(gdp)    -0.49320    0.02586  -19.07   &lt;2e-16
## 
## Residual standard error: 0.5938 on 191 degrees of freedom
##   (14 observations deleted due to missingness)
## Multiple R-squared:  0.6556, Adjusted R-squared:  0.6538 
## F-statistic: 363.7 on 1 and 191 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The estimated regression model is <span class="math inline">\(\log(\widehat{\text{infantmortality}})=7.0452-0.493\cdot\log(\text{GDP})\)</span>. The slope coefficient can be interpreted two ways.</p>
<ol style="list-style-type: decimal">
<li><p><strong><em>On the log-log scale:</em></strong> For a 1 log-dollar increase in <em>GDP</em>, we expect, on average, a change of <span class="math inline">\(-0.493\)</span> log(deaths/1000 live births) in <em>infant mortality</em>.</p></li>
<li><p><strong><em>On the original scale:</em></strong> For a doubling of <em>GDP</em>, we expect a <span class="math inline">\(2^{b_1} = 2^{-0.493} = 0.7105\)</span> multiplicative change in the median <em>infant mortality</em>. That is a 28.95% decrease in the median <em>infant mortality</em> for each doubling of <em>GDP</em>.</p></li>
</ol>
<p>The diagnostics of the log-log SLR model (Figure <a href="chapter7.html#fig:Figure7-21">7.22</a>) show minimal evidence of violations of assumptions although the tails of the residuals are a little heavy (more spread out than a normal distribution) and there might still be a little pattern remaining in the residuals vs fitted values. There are no influential points to be concerned about in this situation.</p>
<p>While we will not revisit this at all except in the case-studies in Chapter <a href="chapter9.html#chapter9">9</a>, log-transformations can be applied to the response variable in ONE and TWO-WAY ANOVA models when we are concerned about non-constant variance and non-normality issues<a href="#fn88" class="footnoteRef" id="fnref88"><sup>88</sup></a>. The remaining methods in this chapter return to SLR and assuming that the model assumptions have been met. In fact, the methods in Section <a href="chapter7.html#section7-7">7.7</a> are some of the most sensitive results to violations of the assumptions that we will explore.</p>

</div>
<div id="section7-7" class="section level2">
<h2><span class="header-section-number">7.7</span> Confidence interval for the mean and prediction intervals for a new observation</h2>

<p>Figure <a href="chapter7.html#fig:Figure7-6">7.7</a> provided a term-plot of the estimated regression line and a shaded area surrounding the estimated regression equation. Those shaded areas are based on connecting the dots on 95% confidence intervals constructed for the true mean <span class="math inline">\(y\)</span> value across all the x-values. To formalize this idea, consider a specific value of <span class="math inline">\(x\)</span>, and call it <span class="math inline">\(\boldsymbol{x_{\nu}}\)</span> (pronounced <strong>x-new</strong><a href="#fn89" class="footnoteRef" id="fnref89"><sup>89</sup></a>). Then the true mean response for this <strong><em>subpopulation</em></strong> (a subpopulation is all observations we could obtain at <span class="math inline">\(\boldsymbol{x=x_{\nu}}\)</span>) is given by <span class="math inline">\(\boldsymbol{E(Y)=\mu_\nu=\beta_0+\beta_1x_{\nu}}\)</span>. To estimate the mean response at <span class="math inline">\(\boldsymbol{x_{\nu}}\)</span>, we plug <span class="math inline">\(\boldsymbol{x_{\nu}}\)</span> into the estimated regression equation:</p>
<p><span class="math display">\[\hat{\mu}_{\nu} = b_0 + b_1x_{\nu}.\]</span></p>
<p>To form the confidence interval, we appeal to our standard formula of <span class="math inline">\(\textbf{estimate} \boldsymbol{\mp t^*}\textbf{SE}_{\textbf{estimate}}\)</span>. The <strong><em>standard error for the estimated mean at any x-value</em></strong>, denoted <span class="math inline">\(\text{SE}_{\hat{\mu}_{\nu}}\)</span>, can be calculated as</p>
<p><span class="math display">\[\text{SE}_{\hat{\mu}_{\nu}} 
= \sqrt{\text{SE}^2_{b_1}(x_{\nu}-\bar{x})^2 + \frac{\hat{\sigma}^2}{n}}\]</span></p>
<p>where <span class="math inline">\(\hat{\sigma}^2\)</span> is the squared residual standard error. This formula combines the variability in the slope estimate, <span class="math inline">\(\text{SE}_{b_1}\)</span>, scaled based on the distance of <span class="math inline">\(x_{\nu}\)</span> from <span class="math inline">\(\bar{x}\)</span> and the variability around the regression line, <span class="math inline">\(\hat{\sigma}^2\)</span>. Fortunately, R’s <code>predict</code> function can be used to provide these results for us and avoid doing this calculation by hand most of the time. The <strong><em>confidence interval for</em></strong> <span class="math inline">\(\boldsymbol{\mu_{\nu}}\)</span>, the population mean response at <span class="math inline">\(x_{\nu}\)</span>, is</p>
<p><span class="math display">\[\boldsymbol{\hat{\mu}_{\nu} \mp
t^*_{n-2}}\textbf{SE}_{\boldsymbol{\hat{\mu}_{\nu}}}.\]</span></p>
<p>In application, these intervals get wider the further we go from the mean of the <span class="math inline">\(x\text{&#39;s}\)</span>. These have interpretations that are exactly like those for the y-intercept:</p>
<blockquote>
<p>For an x-value of <span class="math inline">\(\boldsymbol{x_{\nu}}\)</span>, we are __% confident that the true mean of <strong>y</strong> is between <strong>LL</strong> and <strong>UL</strong> <strong>[<em>units of y</em>]</strong>.</p>
</blockquote>
<p>It is also useful to remember that this interpretation applies individually to every <span class="math inline">\(x\)</span> displayed in term-plots.</p>
<p>A second type of interval in this situation takes on a more challenging task – to place an interval on where we think a new observation will fall, called a <strong><em>prediction interval</em></strong> (PI). This PI will need to be much wider than the CI for the mean since we need to account for both the uncertainty in the mean and the randomness in sampling a new observation from the normal distribution centered at the true mean for <span class="math inline">\(x_{\nu}\)</span>. The interval is centered at the estimated regression line (where else could we center it?) with the estimate denoted as <span class="math inline">\(\hat{y}_{\nu}\)</span> to help us see that this interval is for a <strong>new</strong> <span class="math inline">\(y\)</span> at this x-value. The <span class="math inline">\(\text{SE}_{\hat{y}_{\nu}}\)</span> incorporates the core of the previous SE calculation and adds in the variability of a new observation in <span class="math inline">\(\boldsymbol{\hat{\sigma}^2}\)</span>:</p>
<p><span class="math display">\[\text{SE}_{\hat{y}_{\nu}} 
= \sqrt{\text{SE}^2_{b_1}(x_{\nu}-\bar{x})^2 + \dfrac{\hat{\sigma}^2}{n} 
+ \boldsymbol{\hat{\sigma}^2}}
= \sqrt{\text{SE}_{\hat{\mu}_{\nu}}^2 + \boldsymbol{\hat{\sigma}^2}}\]</span></p>
<p>The __% PI is calculated as</p>
<p><span class="math display">\[\boldsymbol{\hat{y}_{\nu} \mp t^*_{n-2}}\textbf{SE}_{\boldsymbol{\hat{y}_{\nu}}}\]</span></p>
<p>and interpreted as:</p>
<blockquote>
<p>We are __% sure that a new observation at <span class="math inline">\(\boldsymbol{x_{\nu}}\)</span> will be between <strong>LL</strong> and <strong>UL</strong> <strong>[<em>units of y</em>]</strong>. Since <span class="math inline">\(\text{SE}_{\hat{y}_{\nu}} &gt; \text{SE}_{\hat{\mu}_{\nu}}\)</span>, the <strong>PI will always be wider than the CI</strong>.</p>
</blockquote>
<p>As in confidence intervals, we assume that a 95% PI “succeeds” – now it contains the new observation – in 95% of applications of the methods and fails the other 5% of the time. Remember that for any interval estimate, the true value is either in the interval or it is not and our confidence level essentially sets our failure rate! Because PIs push into the tails of the assumed distribution of the responses these methods are very sensitive to violations of assumptions so we need to be especially certain that we have met the assumptions to trust these results will work as advertised (at the <strong><em>nominal</em></strong> (specified) level).</p>
<p>There are two ways to explore CIs for the mean and PIs for a new observation. The first is to focus on a specific x-value of interest. The second is to plot the results for all <span class="math inline">\(x\text{&#39;s}\)</span>. To do both of these, but especially to make plots, we want to learn to use the <code>predict</code> function. It can either produce the estimate for a particular <span class="math inline">\(x_{\nu}\)</span> and the <span class="math inline">\(\text{SE}_{\hat{\mu}_{\nu}}\)</span> or we can get it to directly calculate the CI and PI. The first way to use it is <code>predict(MODELNAME, se.fit=T)</code> which will provide fitted values and <span class="math inline">\(\text{SE}_{\hat{\mu}_{\nu}}\)</span> for all observed <span class="math inline">\(x\text{&#39;s}\)</span>. We can then use the <span class="math inline">\(\text{SE}_{\hat{\mu}_{\nu}}\)</span> to calculate <span class="math inline">\(\text{SE}_{\hat{y}_{\nu}}\)</span> and form our own PIs. If you want CIs, run <code>predict(MODELNAME, interval= &quot;confidence&quot;)</code>; if you want PIs, run <code>predict(MODELNAME, interval=&quot;prediction&quot;)</code>. If you want to do prediction at an x-value that was not in the original observations, add the option <code>newdata=tibble(XVARIABLENAME_FROM_ORIGINAL_MODEL=Xnu)</code> to the <code>predict</code> function call.</p>
<p>Some examples of using the predict function follow<a href="#fn90" class="footnoteRef" id="fnref90"><sup>90</sup></a>. For example, it might be interesting to use the regression model to find a 95% CI and PI for the <em>Beers</em> vs <em>BAC</em> study for a student who would consume 8 beers. Four different applications of the predict function follow. Note that <code>lwr</code> and <code>upr</code> in the output depend on what we requested. The first use of <code>predict</code> just returns the estimated mean for 8 beers:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">m1 &lt;-<span class="st"> </span><span class="kw">lm</span>(BAC<span class="op">~</span>Beers, <span class="dt">data=</span>BB)
<span class="kw">predict</span>(m1, <span class="dt">newdata=</span><span class="kw">tibble</span>(<span class="dt">Beers=</span><span class="dv">8</span>))</code></pre></div>
<pre><code>##         1 
## 0.1310095</code></pre>
<p>By turning on the <code>se.fit=T</code> option, we also get the SE for the confidence interval and degrees of freedom. Note that elements returned are labelled as <code>$fit</code>, <code>$se.fit</code>, etc. and provide some of the information to calculate CIs or PIs “by hand”.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">predict</span>(m1, <span class="dt">newdata=</span><span class="kw">tibble</span>(<span class="dt">Beers=</span><span class="dv">8</span>), <span class="dt">se.fit=</span>T)</code></pre></div>
<pre><code>## $fit
##         1 
## 0.1310095 
## 
## $se.fit
## [1] 0.009204354
## 
## $df
## [1] 14
## 
## $residual.scale
## [1] 0.02044095</code></pre>
<p>Instead of using the components of the intervals to make them, we can also directly request the CI or PI using the <code>interval=...</code> option, as in the following two lines of code.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">predict</span>(m1, <span class="dt">newdata=</span><span class="kw">tibble</span>(<span class="dt">Beers=</span><span class="dv">8</span>), <span class="dt">interval=</span><span class="st">&quot;confidence&quot;</span>)</code></pre></div>
<pre><code>##         fit       lwr       upr
## 1 0.1310095 0.1112681 0.1507509</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">predict</span>(m1, <span class="dt">newdata=</span><span class="kw">tibble</span>(<span class="dt">Beers=</span><span class="dv">8</span>), <span class="dt">interval=</span><span class="st">&quot;prediction&quot;</span>)</code></pre></div>
<pre><code>##         fit        lwr       upr
## 1 0.1310095 0.08292834 0.1790906</code></pre>
<p>Based on these results, we are 95% confident that the true mean <em>BAC</em> for 8 beers consumed is between 0.111 and 0.15 grams of alcohol per dL of blood. For a new student drinking 8 beers, we are 95% sure that the observed BAC will be between 0.083 and 0.179 g/dL. You can see from these results that the PI is much wider than the CI – it has to capture a new individual’s results 95% of the time which is much harder than trying to capture the true mean at 8 beers consumed. For completeness, we should do these same calculations “by hand”. The <code>predict(..., se.fit=T)</code> output provides almost all the pieces we need to calculate the CI and PI. The <code>$fit</code> is the <span class="math inline">\(\text{estimate} = \hat{\mu}_{\nu}=0.131\)</span>, the <code>$se.fit</code> is the SE for the estimate of the <span class="math inline">\(\text{mean} = \text{SE}_{\hat{\mu}_{\nu}}=0.0092\)</span> , <code>$df</code> is <span class="math inline">\(n-2 = 16-2=14\)</span>, and <code>$residual.scale</code> is <span class="math inline">\(\hat{\sigma}=0.02044\)</span>. So we just need the <span class="math inline">\(t^*\)</span> multiplier for 95% confidence and 14 <em>df</em>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dt">df=</span><span class="dv">14</span>) <span class="co"># t* multiplier for 95% CI or 95% PI</span></code></pre></div>
<pre><code>## [1] 2.144787</code></pre>
<p>The 95% CI for the true mean at <span class="math inline">\(\boldsymbol{x_{\nu}=8}\)</span> is then:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="fl">0.131</span> <span class="op">+</span><span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="op">*</span><span class="fl">2.1448</span><span class="op">*</span><span class="fl">0.0092</span></code></pre></div>
<pre><code>## [1] 0.1112678 0.1507322</code></pre>
<p>Which matches the previous output quite well.</p>
<p>The 95% PI requires the calculation of <span class="math inline">\(\sqrt{\text{SE}_{\hat{\mu}_{\nu}}^2 + \boldsymbol{\hat{\sigma}^2}} = \sqrt{(0.0092)^2+(0.02044)^2}=0.0224\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sqrt</span>(<span class="fl">0.0092</span><span class="op">^</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.02044</span><span class="op">^</span><span class="dv">2</span>)</code></pre></div>
<pre><code>## [1] 0.02241503</code></pre>
<p>The 95% PI at <span class="math inline">\(\boldsymbol{x_{\nu}=8}\)</span> is</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="fl">0.131</span> <span class="op">+</span><span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="op">*</span><span class="fl">2.1448</span><span class="op">*</span><span class="fl">0.0224</span></code></pre></div>
<pre><code>## [1] 0.08295648 0.17904352</code></pre>
<p>These calculations are “fun” and informative but displaying these results for all x-values is a bit more informative about the performance of the two types of intervals and for results we might expect in this application. The calculations we just performed provide endpoints of both intervals at <code>Beers</code>= 8. To make this plot, we need to create a sequence of <em>Beers</em> values to get other results for, say from 0 to 10, using the <code>seq</code> function. The <code>from</code> and <code>to</code> define the endpoints and the <code>length.out</code> defines the resolution of the grid of equally spaced points to create. Here, 30 points is more than enough to make the confidence and prediction intervals from 0 to 10 <em>Beers</em>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">beerf &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dt">from=</span><span class="dv">0</span>, <span class="dt">to=</span><span class="dv">10</span>, <span class="dt">length.out=</span><span class="dv">30</span>)
<span class="kw">head</span>(beerf,<span class="dv">6</span>)</code></pre></div>
<pre><code>## [1] 0.0000000 0.3448276 0.6896552 1.0344828 1.3793103 1.7241379</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">tail</span>(beerf,<span class="dv">6</span>)</code></pre></div>
<pre><code>## [1]  8.275862  8.620690  8.965517  9.310345  9.655172 10.000000</code></pre>
<p>Now we can call the <code>predict</code> function at the values stored in <code>beerf</code> to get the CIs across that range of <em>Beers</em> values:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">BBCI &lt;-<span class="st"> </span><span class="kw">as.tibble</span>(<span class="kw">predict</span>(m1, <span class="dt">newdata=</span><span class="kw">tibble</span>(<span class="dt">Beers=</span>beerf),
                           <span class="dt">interval=</span><span class="st">&quot;confidence&quot;</span>))
<span class="kw">head</span>(BBCI)</code></pre></div>
<pre><code>## # A tibble: 6 x 3
##             fit          lwr        upr
##           &lt;dbl&gt;        &lt;dbl&gt;      &lt;dbl&gt;
## 1 -0.0127006040 -0.039805351 0.01440414
## 2 -0.0065062033 -0.031996517 0.01898411
## 3 -0.0003118027 -0.024210653 0.02358705
## 4  0.0058825980 -0.016452670 0.02821787
## 5  0.0120769986 -0.008728854 0.03288285
## 6  0.0182713992 -0.001047321 0.03759012</code></pre>
<p>And the PIs:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">BBPI &lt;-<span class="st"> </span><span class="kw">as.tibble</span>(<span class="kw">predict</span>(m1, <span class="dt">newdata=</span><span class="kw">tibble</span>(<span class="dt">Beers=</span>beerf),
                           <span class="dt">interval=</span><span class="st">&quot;prediction&quot;</span>))
<span class="kw">head</span>(BBPI)</code></pre></div>
<pre><code>## # A tibble: 6 x 3
##             fit         lwr        upr
##           &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;
## 1 -0.0127006040 -0.06424420 0.03884300
## 2 -0.0065062033 -0.05721943 0.04420702
## 3 -0.0003118027 -0.05024406 0.04962046
## 4  0.0058825980 -0.04332045 0.05508564
## 5  0.0120769986 -0.03645092 0.06060492
## 6  0.0182713992 -0.02963777 0.06618057</code></pre>
<p>The rest of the code is just making a scatterplot and adding the five lines with a legend.</p>

<div class="figure"><span id="fig:Figure7-22"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-22-1.png" alt="Estimated SLR for BAC data with 95% confidence (dashed lines) and 95% prediction (lighter, dotted lines) intervals." width="960" />
<p class="caption">
Figure 7.23: Estimated SLR for BAC data with 95% confidence (dashed lines) and 95% prediction (lighter, dotted lines) intervals.
</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))
<span class="kw">plot</span>(BAC<span class="op">~</span>Beers, <span class="dt">data=</span>BB, <span class="dt">xlab=</span><span class="st">&quot;Beers&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;BAC&quot;</span>, <span class="dt">pch=</span><span class="dv">20</span>, <span class="dt">col=</span><span class="st">&quot;gold4&quot;</span>,
     <span class="dt">main=</span><span class="st">&quot;Scatterplot of estimated regression line with 95% CI and PI&quot;</span>)
<span class="kw">lines</span>(beerf, BBCI<span class="op">$</span>fit, <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>, <span class="dt">lwd=</span><span class="dv">3</span>)
<span class="kw">lines</span>(beerf, BBCI<span class="op">$</span>lwr, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>, <span class="dt">lty=</span><span class="dv">2</span>, <span class="dt">lwd=</span><span class="dv">3</span>)
<span class="kw">lines</span>(beerf, BBCI<span class="op">$</span>upr, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>, <span class="dt">lty=</span><span class="dv">2</span>, <span class="dt">lwd=</span><span class="dv">3</span>)
<span class="kw">lines</span>(beerf, BBPI<span class="op">$</span>lwr, <span class="dt">col=</span><span class="st">&quot;grey&quot;</span>, <span class="dt">lty=</span><span class="dv">3</span>, <span class="dt">lwd=</span><span class="dv">3</span>)
<span class="kw">lines</span>(beerf, BBPI<span class="op">$</span>upr, <span class="dt">col=</span><span class="st">&quot;grey&quot;</span>, <span class="dt">lty=</span><span class="dv">3</span>, <span class="dt">lwd=</span><span class="dv">3</span>)
<span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>, <span class="kw">c</span>(<span class="st">&quot;Estimate&quot;</span>,<span class="st">&quot;CI&quot;</span>,<span class="st">&quot;PI&quot;</span>), <span class="dt">lwd=</span><span class="dv">3</span>, <span class="dt">lty=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>),
       <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;blue&quot;</span>,<span class="st">&quot;red&quot;</span>,<span class="st">&quot;grey&quot;</span>))</code></pre></div>
<p>More importantly, note that the CI in Figure <a href="chapter7.html#fig:Figure7-22">7.23</a> clearly shows widening as we move further away from the mean of the <span class="math inline">\(x\text{&#39;s}\)</span> to the edges of the observed x-values. This reflects a decrease in knowledge of the true mean as we move away from the mean of the <span class="math inline">\(x\text{&#39;s}\)</span>. The PI also is widening slightly but not as clearly in this situation. The difference in widths in the two types of intervals becomes extremely clear when they are displayed together.</p>
<p>Similarly, the 95% CI and PIs for the Bozeman yearly average maximum temperatures in Figure <a href="chapter7.html#fig:Figure7-23">7.24</a> provide interesting information on the uncertainty in the estimated mean temperature over time. It is also interesting to explore how many of the observations fall within the 95% prediction intervals. The PIs are for new observations, but you can see how the PIs that were constructed to contain almost all the observations in the original data set but not all of them. In fact, only 2 of the 109 observations (1.8%) fall outside the 95% PIs. Since the PI needs to be concerned with unobserved new observations it makes sense that it might contain more than 95% of the observations used to make it.</p>

<div class="figure"><span id="fig:Figure7-23"></span>
<img src="07-simpleLinearRegressionInference_files/figure-html/Figure7-23-1.png" alt="Estimated SLR for Bozeman temperature data with 95% confidence (dashed lines) and 95% prediction (lighter, dotted lines) intervals." width="960" />
<p class="caption">
Figure 7.24: Estimated SLR for Bozeman temperature data with 95% confidence (dashed lines) and 95% prediction (lighter, dotted lines) intervals.
</p>
</div>
<p>We can also use these same methods to do a prediction for the year after the data set ended, 2015, and in 2050:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">predict</span>(temp1, <span class="dt">newdata=</span><span class="kw">tibble</span>(<span class="dt">Year=</span><span class="dv">2015</span>), <span class="dt">interval=</span><span class="st">&quot;confidence&quot;</span>)</code></pre></div>
<pre><code>##        fit     lwr      upr
## 1 58.31967 57.7019 58.93744</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">predict</span>(temp1, <span class="dt">newdata=</span><span class="kw">tibble</span>(<span class="dt">Year=</span><span class="dv">2015</span>), <span class="dt">interval=</span><span class="st">&quot;prediction&quot;</span>)</code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 58.31967 55.04146 61.59787</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">predict</span>(temp1, <span class="dt">newdata=</span><span class="kw">tibble</span>(<span class="dt">Year=</span><span class="dv">2050</span>), <span class="dt">interval=</span><span class="st">&quot;confidence&quot;</span>)</code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 60.15514 59.23631 61.07397</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">predict</span>(temp1, <span class="dt">newdata=</span><span class="kw">tibble</span>(<span class="dt">Year=</span><span class="dv">2050</span>), <span class="dt">interval=</span><span class="st">&quot;prediction&quot;</span>)</code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 60.15514 56.80712 63.50316</code></pre>
<p>These results tell us that we are 95% confident that the true mean yearly average maximum temperature in 2015 is (or was?) between 55.04<span class="math inline">\(^\circ F\)</span> and 61.6<span class="math inline">\(^\circ F\)</span>. And we are 95% sure that the observed yearly average maximum temperature in 2015 will be (or would have been?) between 59.2<span class="math inline">\(^\circ F\)</span> and 61.1<span class="math inline">\(^\circ F\)</span>. Obviously, 2015 has occurred, but since the data were not published when the data set was downloaded in July 2016, we can probably best treat 2015 as a potential “future” observation. The results for 2050 are clearly for the future mean and a new observation in 2050. Note that up to 2014, no values of this response had been observed above 60<span class="math inline">\(^\circ F\)</span> and the predicted mean in 2050 is over 60<span class="math inline">\(^\circ F\)</span> if the trend persists. It is also easy to criticize the use of this model for 2050 because of its extreme amount of extrapolation.</p>

</div>
<div id="section7-8" class="section level2">
<h2><span class="header-section-number">7.8</span> Chapter summary</h2>
<p>In this chapter, we raised our SLR modeling to a new level, considering inference techniques for relationships between two quantitative variables. The next chapter will build on these same techniques but add in additional explanatory variables for what is called <strong><em>multiple linear regression</em></strong> (MLR) modeling. For example, in the <em>Beers</em> vs <em>BAC</em> study, it would have been useful to control for the weight of the subjects since people of different sizes metabolize alcohol at different rates and body size might explain some of the variability. We still would want to study the effects of beer consumption but also control for the differences in subject’s weights. Or if they had studied both male and female students, we might need to change the slope or intercept for each sex, allowing the relationship between <em>Beers</em> and <em>BAC</em> to change between these groups. That will also be handled using MLR techniques but result in two simple linear regression equations – one for females and one for males.</p>
<p>In this chapter you learned how to interpret SLR models. The next chapter will feel like it is completely new initially but it actually contains very little new material, just more complicated models that use the same concepts. There will be a couple of new issues to consider for MLR and we’ll need to learn how to work with categorical variables in a regression setting – but we actually fit linear models with categorical variables in Chapters <a href="chapter3.html#chapter3">3</a> and <a href="chapter4.html#chapter4">4</a> so that isn’t actually completely new either.</p>
<p>SLR is a simple (thus its name) tool for analyzing the relationship between two quantitative variables. It contains assumptions about the estimated regression line being reasonable and about the distribution of the responses around that line to do inferences for the population regression line. Our diagnostic plots help us to carefully assess those assumptions. If we cannot trust the assumptions, then the estimated line and any inferences for the population are un-trustworthy. Transformations can fix things so that we can use SLR to fit regression models. Transformations can complicate the interpretations on the original, untransformed scale but have minimal impact on the interpretations on the transformed scale. It is important to be careful with the units of the variables, especially when dealing with transformations, as this can lead to big changes in the results depending on which scale (original or transformed) the results are being interpreted on.</p>

</div>
<div id="section7-9" class="section level2">
<h2><span class="header-section-number">7.9</span> Summary of important R code</h2>
<p>The main components of the R code used in this chapter follow with the components to modify in lighter and/or ALL CAPS text where <code>y</code> is a response variable, <code>x</code> is an explanatory variable, and the data are in <code>DATASETNAME</code>.</p>
<ul>
<li><p><strong>scatterplot(<font color='red'>y</font>~<font color='red'>x</font>, data=<font color='red'>DATASETNAME</font>, smooth=F)</strong></p>
<ul>
<li><p>Requires the <code>car</code> package.</p></li>
<li><p>Provides a scatterplot with a regression line.</p></li>
<li><p>Turn on <code>smooth=T</code> to add a smoothing line to help detect nonlinear relationships.</p></li>
</ul></li>
<li><p><strong><font color='red'>MODELNAME</font> <code>&lt;-</code> lm(<font color='red'>y</font>~ <font color='red'>x</font>, data=<font color='red'>DATASETNAME</font>)</strong></p>
<ul>
<li>Estimates a regression model using least squares.</li>
</ul></li>
<li><p><strong>summary(<font color='red'>MODELNAME</font>)</strong></p>
<ul>
<li>Provides parameter estimates and R-squared (used heavily in Chapter <a href="chapter8.html#chapter8">8</a> as well).</li>
</ul></li>
<li><p><strong>par(mfrow=c(2, 2)); plot(<font color='red'>MODELNAME</font>)</strong></p>
<ul>
<li>Provides four regression diagnostic plots in one plot.</li>
</ul></li>
<li><p><strong>confint(<font color='red'>MODELNAME</font>, level=0.95)</strong></p>
<ul>
<li><p>Provides 95% confidence intervals for the regression model coefficients.</p></li>
<li><p>Change <code>level</code> if you want other confidence levels.</p></li>
</ul></li>
<li><p><strong>plot(allEffects(<font color='red'>MODELNAME</font>))</strong></p>
<ul>
<li><p>Requires the <code>effects</code> package.</p></li>
<li><p>Provides a term-plot of the estimated regression line with 95% confidence interval for the mean.</p></li>
</ul></li>
<li><p><strong><font color='red'>DATASETNAME$log.y</font> <code>&lt;-</code> log(<font color='red'>DATASETNAME$y</font>)</strong></p>
<ul>
<li>Creates a transformed variable called log.y – change this to be more specific to your “<span class="math inline">\(y\)</span>” or “<span class="math inline">\(x\)</span>”.</li>
</ul></li>
<li><p><strong>predict(<font color='red'>MODELNAME</font>, se.fit=T)</strong></p>
<ul>
<li>Provides fitted values for all observed <span class="math inline">\(x\text{&#39;s}\)</span> with SEs for the mean.</li>
</ul></li>
<li><p><strong>predict(<font color='red'>MODELNAME</font>, newdata=tibble(<font color='red'>x</font> = <font color='red'>XNEW</font>), interval=“confidence”)</strong></p>
<ul>
<li>Provides fitted value for a specific <span class="math inline">\(x\)</span> (XNEW) with CI for the mean. Replace <code>x</code> with name of explanatory variable.</li>
</ul></li>
<li><p><strong>predict(<font color='red'>MODELNAME</font>, newdata=tibble(<font color='red'>x</font> = <font color='red'>XNEW</font>), interval=“prediction”)</strong></p>
<ul>
<li>Provides fitted value for a specific <span class="math inline">\(x\)</span> (XNEW) with PI for a new observation. Replace <code>x</code> with name of explanatory variable.</li>
</ul></li>
<li><p><strong>qt(0.975, df=<font color='red'>n</font> - 2)</strong></p>
<ul>
<li>Gets the <span class="math inline">\(t^*\)</span> multiplier for making a 95% interval with <span class="math inline">\(n-2\)</span> replaced by the sample size – 2.</li>
</ul></li>
</ul>

</div>
<div id="section7-10" class="section level2">
<h2><span class="header-section-number">7.10</span> Practice problems</h2>
<p>We will continue with the treadmill data set introduced in Chapter <a href="chapter1.html#chapter1">1</a> and the SLR fit in the practice problems in Chapter <a href="chapter6.html#chapter6">6</a>. The following code will get you back to where we stopped at the end of Chapter <a href="chapter6.html#chapter6">6</a>:</p>
<pre><code>treadmill &lt;- read_csv(&quot;http://www.math.montana.edu/courses/s217/documents/treadmill.csv&quot;,
                      header=T)
plot(TreadMillOx~RunTime, data=treadmill)
tm &lt;- lm(TreadMillOx~RunTime, data=treadmill)
summary(tm1)</code></pre>
<p>7.1. Use the output to test for a linear relationship between treadmill oxygen and run time, writing out all 6+ steps of the hypothesis test. Make sure to address scope of inference and interpret the p-value.</p>
<p>7.2. Form and interpret a 95% confidence interval for the slope coefficient “by hand” using the provided multiplier:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qt</span>(<span class="fl">0.975</span>, <span class="dt">df=</span><span class="dv">29</span>)</code></pre></div>
<pre><code>## [1] 2.04523</code></pre>
<p>7.3. Use the <code>confint</code> function to find a similar confidence interval, checking your previous calculation.</p>
<p>7.4. Use the <code>predict</code> function to find fitted values, 95% confidence, and 95% prediction intervals for run times of 11 and 16 minutes.</p>
<p>7.5. Interpret the CI and PI for the 11 minute run time.</p>
<p>7.6. Compare the width of either set of CIs and PIs – why are they different? For the two different predictions, why are the intervals wider for 16 minutes than for 11 minutes?</p>
<p>7.7. The Residuals vs Fitted plot considered in Chapter <a href="chapter6.html#chapter6">6</a> should have suggested slight non-constant variance and maybe a little missed nonlinearity. Perform a log-transformation of the treadmill oxygen response variable and re-fit the SLR model. Remake the diagnostic plots and discuss whether the transformation changed any of them.</p>
<p>7.8 Summarize the <span class="math inline">\(\log(y) \sim x\)</span> model and interpret the slope coefficient on the transformed and original scales, regardless of the answer to the previous question.</p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-Moore2007">
<p>Moore, Johnnie N., Joel T. Harper, and Mark C. Greenwood. 2007. “Significance of Trends Toward Earlier Snowmelt Runoff, Columbia and Missouri Basin Headwaters, Western United States.” <em>Geophysical Research Letters</em> 34 (16). doi:<a href="https://doi.org/10.1029/2007GL031022">10.1029/2007GL031022</a>.</p>
</div>
<div id="ref-Greenwood2011">
<p>Greenwood, Mark C., Joel Harper, and Johnnie Moore. 2011. “An Application of Statistics in Climate Change: Detection of Nonlinear Changes in a Streamflow Timing Measure in the Columbia and Missouri Headwaters.” In <em>Handbook of the Philosophy of Science, Vol. 7: Statistics</em>, edited by P.S. Bandyopadhyay and M. Forster, 1117–42. Elsevier.</p>
</div>
<div id="ref-R-car">
<p>Fox, John, and Sanford Weisberg. 2016. <em>Car: Companion to Applied Regression</em>. <a href="https://CRAN.R-project.org/package=car" class="uri">https://CRAN.R-project.org/package=car</a>.</p>
</div>
<div id="ref-Fox2003">
<p>Fox, John. 2003. “Effect Displays in R for Generalised Linear Models.” <em>Journal of Statistical Software</em> 8 (15): 1–27. <a href="http://www.jstatsoft.org/v08/i15/" class="uri">http://www.jstatsoft.org/v08/i15/</a>.</p>
</div>
<div id="ref-Dieser2010">
<p>Dieser, Markus, Mark C. Greenwood, and Christine M. Foreman. 2010. “Carotenoid Pigmentation in Antarctic Heterotrophic Bacteria as a Strategy to Withstand Environmental Stresses.” <em>Arctic, Antarctic, and Alpine Research</em> 42(4): 396–405. doi:<a href="https://doi.org/10.1657/1938-4246-42.4.396">10.1657/1938-4246-42.4.396</a>.</p>
</div>
<div id="ref-Greenwood2002">
<p>Greenwood, Mark C., and N.F. Humphrey. 2002. “Glaciated Valley Profiles: An Application of Nonlinear Regression.” <em>Computing Science and Statistics</em> 34: 452–60.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="79">
<li id="fn79"><p>We can also write this as <span class="math inline">\(E(y_i|x_i) = \mu\{y_i|x_i\} = \beta_0 + \beta_1x_i\)</span>, which is the notation you will see if you continue into the <em>Methods of Data Analysis I</em> course. We will use notation that is consistent with how we originally introduced the methods.<a href="chapter7.html#fnref79">↩</a></p></li>
<li id="fn80"><p>There is an area of statistical research on how to optimally choose x-values to get the most precise estimate of a slope coefficient. In observational studies we have to deal with whatever pattern of <span class="math inline">\(x\text{&#39;s}\)</span> we ended up with. If you can choose, generate an even spread of <span class="math inline">\(x\text{&#39;s}\)</span> over some range of interest similar to what was used in the <em>Beers</em> vs <em>BAC</em> study to provide the best distribution of values to discover the relationship across the selected range of x-values.<a href="chapter7.html#fnref80">↩</a></p></li>
<li id="fn81"><p>See <a href="http://fivethirtyeight.com/features/which-city-has-the-most-unpredictable-weather/" class="uri">http://fivethirtyeight.com/features/which-city-has-the-most-unpredictable-weather/</a> for an interesting discussion of weather variability where Great Falls, MT had a very high rating on “unpredictability”.<a href="chapter7.html#fnref81">↩</a></p></li>
<li id="fn82"><p>It is actually pretty amazing that there are hundreds of locations with nearly complete daily records for over 100 years.<a href="chapter7.html#fnref82">↩</a></p></li>
<li id="fn83"><p>All joking aside, if researchers can find evidence of climate change using <strong><em>conservative</em></strong> methods (methods that reject the null hypothesis when it is true less often than stated), then their results are even harder to ignore.<a href="chapter7.html#fnref83">↩</a></p></li>
<li id="fn84"><p>The simplest adjustment for multiple testing is using what is called a Bonferroni adjustment, where you multiply all the p-values by the number of tests performed. It controls the chances of at least one error to be same as your Type I error rate for one test.<a href="chapter7.html#fnref84">↩</a></p></li>
<li id="fn85"><p>It took many permutations to get competitor plots this close to the real data set and they really aren’t that close.<a href="chapter7.html#fnref85">↩</a></p></li>
<li id="fn86"><p>If the removal is of a point that is extreme in x-values, then it is appropriate to note that the results only apply to the restricted range of x-values that were actually analyzed. Our results only ever apply to the range of x-values we had available so this is a relatively minor change.<a href="chapter7.html#fnref86">↩</a></p></li>
<li id="fn87"><p>Note <code>exp(x)</code> is the same as <span class="math inline">\(e^{(x)}\)</span> but easier to read in-line and <code>exp()</code> is the R function name to execute this calculation.<a href="chapter7.html#fnref87">↩</a></p></li>
<li id="fn88"><p>This transformation could not be applied directly to the education growth score data in Chapter <a href="chapter5.html#chapter5">5</a> because there were negative “growth” scores.<a href="chapter7.html#fnref88">↩</a></p></li>
<li id="fn89"><p>This silly nomenclature was inspired by <span class="citation">De Veaux, Velleman, and Bock (<a href="#ref-DeVeaux2001">2001</a>)</span> <em>Stats: Data and Models</em> text. If you find this too cheesy, you can just call it x-vee.<a href="chapter7.html#fnref89">↩</a></p></li>
<li id="fn90"><p>I have suppressed some of the plotting code in this and the last chapter to make “pretty” pictures - which you probably are happy to not see it until you want to make a pretty plot on your own. All the code used is available upon request.<a href="chapter7.html#fnref90">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chapter6.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chapter8.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": ["Greenwood_Book.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
